### ISSUE TITLE
Web workers support?

### ISSUE THREAD

**Issue by hinti** [ember-cli/ember-cli#1011]
Hi, how can I use web workers within an ember-cli based project?

Relevant SO-Question: 
http://stackoverflow.com/questions/24175120/ember-cli-project-and-web-workers

**Comment by stefanpenner** [comment]
still important, we are planning on re-working the internal build flow to enable addons + nested addons, I will keep this in mind as that begins.

**Comment by James1x0** [comment]
+1

**Comment by abuiles** [comment]
Closing too in favor of RFC.

**Comment by nruth** [comment]
Does that mean there's an RFC for this? Where do they live?

**Comment by abuiles** [comment]
@nruth no, it means closing in favor of someone opening a RFC here http://github.com/ember-cli/rfcs :)

**Comment by nruth** [comment]
Ah ok, thanks for explaining. :)

**Comment by janmisek** [comment]
Hello

It is already possible to hook workers scripts into ember-cli build process (including watching) even it is not straightforward. 

**Option 1:  workers does not need to reuse routines from application**

Its possible to include own building tree in `Brocfile.js`
```js

var webpackify = require('broccoli-webpack');

MyApp.prototype.workerJavascript = function () {

    var bundler = webpackify(path.resolve('./worker'), {
        entry: './main',
        output: {filename: './assets/worker.js'},
        devtool: 'eval',
        module: {
            loaders: [
                {test: /\.js$/, loader: 'babel-loader'},
            ]
        }
    });
    return bundler;
};

MyApp.prototype.toArray = function () {
    var trees = EmberApp.prototype.toArray.apply(this, arguments);
    // extra builders
    trees.push(this.workerJavascript());
    // ...
    return trees;
};
```
Worker code is expected to reside in `./worker` dir. entry point of worker is `main.js`. Instead of `webpackify` it is possible to use `broccoli-babel-transpiler` and `broccoli-es6modules` which are used by ember-cli. Worker code could be written in es6 favor including eg. `import`. I can publish gist if needed.

**Option 2:  workers need to reuse code from application**

In that case I would suggest to create new standalone application which will contain the worker logic. Routines to be shared between worker and application needs to be separated to addon used among them. 

Also the worker app need to be placed somewhere in parent application directory, then `broccoli-static-compiler` (pickFiles) could be used to pick built output of worker and copy it to app assets. 

Of course this solution is intended only for long live workers, not the "spawn-do-die" workers, because whole ember stack needs to be loaded inside worker's thread. I briefly tried to include ember.js in worker and it worked. 

For these purposes I am now working on addon which will publish interface defined by worker as standard ember service and provides easy execution of worker methods utilizing promises. Not the addon yet, just platform, but already passing tests. It can be seen here: https://github.com/janmisek/workerio

**Comment by stefanpenner** [comment]
we have plans to offer first class support for this, likely as an extension of the packager + engine efforts.

**Comment by janmisek** [comment]
@stefanpenner looking forward

**Comment by AdamBuczynski** [comment]
Any progress on this feature?

**Comment by listepo** [comment]
+1

**Comment by runspired** [comment]
@listepo as soon as the new packager stuff lands (I think ember-cli 2.0?) I'll be rapidly pushing out `ember-skyrocket`.  Work is starting this week on everything that doesn't necessitate the packager changes.

**Comment by listepo** [comment]
@runspired :+1:

**Comment by stefanpenner** [comment]
> (I think ember-cli 2.0?)

sometime during the 2.x cycle

**Comment by stefanpenner** [comment]
somewhat relevant (atleast as a basic high level escape valve https://github.com/ember-cli/rfcs/pull/28)

**Comment by ivaylopivanov** [comment]
+1

**Comment by Leooo** [comment]
@janmisek any hint of how to use your code in option 1 in ember-cli-build? Thanks

**Comment by Leooo** [comment]
@janmisek any hint on how to do your option 1 with ember-cli-build? getting an `app.protoype undefined` when trying:
`````
  module.exports = function(defaults) {
    var app = new EmberApp(defaults, {
      ..
    });
    ..
    app.prototype.workerJavascript = function () {  .. });
    app.prototype.toArray = function () { .. });
    return app.toTree();
  }
`````

**Comment by kanongil** [comment]
So… I guess this died…

**Comment by krzkrzkrz** [comment]
Sad, was also looking forward to this....
