### ISSUE TITLE
ember-cli 5 makes the quick start guide error

### ISSUE THREAD

**Issue by jacobnlsn** [ember-cli/ember-cli#10295]
I think the issue is in ember-cli-app-version but posting an issue here for visibility

https://github.com/ember-cli/ember-cli-app-version/pull/410

> Full disclosure, looked very little into this. I am new to ember and just having issues going through the quick start guide, so spent some time trying to figure out why.
> 
> With ember-cli 5 [getting released as latest](https://www.npmjs.com/package/ember-cli?activeTab=versions) the [quick start guide](https://guides.emberjs.com/release/getting-started/quick-start/) is failing on ember new ember-quickstart --lang en
> 
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: ember-quickstart@0.0.0
> npm ERR! Found: ember-source@5.0.0
> npm ERR! node_modules/ember-source
> npm ERR!   dev ember-source@"~5.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer ember-source@"^3.28.0 || ^4.0.0" from ember-cli-app-version@6.0.0
> npm ERR! node_modules/ember-cli-app-version
> npm ERR!   dev ember-cli-app-version@"^6.0.0" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> 

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember version --verbose && npm --version && yarn --version
ember-cli: 5.0.0
node: 18.16.0
acorn: 8.8.2
ada: 1.0.4
ares: 1.19.0
brotli: 1.0.9
cldr: 42.0
icu: 72.1
llhttp: 6.0.10
modules: 108
napi: 8
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.8+quic
simdutf: 3.2.2
tz: 2022g
undici: 5.21.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.15
v8: 10.2.154.26-node.26
zlib: 1.2.13
os: darwin arm64
9.5.1
zsh: command not found: yarn
```

**Comment by simonihmig** [comment]
Can confirm. The app blueprint was updated to `ember-source@5.0.0`, but `ember-cli-app-version` is causing a peer dependency conflict. 

The PR of yours looks good, we should get that package updated asap!

**Comment by kategengler** [comment]
We merged that PR and are waiting for https://github.com/ember-cli/ember-cli-app-version/pull/411 so that we can release a patch of ember-cli-app-version.

I am working on releasing a patch of ember-resolver after merging https://github.com/ember-cli/ember-resolver/pull/916 

Also courtesy of @NullVoxPopuli we have a PR for ember-cli-dependency-checker https://github.com/quaertym/ember-cli-dependency-checker/pull/144

This is likely also failing ember-cli's CI as well as the tutorial, but being hidden by https://github.com/ember-template-lint/ember-template-lint/issues/2912 which is causing both to fail as well.
