### ISSUE TITLE
`test` script should not run `lint:*` scripts

### ISSUE THREAD

**Issue by HeroicEric** [ember-cli/ember-cli#10383]
The `package.json` generated from the blueprints includes a bunch of helpful scripts like `test` and `lint`.

The `lint` script concurrently runs all of the `lint:*` scripts, which is nice.

The `test` script concurrently runs all of the `test:*` scripts AND the `lint:*` scripts, which feels strange to me. Why does the `test` script also run the linting scripts?

I think it is quite common for these scripts to ran separately in CI, which is even the case in the default GitHub Actions workflow included in the blueprint. This results all the linting scripts being run twice, once via `yarn lint` and once via `yarn test`.

**Comment by kategengler** [comment]
👋 This has been the case since at least 3.18 and was specified in https://rfcs.emberjs.com/id/0121-remove-ember-cli-eslint

Here is the commit that did this https://github.com/ember-cli/ember-cli/commit/754504c43d2f212c35a0615fae01d891e049a6f6 which gives more context. I'll highlight this part of the commit message, which is still a statement I'd agree with:

> This means that we **must** ensure that `npm test` (or `yarn test`) fails when we consider the repository to be in a "bad state".

You can, of course, customize the scripts in your own project. You can also customize CI and use `yarn lint` and `yarn test:ember` separately.
