### ISSUE TITLE
Handlebars Helper not registering?

### ISSUE THREAD

**Issue by mlb5000** [ember-cli/ember-cli#1130]
I have a helper like this:

```
//app/helpers/rack-preview.js
import Ember from 'ember';

export default Ember.Handlebars.helper('rack-preview', Ember.View.extend({
    templateName: 'rack-preview'
    ...
});

//app/templates/rack-preview.hbs
{{some template}}
```

However, when I go to use I from another template I get the following error:

```
Uncaught TypeError: undefined is not a function vendor.js:43535
  helperMissingHelper vendor.js:43535
  program1 app/templates/racks.js:18
  prog vendor.js:10872
  CoreView.extend.render vendor.js:39701
  EmberObject.extend._renderToBuffer vendor.js:38609
  apply vendor.js:21133
  superFunction vendor.js:17840
  CoreView.extend._renderToBuffer vendor.js:40307
  apply vendor.js:21133
  superWrapper vendor.js:20716
  instrumentRenderToBuffer vendor.js:38590
  instrument vendor.js:16768
  EmberObject.extend.renderToBuffer vendor.js:38589
  merge.renderToBufferIfNeeded vendor.js:38374
  CoreView.extend.renderToBufferIfNeeded vendor.js:40314
  merge.ensureChildrenAreInDOM vendor.js:37914
  View.extend._ensureChildrenAreInDOM vendor.js:37879
  DeferredActionQueues.invoke vendor.js:21736
  DeferredActionQueues.flush vendor.js:21786
  Backburner.end vendor.js:21249
  Backburner.run vendor.js:21304
  apply vendor.js:21134
  run vendor.js:19774
  Adapter.extend.ajax.Ember.RSVP.Promise.hash.success vendor.js:62186
  jQuery.Callbacks.fire vendor.js:3214
  jQuery.Callbacks.self.fireWith vendor.js:3326
  done vendor.js:9370
  jQuery.ajaxTransport.send.callback vendor.js:9780
```

For some reason the `helper` object in that function comes out as `undefined`.

ember-cli 0.0.34
Ember 1.6.0.beta-5

**Comment by atduskgreg** [comment]
I know I'm a bit late to this party, but this is kinda baffling. I'm a relative ember noob switching over an app that had outgrown the single file app.js structure into ember-cli. Am I reading this correctly that, in ember-cli, there's simply no way for my existing helpers (or anything like them) to work? For example, the helper that was previously defined here:

https://github.com/atduskgreg/SneakGame/blob/master/js/app.js#L381

and that I'm now trying to put in its own file here:

https://github.com/atduskgreg/SneakGame/blob/ember-cli-refactor/app/helpers/format-square.js

All that is doing is calling a bit of utility code of my own to format one of my objects into a human readable form. And it doesn't work in ember-cli and I think I'm reading in this thread that there is no way for it to work. Is there truly no way for me to do that in ember-cli without making drastic refactors to my code?

This seems a bit baffling and, as a beginner, it makes me wish that the intro tutorials had said clearly "helpers considered harmful" because now I'm a bit up a creek here...

**Comment by ridget** [comment]
Hey @atduskgreg this is how I ended up approaching it, which looks very similar to yours: https://github.com/ridget/transactions/blob/master/app/helpers/to-currency.js

implemented in a view here:
https://github.com/ridget/transactions/blob/master/app/templates/transactions/index.hbs

As like you, I didn't want to extract straight out to a component straight away.

**Comment by jdhines** [comment]
Just hit this as well, but the documentation helped me out. I had initially generated a helper called "money" while following a tutorial written without ember-cli, and got the error `Assertion Failed: A helper named 'money' could not be found`. However, renaming the helper file from `money.js` to `format-money.js` allowed me to use the helper in my template like so:

`{{format-money cost}}`

(Registering Handlebars Helpers)[http://www.ember-cli.com/#resolving-handlebars-helpers] states that
>Limiting automatically-loaded helpers to those that contain dashes is an explicit decision made by Ember.
If you want to have a helper without a hyphen in the name, then as the docs state you have to load it explicitly.

**Comment by aranaravi** [comment]
Hi folks,
   apart from makeBoundHelper, why others helpers are not working in ember cli, i need to compare two different string.help me with share some sample code.

**Comment by clekstro** [comment]
I'm with @atduskgreg on this.

I'm also relatively new to Ember-CLI, but I've re-read this thread several times now and am trying to understand why this is not a bug.  If Ember-CLI allows you to create helpers, why shouldn't an Ember-CLI addon allow you to register a hyphenated helper under `addons/helpers/foo-helper.js` and then re-export it in `app/helpers/foo-helper.js`? The documented workaround to export this as a component seems like it's simply a hack around behavior that should be supported.

My own use case is creating an addon that simply adds a helper to output a data attribute within certain environments for testing purposes.  Using a component here feels very awkward, when it works just fine within a normal Ember-CLI generated app as a helper.

Also, perhaps I'm mistaken, but isn't this precise pattern working with Ember-CLI 0.2.0 [here](https://github.com/johnotander/ember-cli-dates) and [here](https://github.com/johnotander/ember-linkify), albeit with the use of an initializer?  I have tried to emulate both of these repos using 0.2.3 and have had no success.
