### ISSUE TITLE
[feature request] Allow for subdirectories in components

### ISSUE THREAD

**Issue by ssured** [ember-cli/ember-cli#1219]
I am developing a form editor, which currently consists of a multiple of components named like this:

```
/components/form-select.coffee
/components/form-input.coffee
/components/form-number.coffee
...
```

It would be nice if components (and their templates) can live in their own subdirectory, like this:

```
/components/form/select.coffee
/components/form/input.coffee
/components/form/number.coffee
...
```

To me it would be better for
1. Project structure, in the file explorer it's easier to find what you are searching for
2. Library development, it would allow for splitting the files of into a separate repo, having its own unit tests. The library can then easily be added using symlinks. Also this structure might benefit the plugin work @rjackson is doing.

**Comment by lightblade** [comment]
Now that we're on HTMLBars, is this still an issue?

**Comment by phcoliveira** [comment]
Maybe I am late to the discussion, since components can be nested in subdirectories and I am already using them this way, but I am missing the reason for imposing the dash in a component's name.

I thought that components would use their own names instead of classic tag names, and, for such, W3C recommends using a dash, like this: ```<my-tag></my-tag>```, justifying the imposition. But, if this is true, how the slash is going to be handled, since it is not valid HTML markup? And, if this is not true, if components are not going to use their own names instead of classic tag names, then why imposing the dash in their names?

**Comment by stefanpenner** [comment]
> Maybe I am late to the discussion, since components can be nested in subdirectories and I am already using them this way, but I am missing the reason for imposing the dash in a component's name.

It actually boils down to us not believing `/` in a component name is appropriate. Our short term plan for pods, will likely enable "pod local" components and helpers (this prevents the long slashed pathed based component names), which means the `dash` will once again be required. 

So removing the `-` requirement, becomes a hazard for ^ work.

**Comment by stefanpenner** [comment]
Expect an updating pods RFC soon outlining this.

**Comment by jleppert** [comment]
This thread is everything about why I hate Ember.

**Comment by stefanpenner** [comment]
@jleppert I appreciate the constructive feedback...

**Comment by ugoa** [comment]
@stefanpenner HAHAHAHAHAHA...

**Comment by jleppert** [comment]
I wasted over an hour of time trying to figure out why ember wasn't finding my component, giving no clue as to why. Only to find out that it's some random decision instead of letting people decide how to name their files...

**Comment by stefanpenner** [comment]
@jleppert it is not random, it is to avoid ambiguity in the resolution of components and to prevent locking in functionality future work (local component lookup and some variants of angle bracket components) cannot support.

Now it would be handy if in development we detected these scenarios and warned/threw a helpful error. Unfortunately, your original comment failed to provide any actionable feedback, which prevented me from realizing the actual pain and recommending this as a potential resolution.

Although you may have frustrations, please be sure to provide it in the form of constructive feedback. Otherwise it is merely a wasted exchange. We respond quite well to polite constructive feedback, but aren't terribly motivated by excessively negative remarks (especially when they provide little or no concrete points).

**Comment by wycats** [comment]
> I wasted over an hour of time trying to figure out why ember wasn't finding my component, giving no clue as to why. Only to find out that it's some random decision instead of letting people decide how to name their files...

> Now it would be handy if in development we detected these scenarios and warned/threw a helpful error. Unfortunately, your original comment failed to provide any actionable feedback, which prevented me from realizing the actual pain and recommending this as a potential resolution.

I agree with both of you. It seems like we have a painful error-case missing.

@rwjblue any interest in adding an explicit error in this scenario?

**Comment by jleppert** [comment]
I disagree. If your goal is to provide for convention over configuration, you think it's wise to break with the convention of a standard directory structure and naming convention that has been in use as the standard of almost every OS and file system? People expect that when you name a file something it should be made available as that name and be resolved as such. If you're concerned about ambiguity, you can use a name space like you've already done.

Imagine the frustration of creating a text file and naming it something only to find that the text editor not only won't open that file, it has no idea about the existence of said file because it doesn't conform to arbitrary naming conventions at the personal choice and whim of the text editor author? And not only that but it fails to tell the user the real problem, making an obvious problem more difficult and resulting in a discussion -- the file in fact was found, but we aren't considering it because it doesn't have the correct name.

**Comment by rwjblue** [comment]
> @rwjblue any interest in adding an explicit error in this scenario?

I'm happy to add debugging aids (assertions/warnings/deprecations/etc) if an actual scenario is provided.  All we've gotten so far is that @jleppert is frustrated, no steps to reproduce or explanation of what was happening.

@jleppert - Please open a new issue explaining the problems that you faced, and how we can reproduce them so that we might actually do something about this...

**Comment by wycats** [comment]
> I disagree.

@jleppert what exactly do you disagree with?

**Comment by stefanpenner** [comment]
The resolution without a dash is ambiguous in this domain, as an angle bracket component resolved via local component lookup wouldn't be differentiable from a real DOM tag. As with web components, the dash ensures no conflict with current or future platform provided tags, and is intended to unambiguously refer to a custom tag.

This ultimately leads to two different mutually exclusive constraints, to resolve the tie we look to the domain where the entity is referenced html/htmlbars and consider the invariants (like DOM/web component naming conventions). It would be great if we could satisfy all constraints, but this scenario appears to require some trade offs.

@wycats we do currently provide an error if the component was created via generators, but it would appear we need some sort of additional pre-flight check. This may fall into the category of ember Doctor like scripts, or maybe at resolution time in dev mode all tags trigger a check via resolver for an invalid component name, erroring or warning. You are likely more familiar then I with this part of glimmer, do we have such a hook?

**Comment by wycats** [comment]
Glimmer2 provides a one-time hook for "tag name" -> "component name" that we could use.

**Comment by brandonparsons** [comment]
In my opinion, a lot of this pain can also be fixed by putting components in a pod structure.  I used to have a huge `/components` directory with all kinds of clutter, but found that by moving to pods (`/pods/components/my-component/component.js` & `pods/components/my-component/template.hbs`) it's all much cleaner.

Perhaps this option could be better advertised? I have been using Ember since pre 1.0 and didn't even know that this was an option until last week.

**Comment by stefanpenner** [comment]
> Glimmer2 provides a one-time hook for "tag name" -> "component name" that we could use.

Nice, that will be nice to hook into. Is this Glimmer or glimmer@2

> In my opinion, a lot of this pain can also be fixed by putting components in a pod structure. I used to have a huge /components directory with all kinds of clutter, but found that by moving to pods (/pods/components/my-component/component.js & pods/components/my-component/template.hbs) it's all much cleaner.
> 
> Perhaps this option could be better advertised? I have been using Ember since pre 1.0 and didn't even know that this was an option until last week.

There are some things that must be cleaned up before we swap over to pods being the default. It is likely still a good choice, but until that work happens I am uneasy to make it the default. Someone needs to "own" that transition, and help move it forward.

**Comment by sergetab** [comment]
>It actually boils down to us not believing / in a component name is appropriate. Our short term plan for >pods, will likely enable "pod local" components and helpers (this prevents the long slashed pathed >based component names), which means the dash will once again be required.

@stefanpenner Does that mean folders in components are not going to be supported in the future?  We currently use them for our components.

**Comment by stefanpenner** [comment]
> @stefanpenner Does that mean folders in components are not going to be supported in the future? We currently use them for our components.

there will be support for components in folders, but it will likely be via the local component lookup pattern i believe @rwjblue is working on as part of some next steps in making pods a default pattern. I am unsure if their is an RFC with that or not

**Comment by kimroen** [comment]
@sergetab Robert talked a bit about this in [his talk at the Austin Ember Meetup](https://www.youtube.com/watch?v=1wc3a_ttTy0&t=28m18s), and again in [the latest episode of EmberLand](http://ember.land/episodes/17) - maybe that would be of interest.

**Comment by runspired** [comment]
I forget, but I believe there was a blocker @rwjblue faced in created an addon to test the "fractal pods" pattern.  If so, has that cleared? And if so, want to spec it out a bit?  I could take a stab at an addon implementing it to test with.

**Comment by htmldrum** [comment]
:+1: for "fractal pods"

**Comment by RustyToms** [comment]
If we could use the {{component}} helper in block form we would at least have a work around for this.

```
{{#component "directory/component-name"}}
  ...some stuff...
{{/component}}
```

**Comment by runspired** [comment]
@RustyToms how does that relate to this?

**Comment by RustyToms** [comment]
Sorry, I guess that is a suggestion for ember, not ember-cli? This was the thread I found when trying to figure out how to solve using components in subdirectories in block form. We already use them extensively as we have over 100 components in our app and needed better organization. This block-form problem is the only problem that I have really run into.

**Comment by RustyToms** [comment]
Sorry, user error I think, it should work fine...

**Comment by egee-irl** [comment]
It's unclear as it whether or not Ember supports component sub-directories. Some comments claim Ember supports it, while other comments do not. The official documentation does not say anything about sub-directories.

I am coming from the AngularJS world and my simple Ember project has 23 components. It seems like an oversight that sub-directories are not supported.

**Comment by ibraheem4** [comment]
+1 would be a nice-to-have feature.

**Comment by kumkanillam** [comment]
@ibraheem4 @egee-irl you can create component in sub-directory.
