### ISSUE TITLE
Uncaught Error: Could not find module /app 

### ISSUE THREAD

**Issue by Nininea-zz** [ember-cli/ember-cli#1512]
I have updated ember-cli version, and after build application didn't load. my application name is 'scripts' and in verndor.js (ln.42)  throws this error
 "Uncaught Error: Could not find module scripts/app "
this is package.json 

{
  "name": "Scripts",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "test"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "https://github.com/stefanpenner/ember-cli",
  "engines": {
  "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "body-parser": "^1.2.0",
    "broccoli-asset-rev": "0.0.17",
    "broccoli-ember-hbs-template-compiler": "^1.5.0",
    "broccoli-merge-trees": "^0.1.4",
    "broccoli-static-compiler": "^0.1.4",
    "ember-cli": "0.0.40",
    "ember-cli-ember-data": "0.1.0",
    "ember-cli-ic-ajax": "0.1.1",
    "express": "^4.1.1",
    "glob": "^3.2.9",
    "originate": "0.1.5"
  }
}

this issue is very critical for me

**Comment by devinrhode2** [comment]
I have this error occurring after upgrading to ember-cli 0.2.0 and tracked it down to the _`coffees6`_ addon, which is a simple 64 line script here: https://github.com/alexspeller/ember-cli-coffees6/blob/master/index.js

You can read full details of the bug here: https://github.com/alexspeller/ember-cli-coffees6/issues/9

But the `coffees6` addon is a hack in the first place. [I'm more concerned about seeing better separation of concerns between coffeescript and ecmascript](https://github.com/michaelficarra/CoffeeScriptRedux/issues/338).

**Comment by devinrhode2** [comment]
Important note: it is rather obscure that the coffees6 addon **still completely works except for with the app/app file** (app.coffee/app.js)
