### ISSUE TITLE
Using a partial with pods

### ISSUE THREAD

**Issue by nathanpalmer** [ember-cli/ember-cli#1538]
Assuming we have it setup in pod format is there a way to use a partial within the pod directory? I'm trying to avoid having to throw the template under templates.

``` javascript
var App = Ember.Application.extend({
  modulePrefix: 'test',
  podModulePrefix: 'test/pods',
  Resolver: Resolver
});
```

The file structure would look something like this.

pods/
pods/posts/
pods/posts/template.hbs
pods/posts/_post.hbs

It seems though that the file isn't even served up (doesn't show up in source) unless it's either called template or exists in the /templates/ directory.

**Comment by buschtoens** [comment]
I'm on vacation (happy new year!) and only got my phone, otherwise I'd probably find out where to put this, but I got an idea.

It would be sexy if this... 

```hbs
{{user-form 
  firstName=model.firstName
  lastName=model.lastName
  phone=model.phone
}}```

...was equal to... 

```hbs
{{user-form model}}
```

As far as I can see, this is 100% backwards compatible and allows for great flexibility. 


Otherwise you'd have to either prefix the attributes in the template with `model.` or pass in each attribute by hand, which can get tedious very quickly.

**Comment by eccegordo** [comment]
@buschtoens That would be a very nice feature.

**Comment by rwjblue** [comment]
> {{user-form model}}

Components are not allowed to have ordered params (only hash params).

> you'd have to either prefix the attributes in the template with model.

We are removing `Ember.ObjectController` in 2.0 (and deprecating in 1.11). So you will have to prefix your model properties in your templates either way...

**Comment by buschtoens** [comment]
> Components are not allowed to have ordered params (only hash params).

This is exactly why this would be backwards compatible. Starting from the next minor version update, components would accept one ordered parameter (or multiple maybe) and the traditional hash params. Those params are then merged from left to right. 

```hbs
{{order-summary
 model
 freeDrinks=freeDrinks
 deliveryCost="7.5"
}}

// order-summary.hbs
{{#if model.tacos}}
 You ordered {{model.tacos}} tacos. 
{{/if}} 

{{#if model.tortillas}}
 You ordered {{model.tortillas}} tortillas. 
{{/if}}

You get {{model.freeDrinks}} free drinks. And the delivery cost is ${{mosel.deliveryCost}}. 
```

The great advantage here is, that you don't have to explicitly pass in each and every value, but could just throw in the current model or other objects.

**Comment by eoinkelly** [comment]
I would like to +1 for partials being loaded from pod directories. I think there is a use case for not forcing the "template" of a pod to be a single file.

We are currently building a prototype app (btw: so much :heart: for how easy this is with ember-cli) using pods. Because the design is still not settled we have a lot of example content hard-coded into the templates. We are currently putting our partials in `templates/*.hbs` but ideally we would keep them with their pod - they are sometimes re-used within a pod but never between pods. I think this situation would be mirrored by many "content heavy" sites.

I don't think components would be a good fit for this as the "natural home" for those templates feels like it is the pod itself given that there is no re-use outside it - we are simply trying to make long HTML templates more tractable.

**Comment by jfcouture** [comment]
For those interested, I've been using the following hack to be able to use partials in the pod directory.

```javascript
// in Brocfile.js
// load all .hbs files, not just those named template
EmberApp.prototype._podTemplatePatterns = function() {
  return this.registry.extensionsForType('template').map(function(extension) {
    return new RegExp('.' + extension + '$');
  });
};
```

```javascript
// in app/app.js
// based on https://github.com/ember-cli/ember-cli/pull/1439#issuecomment-50027971
var CustomResolver = Resolver.extend({
  // add a new function to use in the lookup paths (can be first/last/wherever)
  moduleNameLookupPatterns: Ember.computed(function(){
    var arr = this._super();
    arr.unshift(this.handleArbitraryTemplateInPodFormat);
    return arr;
  }),

  // load any template/partial in my pods
  handleArbitraryTemplateInPodFormat: function(parsedName) {
    var podPrefix = this.namespace.podModulePrefix || this.namespace.modulePrefix;

    var fullNameWithoutType = parsedName.fullNameWithoutType;

    if (parsedName.type === 'template') {
      fullNameWithoutType = fullNameWithoutType.replace(/^components\//, '');
    }

    return podPrefix + '/' + fullNameWithoutType;
  }
});
```

**Comment by brandensilva** [comment]
It's been awhile since this has been discussed. Has everyone decided on nested folder spaghetti or what for something simple like partials? 

Right now I'm just leaving the partials in the original template directory structure while the top level resources sit in their pod directory.

If we are going the route of transforming partials into template only components, is their a performance hit for this?

**Comment by maysale01** [comment]
+1

**Comment by ivanbanov** [comment]
+1

**Comment by lindem** [comment]
Just found this issue because I have something that might have been nice to do with partials. Are there any tangible, official moves into the direction of removing or deprecating partials by now, did I miss the memo, or any other news from this past discussion?
