### ISSUE TITLE
smarter ember init?

### ISSUE THREAD

**Issue by eccegordo** [ember-cli/ember-cli#2041]
Are there any plans to make `ember init` smarter?

At ember conf @stefanpenner suggested that it should only take a few minutes to run the upgrade and move on. The review diffs feature is nice. Just wondering if there is a better way to manage the init process.

A few strategies come to mind:
### 1.) Separate dependencies

Separate ember cli "system" dependencies from "user defined" dependencies in `package.json` and `bower.json`. Basically segment the areas where ember init is going to manage things, and a separate area where I have project dependencies. For example I shouldn't have to merge back in `broccoli-sass` every time.
#### pros:
- very declarative
- user intention is respected automatically 
#### cons:
- might be source of confusion and incompatible dependencies
- might lead to ambiguity in the dependency management
- might not always be clear what should be "system" and what should be "user defined"
### 2.) Customizable ignore file

Provide an ignore file which prompts ember init to ignore specific files.
It is very unlikely that I am going to want ember init to override my `router.js` or my `application.hbs` let me exclude those and a save a few clicks during the confirmation step.
#### pros:
- simple and deterministic
- allows for possibility of override flag when you want to review everything
- can commit ignore file to revision control
- automate and control the ember init process across large team and large project
- can be used with above to declare user defined `package.json` and `bower.json` files that are to be treated as sacrosanct and always appended to "system" dependencies.
#### cons:
- more configuration surface area, but is optional
- does not solve the "merge" problem.
### 3.) Smart merge strategy

Apply some heuristics so that ember init can automatically merge in changes, rather than basic overwrite. Perhaps some intelligence around what is going to change and how to merge in the change. For example if a new feature or bug fix necessitates adding or removing a specific line just do it for me.
#### pros:
- if done well, requires very little work from user, merges happen "automagically"
#### cons:
- can be very complex and error prone to implement
- tough problem when there is ambiguity in how to merge
- might not be worth the dev and maintenance upkeep required to keep running smoothly.
- might be too "magical" for some users
### 4.) Merge conflict markers

Do what most revision control systems do and attempt merge only when it can be done cleanly but put in merge conflict markers when can't be merged cleanly.
#### pros:
- is a pattern people know
- can be combined with diff automation tools
#### cons:
- can introduce a lot of noise with a complex merge (where an overwrite is easier)
- still does not save user from having to resolve merges

**Comment by H3Chief** [comment]
It's absolutely ridiculous that this issue was closed. `ember init` at first glance seems like a local alternative to a globally installed `ember-cli`, but it is toxic to your project.

**Comment by stefanpenner** [comment]
> ember init at first glance seems like a local alternative to a globally installed ember-cli

what does this mean?

> but it is toxic to your project.

only if one blindly says "yes"

> And it's saying something that it's a year since this issue was raised an it's still a problem.

not really, lots of work todo!

**Comment by H3Chief** [comment]
> what does this mean?

In scenarios where I might be building many different ember apps, and using the cli to generate structures for them, the global-cli is a bad idea, causing conflicts.  Also, the `ember new <appname>` is a very "heavy handed" operation, that creates not only the scaffolds it needs inside the project folder, but creates the folder itself, as well as performing operations on git that aren't conducive to taking a project that was formerly non-ember, and making it ember.

However, since `ember init` overwrites instead of merges, it causes many of these same issues... whereby it's only easily used on brand new projects. 

> only if one blindly says "yes"

There is no other real feasible option. If you say no, then you lose the whole purpose behind using `ember init` in the first place. Running the `init` is supposed to take care of knowing what deps to introduce.  The ember docs don't really have a good guide on what recommended deps are at any given moment, because they're docs rely so heavily on the ember-cli. 

That means if I chose "no" (because I have too much critical info in my package.json to have to worry about merging back in correctly,) that I have no way of knowing what deps to install in order to use the rest of the generator functions of the cli with confidence... or at least the type of confidence I need to ensure bugs during builds aren't because of an incorrect dependencies I introduced by hand.

> not really, lots of work todo!

We're talking about merging a javascript object, instead of writing out a file. I understand being busy, but the package.json is the heart and soul of a javascript development project, and should be a fairly large priority/consideration.

Ember has a problem with being adopted by the community at large, because of it's huge "getting started/learning curve".  Making Things like this a priority, make a big difference to those evaluating or taking first steps with ember.  

From this perspective, I don't understand how it's been a year for something that seems as simple as changing an overwrite to a merge... for something that is a native javascript object. 

I have no problem working on a PR for this, but that still doesn't answer the question of why this went unaddressed (and in fact was dismissed) for a year, when knowingly the biggest issue with ember adoption is the struggle with getting started.

**Comment by H3Chief** [comment]
All that being said, if you agree to open this issue back up, I *will* work on a PR for it.

**Comment by stefanpenner** [comment]
> the global-cli is a bad idea, causing conflicts.

It actually resolves first relative to the current projects package.json, if it has ember-cli included that is the version of cli it runs. If one isn't present it bounces back to the global.

> However, since ember init overwrites instead of merges, it causes many of these same issues... whereby it's only easily used on brand new projects.

ember init, prompts with several options:

```
➜  ffff git:(master) ✗ ember init bower.json
[?] Overwrite bower.json? (Yndeh)
```

* y: overwrite
* n: don't overwrite
* d: display visual diff to aid in decision making
* e: edit the diff in $EDITOR if $EDITOR is set
* h: display relevant help

```
  y) Yes, overwrite
  n) No, skip
  d) Diff
  e) Edit
  h) Help, list all options
  Answer:
```

> We're talking about merging a javascript object, instead of writing out a file.

It is actually quite a bit more then just "merging", causal order/reconciliation is non-trivial. That is why we provide `e` display diff  and `e` edit diff (for those users with $EDITOR set). To allow them to edit the diff themselves.

> That means if I chose "no" (because I have too much critical info in my package.json to have to worry about merging back in correctly,) that I have no way of knowing what deps to install in order to use the rest of the generator functions of the cli with confidence...

that isn't correct, if you choose `n` and defer to after. You can re-run the initializer on that specific file, and view the diff (or choose to edit, again if you have the posix convention $EDITOR setup)

```js
➜  ffff git:(master) ✗ ember init package.json

version: 1.13.8
installing app
[?] Overwrite package.json? Diff
Index: /Users/stefanpenner/tmp/ffff/package.json
===================================================================
--- /Users/stefanpenner/tmp/ffff/package.json
+++ /Users/stefanpenner/tmp/ffff/package.json
@@ -19,24 +19,22 @@
   "author": "",
   "license": "MIT",
   "devDependencies": {
     "broccoli-asset-rev": "^2.2.0",
-    "ember-ajax": "0.6.3",
-    "ember-cli": "1.13.8",
+    "ember-cli": "1.13.9",
     "ember-cli-app-version": "^1.0.0",
     "ember-cli-babel": "^5.1.5",
     "ember-cli-content-security-policy": "0.4.0",
     "ember-cli-dependency-checker": "^1.1.0",
     "ember-cli-htmlbars": "^1.0.1",
     "ember-cli-htmlbars-inline-precompile": "^0.3.1",
+    "ember-cli-ic-ajax": "0.2.1",
     "ember-cli-inject-live-reload": "^1.3.1",
-    "ember-cli-qunit": "^1.0.3",
+    "ember-cli-qunit": "^1.0.4",
     "ember-cli-release": "0.2.8",
     "ember-cli-sri": "^1.1.0",
     "ember-cli-uglify": "^1.2.0",
-    "ember-data": "2.1.0",
+    "ember-data": "1.13.15",
     "ember-disable-proxy-controllers": "^1.0.1",
-    "ember-export-application-global": "^1.0.4",
-    "ember-resolver": "^2.0.3",
-    "emberx-select-blockless": "1.0.0"
+    "ember-export-application-global": "^1.0.4"
   }
 }

[?] Overwrite package.json? (Yndeh)
```

> Making Things like this a priority, make a big difference to those evaluating or taking first steps with ember.

We take everything quite seriously

>


> From this perspective, I don't understand how it's been a year for something that seems as simple as changing an overwrite to a merge... for something that is a native javascript object.

Yup it would be nice.

> I have no problem working on a PR for this,

ideally someone (maybe you) can write a node_module that provides intelligent/interactive package.json merging. That way we can delegate to it when we merge the package.json. If it turn out to work well, we could gladly accept a pull request.

> From this perspective, I don't understand how it's been a year for something that seems as simple as changing an overwrite to a merge...

If the ember project was entirely focused on package.json management, this likely would have long been improved. The reality is, this is a small piece of a much larger system. We must triage accordingly.

> I have no problem working on a PR for this, but that still doesn't answer the question of why this went unaddressed (and in fact was dismissed) for a year, when knowingly the biggest issue with ember adoption is the struggle with getting started.

Well if merging package.json is truly the biggest barrier of entry, maybe we spent the last year working on all the other pain points?

-----

I am quite concerned with the tone of these comments.

This issue was originally closed, because it is not a bug but an enhancement. Something we now recommend users go through the [rfc](github.com/ember-cli/rfcs) process with.

@rwjblue, an extremely active ember contributor 800+ days github streak 6500+ annual contributions, made a judgement call, deeming it interesting and nice to have (would accept a well formed pull request) but bellow the threshold of what we could consider a blocking issue.

I believe @rwjblue made the correct judgment call, and this issue will remain closed. A

You seem quite enthusiastic about this issue, thats great the best OSS occurs when scratch ones own itch. If you are indeed interested and motivated let me recommend that you provide a POC. Likely in the form of a separate (and tested) node_module, and optionally a PR integrated it.

**Comment by H3Chief** [comment]
> ideally someone (maybe you) can write a node_module that provides intelligent/interactive package.json merging. That way we can delegate to it when we merge the package.json. If it turn out to work well, we could gladly accept a pull request.

I would be willing, but based on your comments, will consider accordingly. If I do, I'll go through the rfc process you mentioned.

> Well if merging package.json is truly the biggest barrier of entry, maybe we spent the last year working on all the other pain points?

:+1: 

>  I am quite concerned with the tone of these comments.

I apologize. I looked through the online documentation, as well as `ember --help`, and as far as I can tell the use of these options aren't documented anywhere. This led me to believe this was more of an issue than it actually is.  I'm guessing the options themselves were added after this issue was closed, or they'd have been mentioned already (since they resolve the concern).

Perhaps the any PR I craft should focus more on helping to document the existing flexibility? Do you know if there *is* somewhere this is documented?

**Comment by stefanpenner** [comment]
> Do you know if there is somewhere this is documented?

Unsure, is suspect we assumed the prompt + h (for help) to be somewhat self documenting.
Maybe this belongs in some sort of extended help. @trabus any thoughts or recommendations?

**Comment by H3Chief** [comment]
The cli's `-h` seems to be self-documenting for options/flags, but not prompts. 

> It actually resolves first relative to the current projects package.json, if it has ember-cli in its package.json then that is the version of cli it runs. If one isn't present it bounces back to the global. 

This is also helpful, and would fit well into a usage/faq's page for the online docs. Until I saw this, and then found your use of `require("resolve")`, I figured it worked like any other cli... in that `package.bin` (cli) based modules don't resolve locally first in the same way that `package.main` (programmatic) modules do.

Having been entrenched in the rest of the node-based world for a few years, I've gotten used to the "avoid global" mantra that has finally seen a year or so of stability. My assumption about conflicts came from that predisposition, combined with no explicit discussion about it in the guides.

**Comment by H3Chief** [comment]
> e: edit the diff in $EDITOR if $EDITOR is set

@stefanpenner this feature isn't in the current build. Was it removed, or is this a regression I should open an issue for?

**Comment by stefanpenner** [comment]
Can you elaborate?

**Comment by stefanpenner** [comment]
The code is present and appears to work when $EDITOR is set. Maybe he UX is confusing?

It is disabled on Windows ie believe. Because no one has a chance to get it working there.

**Comment by stefanpenner** [comment]
Maybe e should just always be present and if someone uses it. And something is set up, it should provide a quick message and a link to the site explaining how to use it
