### ISSUE TITLE
How to create or keep a symlink in dist

### ISSUE THREAD

**Issue by patrick-radius** [ember-cli/ember-cli#2091]
i would like to have a symlink `/api` in the dist folder to an api webroot outside the ember app root.
How can i create this symlink during the build process, or make sure it stays in the dist dir (when i create it manually).

I'm testing ember and ember-cli, i have the same setup for the application in backbone/grunt where this is working fine.

**Comment by ef4** [comment]
@rwjblue the example in your comment silently fails, because `result.directory` is a tmpdir that has already been copied into the apps real output directory by the time `postBuild` runs.

**Comment by rwjblue** [comment]
@ef4: Its possible that it was always wrong, but I believe that at the time I wrote it we were using `broccoli-export-tree` so the `results.directory` was actually `dist/`.   Either way you are right, and it is incorrect today.  The general concept is sound though (making a symlink inside the `postBuild` hook).

It does seem that we should expose the `builder` model's `this.outputPath` to the hook though.  Otherwise, you would be assuming `dist/` which is not guaranteed.

**Comment by kjhangiani** [comment]
Has this.outputPath been exposed here yet?  I have this exact issue, and I've hardcoded dist/assets for now, but this.outputPath would be far cleaner.
