### ISSUE TITLE
content-for 'body'

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#2229]
we should place a 

``` html
{{content-for 'body'}}
```

[here](https://github.com/stefanpenner/ember-cli/blob/master/blueprints/app/files/app/index.html#L16)

this would make addons injecting random stuff (like pre-asset reayd loading indicators) easy peasy.

**Comment by phcoliveira** [comment]
Wouldn't be nice if we could write:
```
{{content-for "body" id="some-id" class="some-class"}}

**Comment by stefanpenner** [comment]
I don't think that makes sense. Your app is not placed here, it is merely a hook for addons to inject random snippets into the index.html

**Comment by Redsandro** [comment]
@stefanpenner 
> I don't think that makes sense.

At least it makes debatable sense, as I found myself wondering (googling) the same as @phcoliveira mentioned:
> Wouldn't be nice if we could write:
> 
> ```
> {{content-for "body" id="some-id" class="some-class"}}
> ```

Because now the app renders into `{{content-for "body"}}` in `index.html` translated to `<div id="ember463" class="ember-view">`, and it would be nice to turn that into e.g. `<section>` with a custom class.

**Comment by nathanhammond** [comment]
This is a low-level Ember concern and has to do with how we set up event listeners and which elements are "under Ember's control." Stop by Slack in #dev-ember to discuss. Regardless this will not be addressed on the Ember CLI side as that is outside the scope of this tool.

(On phone, please forgive terseness.)
