### ISSUE TITLE
Addon doesn't work in project with broccoli-sass or any other preprocessor

### ISSUE THREAD

**Issue by miguelcobain** [ember-cli/ember-cli#2363]
Using ember-cli `0.1.2` I created an addon: https://github.com/miguelcobain/ember-paper
This addon uses it's own styles, like I believe it was fixed in #2150.

However, as pointed by @altrim at https://github.com/miguelcobain/ember-paper/issues/1, it doesn't work with `broccoli-sass`.

Basically, this works:
```bash
$ ember new test-paper
$ cd test-paper
$ npm install --save-dev ember-paper
$ ember server
```

But this doesn't:
```bash
$ ember new test-paper
$ cd test-paper
$ npm install --save-dev broccoli-sass
$ npm install --save-dev ember-paper
$ ember server
```

Throwing the error: `app/styles/app.[scss/sass] does not exist`.

Possibly related with #1866 and #1894.

**Comment by vinodhrajamuralidharan** [comment]
this issue is fixed? Can anyone help me for .less files to work on my addon? as of now .css is working fine but not .less....

**Comment by sglanzer** [comment]
@ash11tw Thanks so much for this solution!  I had been using the method detailed on Pixelhandler's blog for creating an addon, but having to run a separate script was a pain.  Your solution works great for me!

**Comment by lolmaus** [comment]
I was running into this issue in my project using [`ember-cli-compass-compiler`](https://github.com/quaertym/ember-cli-compass-compiler/).

It turned out that the issue was caused either by `broccoli-sass` (which was a requirement of one of other addons) or by a conflict between `broccoli-sass` and `ember-cli-compass-compiler`.

Removing `broccoli-sass` from `package.json` [resolved](https://github.com/quaertym/ember-cli-compass-compiler/issues/45#issuecomment-77601551) the issue for me.

I wonder whether `ember-cli-compass-compiler` is immune to subj.

**Comment by rwjblue** [comment]
0.2.0 allows addons to have their own preprocessors (which sounds like what you need/want here).

I believe this is resolved (or at least further than it was previously and now a different issue may block) so I'm closing this for now...
