### ISSUE TITLE
"ember addon foo" fails with 'permission denied'

### ISSUE THREAD

**Issue by tjhart** [ember-cli/ember-cli#2438]
```bash
TimsMac:tmp tjhart$ ember addon bar
version: 0.1.2
EACCES, permission denied '/usr/local/lib/node_modules/ember-cli/blueprints/addon/files/package.json'
Error: EACCES
 permission denied '/usr/local/lib/node_modules/ember-cli/blueprints/addon/files/package.json'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.writeFileSync (fs.js:977:15)
    at Class.module.exports.generatePackageJson (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:27:8)
    at Class.module.exports.files (/usr/local/lib/node_modules/ember-cli/blueprints/addon/index.js:78:10)
    at Class.Blueprint.install (/usr/local/lib/node_modules/ember-cli/lib/models/blueprint.js:327:36)
    at Class.module.exports.Task.extend.run (/usr/local/lib/node_modules/ember-cli/lib/tasks/install-blueprint.js:50:24)
    at Class.module.exports.Command.extend.run (/usr/local/lib/node_modules/ember-cli/lib/commands/init.js:72:29)
    at $$$internal$$tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
TimsMac:tmp tjhart$ 
```

Creating ember projects, building, testing, serving all work fine. This seems odd since I see reports that others can use the addon generator without issue.

**Comment by stefanpenner** [comment]
* the fact that people have wrong permissions is a bug
* the fact that we do anything that writes to these files is also a bug.

**Comment by rwjblue** [comment]
The `addon` blueprint writes temp `package.json` and `bower.json` files in the blueprint directory, so that it can inherit and modify the default app files. We are not doing this in `afterInstall` because if we modify the files after generation, the diff on `ember init` doesn't show changes (and users can't decline them).

We should probably change https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/index.js#L12-50 to write to the system temp dir and figure out how to make the blueprint use those files (to still allow the `ember init` diff to work).

**Comment by stefanpenner** [comment]
@hjdivad we should take a look at this one this afternoon

**Comment by JKGisMe** [comment]
Just ran into this problem when I thought I'd whip up a quick ember addon. 2 hours later I'm researching errors trying to reinstall npm not as root. I followed the linked guide's instructions for reinstalling node with brew but ran into more errors. I'll try the nvm way next but any chance there's an easier way?

**Comment by stefanpenner** [comment]
@JKGisMe nvm is good, don't install npm as sudo

**Comment by JKGisMe** [comment]
I got nvm and everything seemingly installed correctly and not as sudo. But now my project won't install dependencies correctly. Basically every single thing I've needed to do (relating to ember, node, bower, npm) since removing my old root npm & installing with nvm has errored <i>except</i> now I can successfully create an addon... I'm not sure the tradeoff was worth it.

**Comment by bianjp** [comment]
Met the problem. When will it be fixed?

Current workaround:
```shell
sudo ember addon [addon-name]
sudo chown -R [user:group] [addon-name/]
```

**Comment by JKGisMe** [comment]
4 months since I had this problem. The fix will happen whenever you fix your node/npm permissions.

Personally, I did this: http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x/11178106#11178106

Everything works great now and I forgot all about it ever since.

**Comment by catmeme** [comment]
For what it's worth, I experienced this issue using a docker container based on the node image.

**Comment by stefanpenner** [comment]
> Personally, I did this: http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x/11178106#11178106
