### ISSUE TITLE
Bamboo CI currently only supports nunit reporters, when will 'ember test' also support nunit?

### ISSUE THREAD

**Issue by rpupo** [ember-cli/ember-cli#2457]
Bamboo CI currently only supports nunit reporters, when will 'ember test' also support nunit?

**Comment by johndaley-me** [comment]
I am using the Bamboo JUnit Parser with Bamboo 5.8.1 and the "xunit" Testem reporter.

The Bamboo NUnit Parse does not work since the NUnit xml has a different schema.

**Comment by et** [comment]
@johndaley-me - JUnit not NUnit

**Comment by et** [comment]
@johndaley-me - NUnit should work since it's a subset of JUnit. More context of what error you're receiving would help.

**Comment by johndaley-me** [comment]
@et - It didn't work in my case but perhaps it does in others. The JUnit Parser is working well for me.

The NUnit schema http://www.nunit.org/docs/2.6.4/files/Results.xsd uses elements such as "test-case".

The JUnit schema https://github.com/karma-runner/karma-junit-reporter/blob/master/junit-schema.xsd matches what testem outputs with the "xunit" reporter and uses elements such as "testcase" (note that there's no "-").

The JUnit parser works but when I used the NUnit parser instead it fails with this output:

Starting task 'Parse client unit tests' of type 'com.atlassian.bamboo.plugin.dotnet:nunit'
simple 25-Aug-2015 14:27:47 Parsing test results under /home/bamboo/bamboo-agent-home/xml-data/build-dir/NCK-DRG-JOB1...
simple 25-Aug-2015 14:27:47 Failing task since test cases were expected but none were found.
simple 25-Aug-2015 14:27:47 Finished task 'Parse client unit tests' with result: Failed
