### ISSUE TITLE
Could not read config from meta tag with name

### ISSUE THREAD

**Issue by wayne-o** [ember-cli/ember-cli#2517]
I seem to be getting 

Could not read config from meta tag with name "sonatribe-ui/config/environment". 

http://test.sonatribe.co.uk:8080/

This worked recently until I wiped my env and rebuilt so now have the v. latest everything.

My previous environment was only about a month old if that helps.

What would be causing this?

**Comment by samueljseay** [comment]
Can I ask, is there a way to get around this requirement? 

I was using ember-cli-rails up till recently but had too many issues with it limiting our ability to update ember-cli dependencies. 

But now we build our app into a rails projects asset directory and it won't work because we somehow need to grab these meta tags? Is index.html the only way to properly build an ember-cli app?

**Comment by KrzysztofMadejski** [comment]
I wonder what is the need for `meta` tag? can't all this information be bundled into the script as initialization parameters?

**Comment by stefanpenner** [comment]
@KrzysztofMadejski that would not lead to reproducible builds, although it is an opt-in options for those that prefer it.
