### ISSUE TITLE
Document ember-browserify and using npm modules

### ISSUE THREAD

**Issue by jakecraige** [ember-cli/ember-cli#2590]
Since #2505 was merged we can now use ember-browserify to include npm deps and have them loaded via browserify with the ember-browserify addon. This is a big deal as it seriously simplifies a few dependency things so we should mention it. It was kind of hidden in the changelog by how it was worded.

I'm away from the computer for the weekend or I'd test his to make sure it's accurate, but I think that's right? Let me know if that's incorrect

**Comment by djackson-sykes** [comment]
Another +1 for putting it in the docs, especially since I had trouble getting ember-browserify to work correctly and its own documentation wasn't much help.

@jakecraige is right that dependency management in ember-cli is weird right now -- as someone relatively new to frontend development who has used CJS/Node but not AMD, it is absolutely *baffling*. If ember-browserify isn't going to become part of the docs, it'd be nice if they at least explained:

- How to figure out what file to import from a dependency (i.e., what a file with named AMD support looks like), since not everybody structures their project the same way
- How to identify the exports of a named AMD module and use them in the `exports` argument to `app.import`.
- What the limitations of the ES6 module transpiler are (in particular, lack of support for anonymous AMD).

I'd happily make a pull request for this... but unfortunately, I still don't understand the whole system well enough to document it.
