### ISSUE TITLE
CSP Issues

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#2672]
This issue exists to track problems with Content Security Policy.

 - [ ] It seems to be impossible to use `'self'` for websockets, because `'self'` implies same scheme, and `ws://` != `http://`.

**Comment by tp** [comment]
I see the initial `Content-Security-Policy-Report-Only` header containing `connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729`.

Wouldn't it suffice to add `ws://localhost:4000` (or whatever the dev server's port currently is), instead of the port 35729 entries?

(This currently breaks simple WS integration for me as well, had to hardcode the WS connection to port 35729 for testing)

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/issues/3350

**Comment by stefanpenner** [comment]
cc @jonathanKingston

**Comment by jonathanKingston** [comment]
CSP has nonces and hashes for exceptions for scripts. Not widely supported by all browsers unfortunately.

Yeah it abides to the SOP tuple of data as you say scheme dependent.

Yup I will look into this when I get chance to finalise my CSP JSON work which would allow application authors the ability to specify their own policy separate from Ember (Which would switch policy for dev / live)

I'll check our dev setup tomorrow as I don't think I made any changes to it and we have a custom web sockets port.

**Comment by stefanpenner** [comment]
Unfortunately this feature has been removed in #5247, it has been deemed doing more harm then good.

I was hopeful in the past year this situation would have improved, but unfortunately it has not. I will gladly restore it once the UX is up to par.
