### ISSUE TITLE
Docs: clarify default mocks namespacing

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli#2737]
I was talking to an Ember newbie today who got hung up for a bit on trying to get Ember Data talking to ember-cli mocks. I think the source of confusion was that the default mock for getting `Post` 1 is `/api/posts/1`, but Ember Data's default convention is `/posts/1`.

Is there are a way to make the out-of-the-box experience line up better? Or a place where we can at least explain this in the docs?

**Comment by maxmechanic** [comment]
Just ran into this issue. Morgan helped me see that the incorrect call was being made, but not where/how to fix it. I spent a moment digging for a config variable before adding a RESTAdapter with the correct namespace. 

My impulse is to expect the generator to scaffold mocks that would be compatible with the default configuration.

I could see this issue feeling more confusing because the default adapter is generated, so there's no obvious place to look through `app/` or `config/` and change the namespace.

**Comment by ef4** [comment]
I just helped another newbie who hit this same problem.

Is there a reason we can't just add an adapter to the http-mock blueprint? `ember g http-mock posts` could create `app/adapters/posts` with

```js
export default DS.RESTAdapter.extend({
  namespace: 'api'
});
```

**Comment by noslouch** [comment]
+1

**Comment by stefanpenner** [comment]
seems to have gone stale
