### ISSUE TITLE
install:addon command can find wrong default blueprint

### ISSUE THREAD

**Issue by slindberg** [ember-cli/ember-cli#2915]
When installing an addon that has a blueprint of the same name, it can potentially find another package's blueprint and invoke it. This is due to the search that [`findAddonByName` does in `lib/models/project.js`](https://github.com/ember-cli/ember-cli/blob/a8f62e22e8fb24919a7cb8448434388bf0245129/lib/models/project.js#L302-L304)

For example, with an addon called `ember-data-foo`, the `findAddonByName` function will find first `ember-data` and return it immediately, causing its default blueprint to be run instead.

Is there a naming convention that I've unwittingly broken? I've circumvented this for the time being specifying the `defaultBlueprint` option in `package.json`.

/cc @jakecraige

BTW, thanks for the awesome feature!

**Comment by jakecraige** [comment]
Thanks for reporting this. I'm trying to remember why I did `indexOf` rather than equality.. If I even had a reason

**Comment by slindberg** [comment]
Thanks!

**Comment by raycohen** [comment]
you can still run into this issue if `findAddonByName` is called with something other than an exact match to a project name as seen in https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/issues/6

**Comment by raycohen** [comment]
We could attempt to parse the package name out of the command line arguments.  However there's no reliable way to parse a tarball url (another valid npm install argument) and get the package name.

Since we're forcing `'save-dev': true`, perhaps reading the current project's package.json file before and after running the `NpmInstallTask` would give us a way to know exactly which packages were newly installed by the `ember install` command
