### ISSUE TITLE
Where to place custom functions to use in config/environment.js so ember:install or ember:init doesn't crash?

### ISSUE THREAD

**Issue by jcope2013** [ember-cli/ember-cli#3223]
here's a real example in my app today

```
// Add a "startsWith" function to Strings
if (typeof String.prototype.startsWith != 'function') {
  String.prototype.startsWith = function (str){
    return this.slice(0, str.length) == str;
  };
}

if (environment.startsWith('development'))  {
    ENV.host = 'http://localhost:3000';
}
```

this works fine when running ember serve and ember build and does what it correctly is supposed to do, it's used in a few different spots in the file for different environments also, but when installing an addon using ember:install or running ember init, I get this error

```
Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
```

 my current solution is to comment anywhere that uses startWith out, run the command, then uncomment them, I also tried bringing in lodash's startWith but I get ```_ is undefined``` so my question is where can I import functions to use in config.js or is that possible in today's current ember-cli?

**Comment by teddyzeenny** [comment]
The error means `environment` is undefined (not related to `startWith`). This is because commands that use blueprints (such as `ember init`) call the config method [without passing an environment](https://github.com/ember-cli/ember-cli/blob/60e0c6f38c798628ea062abbc6c806fc80e23d1e/lib/models/blueprint.js#L339).

You just need to make sure `environment` is a string. You can just write `environment = environment || 'development';` at the top of the method. I feel like we should actually be passing `development` to the config call in `models/blueprint`. Calling the method with an `undefined` environment seems strange.

As for using lodash you can do:
- `npm install lodash --save-dev`
- `var _ = require('lodash');` (inside `config/environment.js`)

**Comment by jcope2013** [comment]
@teddyzeenny thanks, that did the trick
