### ISSUE TITLE
podModulePrefix recommended format?

### ISSUE THREAD

**Issue by jbrown** [ember-cli/ember-cli#3254]
> The POD path should use the following format: `{appname}/{poddir}`.
> [Pod structure](http://www.ember-cli.com/#pod-structure)

So I follow along...

```javascript
var ENV = {
  podModulePrefix: 'my-app/pods'
}
```

```shell
$ ember g component blog-post --pod
version: 0.1.12-master-51e5933419
installing
  create app/pods/components/blog-post/component.js
  create app/pods/components/blog-post/template.hbs
installing
  create tests/unit/pods/components/blog-post/component-test.js
```

But if I don't follow that format and leave out the app name...

```javascript
var ENV = {
  podModulePrefix: 'pods'
}
```

```shell
$ ember g component blog-post --pod
version: 0.1.12-master-51e5933419
installing
  create app/pods/components/blog-post/component.js
  create app/pods/components/blog-post/template.hbs
installing
  create tests/unit/pods/components/blog-post/component-test.js
```
Same exact outcome.

What is the expected behavior from using that format?

**Comment by trabus** [comment]
This is because we don't need the app name for generating the pod: https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L697

We do however need it for the resolver, which is what it is primarily used for: https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/lib/core.js#L196

So it's definitely a quirk, but not a bug. :)
