### ISSUE TITLE
Getting addon assets (esp. images) into dist/assets

### ISSUE THREAD

**Issue by TeknoFiend** [ember-cli/ember-cli#3313]
The current setup puts anything from an addon's `public` directory into, eg, `dist/my-addon-name`. This is inconvenient when trying to reference images from the addon's CSS files. And completely breaks for ember-cli-rails and other home-grown solutions that only deploy the `assets` directory.

Is there a planned solution to getting files (at least images) into `dist/assets`? Perhaps by changing the location of the addon's public files or using `app/images` or perhaps `addon/images`?

Internally we are hoisting `dist/my-addon-name` to `dist/assets/my-addon-name` by monkey-patching Addon.prototype.treeForPublic. This is a pretty straightforward change that I can submit as a PR but I don't know the history of the decision for the current location.

```
Addon.prototype.treeForPublic = function(tree) {
  this._requireBuildPackages();

  if (!tree) {
    return tree;
  }

  return this.pickFiles(tree, {
    srcDir: '/',
    destDir: 'assets/' + this.moduleName()
  });
};
```

**Comment by rwjblue** [comment]
The default is to scope that output to `dist/my-addon-name`, but you can override `treeForPublic`, and place your files wherever you like in `dist/`.

**Comment by rwjblue** [comment]
(too fast on the button clicking, sorry)

**Comment by wsewell** [comment]
I figured the scoping was intentional but scoping within `assets` made more sense to me for whatever that's worth. I'm not sure I agree that ember-cli-rails is doing the wrong thing. It seems like anything that could be an asset should be in `assets`: CSS, images and (for historical reasons) JS.

Maybe pulling `public` files from the addon into `assets` doesn't make sense since they aren't necessarily "assets".  But maybe there's another choice that does make sense for images (eg `app/images` or `addon/images`).

**Comment by stefanpenner** [comment]
@rwjblue thoughts on maybe:

`my-cool-addon/public/` merged 1:1 with `my-cool-app/public` and `my-cool-addons/public/` get namespaced?

**Comment by rwjblue** [comment]
@stefanpenner - I do not want to make any more nested trees (`styles` and `templates` nested under `app/` for example), since they make much more work to strip them out during the build.  I would be ok with another root level dir for `addon-public` or something...

**Comment by stefanpenner** [comment]
treeForPublic in an addon enables this.

For future exploration, the new RFC process seems correct.
