### ISSUE TITLE
consider min-node version of 0.12.x

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3319]
@ember-cli/owners thoughts?

- [x] deprecate `0.10.x` https://github.com/ember-cli/ember-cli/pull/3326
- [ ] c-extensions that don't work yet?
  - [ ] node-sass ?

**Comment by trabus** [comment]
Are we talking as of ^0.2.1? I'm assuming this is primarily so we can start using more ES6 in ember-cli itself? 

I will need to have a conversation with our ops team to get 0.12 onto our build server, and I imagine that will be the case for a lot of slower moving companies. I imagine there are still lots of companies on 0.10.x out there.

Personally, I won't mind as long as we can get the 0.12 builds stop failing from timeouts on our slower tests.

**Comment by stefanpenner** [comment]
> I imagine there are still lots of companies on 0.10.x out there.

its trivial to change this...



> Are we talking as of ^0.2.1? I'm assuming this is primarily so we can start using more ES6 in ember-cli itself?

my main motivation is actually `execSync` being built in and no longer requiring a c-extension.

**Comment by trabus** [comment]
> its trivial to change this... is this honestly something ops people have trouble doing? Isn't this their job?
I'm sure it is, but getting anything done in a corporate setting will always be met with some pushback from somewhere.

**Comment by stefanpenner** [comment]
> I'm sure it is, but getting anything done in a corporate setting will always be met with some pushback from somewhere.

:cry:

**Comment by raytiley** [comment]
> its trivial to change this... is this honestly something ops people have trouble doing? Isn't this their job?

lol. Haven't been at yahoo long I guess. Unless it provides some huge win that can't be gained any other way it seems like a pretty stiff requirement. 

At my company the only reason anyone know any node, myself included is because of ember-cli.

**Comment by stefanpenner** [comment]
> Unless it provides some huge win that can't be gained any other way it seems like a pretty stiff requirement.

the `huge` win, is that ember-cli works.. :+1:

**Comment by trabus** [comment]
I honestly don't think that it's a huge issue to require it, it's only needed for the build server, and even then there are ways around needing different versions of node. I think I'm just trained to expect caution when asking to upgrade software. Where I've worked it has always been a slow cautious process due to upgrades and things breaking often being associated with each other. I imagine I'm not the only one with a (overly) cautious work culture.

Btw, I just spoke to our ops guy and he had no problem with it, I just need to make a ticket for it. :+1:

**Comment by stefanpenner** [comment]
> Btw, I just spoke to our ops guy and he had no problem with it, I just need to make a ticket for it.

:+1:

**Comment by rwjblue** [comment]
I'm kinda :-1: on changing the platform requirement less than a month after 0.12 is released, and just on the cusp of releasing 0.2.0.

I'd rather make this warn on  0.10 through however many versions of 0.2.x (which should give us some time to fix any issues with 0.12 and give folks time to get the proper infrastructure in place) and require 0.12 or io.js for 0.3.x.

**Comment by searls** [comment]
For what it's worth I agree with Robert. Most users I talk to are not following Node closely, are genuinely confused about 0.12/iojs, and would probably be better served by sticking with 0.10 a bit longer until the dust settles or the future becomes more clear.

**Comment by rwjblue** [comment]
> the huge win, is that ember-cli works

This seems like a somewhat flippant reply to a good question (aside: ember-cli has been working very well under 0.10).  It is not clear to me exactly what code we can remove/refactor of we move to 0.12.

**Comment by stefanpenner** [comment]
> It is not clear to me exactly what code we can remove/refactor of we move to 0.12.

We have much complexity, merely to avoid `execSync`, which only exists as a c extension for node  `0.10.x` but is available in node  `>= 0.11.x`. Additionally. `nextTick` in broken in node `0.10.x` which leads to dubious work-arounds in RSVP.

> give folks time to get the proper infrastructure in place

how much time?
What infrastructure?

> Most users I talk to are not following Node closely, are genuinely confused about 0.12/iojs,

If they choice either 0.12 or iojs they will be better off then they are today. But the suggestion is  we should wait until they two project merge or diverge before we transition to them?

**Comment by ef4** [comment]
People are saying crazy things in this thread.

Any place you are already free to *download and execute code from npm* you are equally free to *download and execute node*. It should not be any bigger deal to upgrade than an npm package.

node runs just fine from a user-specific location. You literally just download the tarball, unpack it, and place the resulting node & npm binaries in your path, and everything just works.

So the issue of needing to grovel with ops to get node upgraded sounds bonkers. Either they let you download and execute arbitrary code or they don't. If they don't, you can't even run npm in the first place. 

Therefore, every ember-cil user already has the power to install any node version they want. QED.

**Comment by chadhietala** [comment]
We script out the node and npm version currently so bumping this is not really an issue for us.  I'll probably just explain why it's better.  My concern would be if this has any potential side effects or in the addon ecosystem.  The last thing we want is android-esk fragmentation in addon land.

By the way it looks like node-sass is tested against 0.12.0 and it's green.

**Comment by searls** [comment]
I don't find the conservative ops argument compelling, least of all because it's a build tool and Node doesn't necessarily need to live on a production server. My comment on waiting for the smoke to clear on iojs/0.12 was focused solely on the end-user experience. I feel like a bit of an outsider here because my experience with ember-cli is as a user, not a maintainer, so that's who I'm empathizing with in this case. 

All I can say is that when I first installed ember-cli I was immediately greeted with bower conflicts that some users wouldn't have understood and given up on. Anything that makes that onboarding experience potentially more cumbersome (e.g. "you have Node installed but it's the wrong one" or "if you need this other node on your system too here's this concept of version managers and nvm") raises the barrier of entry. 

As a rubyist, figuring out nvm was a breeze because I'm familiar with the concept and I've used rvm/rbenv. But I worry that wouldn't be true of non-rubyist users. Even if nvm works great to solve this problem, it's still another thing some people will view as a burden to overcome. 

In the worst case, we might imagine a user with a project whose server-side is written in Node and only runs on either iojs or 0.10, but an ember-cli build telling them it must run on 0.12. In that case, a user might find that for a single repo, the server side has to run with one node distribution and the client side has to be built with another. That's a lot to keep straight. 

_In spite of all of that_, if the benefits discussed above (like native `execSync`) provide a huge immediate value to the project or if complications to the user experience could be minimized, maybe that's just the right move and it can't happen soon enough. I don't have enough data to know. That's just the balance to maintain as I see it.

**Comment by trabus** [comment]
I'm sorry if I'm being dense (maybe I'm missing something), but _I_ technically don't have control over which node is running on our Bamboo build server that runs `ember build -prod` and packages the dist in an RPM that gets deployed to our production servers. Honestly, they're not super comfortable with us pulling down packages from npm, but we're doing it for now. 

Regardless, it's a moot point for me now, but I do agree with the sentiment of waiting a little longer than a month after the release of 0.12.

**Comment by rwjblue** [comment]
@stefanpenner:

> We have much complexity, merely to avoid execSync, which only exists as a c extension for node 0.10.x but is available in node >= 0.11.x. 

I read this earlier, and I am still somewhat unsure what code (other than the internal testing `run-command.js` utility) that could be taken out with `execSync`.

> Additionally. nextTick in broken in node 0.10.x which leads to dubious work-arounds in RSVP.

Agreed.

> * How much time?
> * What infrastructure?
> * What makes up the above checklist so we are enabled to shed the legacy?

I suggested that we make 0.2.0 warn when not running on 0.12 or io.js to properly message to our end users that a change is coming, and that we remove the warning and require 0.12/io.js at 0.3.0.  The actual timeline is completely up to us (if we only have a couple versions in 0.2.x or if we have 15 is completely in our control).

@ef4:

> People are saying crazy things in this thread.

Perhaps, but I doubt that people just decided to chime in here out of insanity or laziness. 

---

The fact that folks can or cannot update to the latest version of Node is not really the issue here. This is about our commitment to be a stable base for folks that need/want to build Ember apps. A platform minimum version requirement change *must* be messaged properly, giving people warnings when they run on a "deprecated" platform and giving them the ability to squelch those deprecation notices by updating to our desired platform(s).

**Comment by stefanpenner** [comment]
Ok let's deprecate node 0.10 for the 0.2x series. With plans to drop entirely after. I am good with this

**Comment by Kuzirashi** [comment]
`node-sass` does work for me on nodejs v0.12.

**Comment by jakecraige** [comment]
Excuse my ignorance, but why is having the c extension for execSync bad?

**Comment by rwjblue** [comment]
> Ok let's deprecate node 0.10 for the 0.2x series. With plans to drop entirely after. I am good with this. 

Submitted PR to implement the warning.

**Comment by stefanpenner** [comment]
> Submitted PR to implement the warning.

awesome

**Comment by stefanpenner** [comment]
> Excuse my ignorance, but why is having the c extension for execSync bad?

Users without the correct build tools will be unable to install the module. Additionally, typically these native extensions depend on v8/libuv internals that are not supported. So upgrading node, also often requires the c-extension to be upgraded.

**Comment by rwjblue** [comment]
Closing this issue based on the warning added in https://github.com/ember-cli/ember-cli/pull/3326, I have created https://github.com/ember-cli/ember-cli/issues/3329 to track the removal in 0.3.0.
