### ISSUE TITLE
Registry ordering issue

### ISSUE THREAD

**Issue by rondale-sc** [ember-cli/ember-cli#3396]
@code0100fun and myself found a possible issue with the registry in EmberCLI not respecting the order defined in the package.json correctly.  The steps to reproduce are as follows:

1. pull down
  - [ember-cli-emblem-hbs-printer](https://github.com/rondale-sc/ember-cli-emblem-hbs-printer)
  - [ember-cli-emblem-test](https://github.com/hashrocketeer/ember-cli-emblem-test)
  - ember-cli
- `cd` into `ember-cli-emblem-hbs-printer` pull in branch named `handle_0.1.x_compat`
- npm install e'erything
- `npm link` both `ember-cli-emblem-hbs-printer` and `ember-cli` to `ember-cli-emblem-test`
- Finally, load the page.  

The test app should display the header "Winning"  but instead displays nothing.  

Things we've learned while trying to tackle this one.  

First, when we place a log the output from [registry.extensionsForType](https://github.com/ember-cli/ember-cli/blob/master/lib/models/registry.js#L35) we see that the `extensions` var is set out of order with `hbs` before `embl` and `emblem` (which shouldn't happen because of the before in the package.json)

Second, changing [registry.add](https://github.com/ember-cli/ember-cli/blob/master/lib/models/registry.js#L72) from `unshift` to `push` fixes the issue.  Which is what makes us think that this is a problem with the registry ordering. (though it'd be very unlikely for this to be the actual fix, it is just illustrative)

 It doesn't seem as if the DAG is being respected when you manually call add on the registry.

We also found that whenever we had access to `project` or `app` and could call `addons` we'd see that their order was correct despite the registry not being ordered correctly.

(we imported pluck from lodash

This is all from inside `registry.extensionsForType`  

![](http://i.imgur.com/utdZAhO.png) 

With `ember-cli-emblem-hbs-printer` occurring before `ember-cli-htmlbars`.

If I can be any help with finding a resolution just let me know.  Thanks!

**Comment by rwjblue** [comment]
Just chatted with @rondale-sc in irc about this a bit more, I believe this is a blocker for 0.2.0.  I also think that swapping `unshift` for `push` is possibly the correct solution but we need to make up some tests to really confirm.

Here is what is happening now:

So if I have two addons (Addon A and Addon B) that both add something to the project's registry:

* Addon A is setup to be loaded before Addon B
* Addon A is loaded and calls `registry.add` in its `setupPreProcessorRegistry` hook.
* Addon B is loaded and calls `registry.add` in its `setupPreProcessorRegistry` hook.

With the current system (using `unshift`) the items added to the registry in Addon B are processed before those in Addon A.

---

I believe that the following sums up the issue (and argues for changing back to `push` instead of `unshift`):

* Addon instantiation is guaranteed by way of the DAG.
* The final order of `registry.load` should be the same as the order of the addons added.

**Comment by rondale-sc** [comment]
Also, just confirmed that this is happening on [hbars](https://github.com/code0100fun/ember-cli-hbars) which is similiarly dependent on `ember-cli-htmlbars` being loaded after it.

**Comment by rondale-sc** [comment]
:+1:

**Comment by rondale-sc** [comment]
I think this may still be a problem.  Went back to update emblem and the above case still doesn't render as I'd expect.

**Comment by rwjblue** [comment]
@rondale-sc - Can you please `nombom` to confirm?

**Comment by rondale-sc** [comment]
Done.  Seeing:

![](http://i.imgur.com/uMy0LUU.png)

On this PR: https://github.com/201-created/ember-cli-emblem-hbs-printer/pull/3

with ` 0.2.0-beta.1-master-750596e268`

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/3464 should fix the issue mentioned in the last comment
