### ISSUE TITLE
Develop addon with broccoli-sass

### ISSUE THREAD

**Issue by Fed03** [ember-cli/ember-cli#3414]
Hi all, I'm using v0.1.15
I created a new addon and added broccoli-sass to it.
I tried with creating the following files:
- app/styles/app.scss 
- addon/styles/addon.scss

But the compiler throws error `ember-foo\tmp\tree_merger-tmp_dest_dir-64eMXcc2.tmp\app\styles\app.[scss|sass] does not exist`

then after creating `tests/app/styles/app.scss` and importing `@import('app/styles/app')`
```
{
  "status": 1,
  "file": "ember-foo/tmp/tree_merger-tmp_dest_dir-ATL7jQeC.tmp/app/styles/app.scss",
  "line": 1,
  "column": 1,
  "message": "@import directive requires a url or quoted path"
} [string exception]
```

I don't know if there is a way to manage custom assets in ember-cli addons

**Comment by lolmaus** [comment]
@Fed03, have a look at https://github.com/Blooie/ember-cli-notifications for a working example.

**Comment by rwwagner90** [comment]
@lolmaus I don't see how that example works. I looked in the Brocfile and index.js and I didn't see anything importing the scss anywhere.

**Comment by stefanpenner** [comment]
@lolmaus https://github.com/Blooie/ember-cli-notifications/blob/master/package.json#L25 shouldn't that be in dependencies?

**Comment by stefanpenner** [comment]
@rwwagner90 ember-cli should just correctly detect nested addons, 

> Hi all, I'm using v0.1.15

you need to use `> 0.2.0`

**Comment by rwwagner90** [comment]
The styles don't get copied over for me. I'm using less and not scss. I have an addon.less, just like they have an addon.scss, and my styles do not end up in vendor.css. I would also like to be able to make my addon depend on the ember-cli-bootstrap addon, rather than keeping the bootstrap code in my addon as well. Is there a way to do this?

**Comment by stefanpenner** [comment]
@rwwagner90 can you share the add-on?

@rwjblue r?

**Comment by rwwagner90** [comment]
I believe the issue here is ember-cli-less. It wants me to have tests/dummy/app/styles/app.less, which is not where I want it to be doing anything. I want either addon/styles/addon.less or app/styles/app.less to work. Do I need a different package? Perhaps one of the broccoli less ones? My addon code is here: https://github.com/rwwagner90/ember-x-editable-addon

**Comment by stefanpenner** [comment]
@rwwagner90 can you open a new descriptive issue, This issue is more related to broccoli-sass and has been fixed.

**Comment by rwwagner90** [comment]
Sure, new issue here: https://github.com/ember-cli/ember-cli/issues/3490
