### ISSUE TITLE
Handle Marked ReDoS Vulnerability

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli#3455]
We recently introduced [marked](https://github.com/chjj/marked) for better help documentation. A ReDoS vulnerability has been reported on this project and we should either fix marked or remove the dependency on it before releasing 0.2.0. 

/cc @trabus 

https://nodesecurity.io/advisories/marked_redos

**Comment by trabus** [comment]
Ugh, yeah, we should probably fix this. The likelyhood of someone hitting this vulnerability is very low, as the only thing implementing it currently is the model blueprint, but if people start dropping a bunch of garbage like [this](https://github.com/chjj/marked/issues/497) into their blueprint's `HELP.md` file, it would be an issue.

I've seen mention of using [markdown-it](https://github.com/markdown-it/markdown-it) as a safe replacement, so I'll look into what would need to be done to implement it instead. We're also using marked-terminal, which depends on marked, so it's not an easy swap.

I can't work on this until probably tomorrow, I've got a pretty full weekend. I'll research while I can though. :\

**Comment by trabus** [comment]
I think I can leverage markdown-it, and essentially convert marked-terminal to work with markdown-it. Reading up on the api, but it looks like it should be pretty straightforward. I'll post progress tomorrow.

**Comment by rwjblue** [comment]
@chadhietala - Thank you for reporting this!! 

We should absolutely fix, but I'm not sure that we should consider this a blocker for 0.2.0 since `marked` is only used in an already trusted context (after installing an addon).

**Comment by stefanpenner** [comment]
I don't believe this is a vector that posses any additional risI to ember-cli users.

For the attack to be exploited, one needs to install a malicious addon that introduces the malicious markdown content. In reality that add-on already can execute code on the hosts machine and the attacker may as well just write malicious js.

I would consider this an issue if: ember cli was used as the server for hosting these apps in prod and user provided content was consumed by this module. Hopefully the former isn't true but the later is absolutely true.

If someone can point out a reasonable vector I have missed. Please let me know.

**Comment by chadhietala** [comment]
__TL;DR__ Green badges are good.

There is no vector, however this is more of a marketing thing. If I tell some security person we're using Ember CLI and the first thing they do is go to github and see the David badge that says there are insecure dependencies then I have to explain why there is no vector.  It also says something about the integrity and maturity of the project.

**Comment by rwjblue** [comment]
@chadhietala - I completely agree, we **absolutely** should fix!! And it sounds like @trabus has a plan to get it taken care of.

At the moment our users are having major issues with installing all recent versions via NPM at the moment, and we need to release 0.2.0 to help resolve that.  Since there is no known vector, I do not want to block 0.2.0 on this.  But as soon as we can fix it, we should!

**Comment by stefanpenner** [comment]
Ya. We should also apply pressure upstream so others who are using this lib and actually are vulnerable to the attack vector are not left vulnerable.

I think it's important to consider usage and vector risk, or we will just get desensitized.

**Comment by trabus** [comment]
@stefanpenner @rwjblue @chadhietala The author of marked is aware of the issue, but I haven't seen any progress reported since December. The issue lies with [catastrophic backtracing](http://www.regular-expressions.info/catastrophic.html), which has some solutions, but I'm not sure if the author has tried implementing them yet. 

I've started looking down a path of using a different markdown parser that doesn't use regular expressions. Looking at markdown-it, and I think it will allow me to extend it in a way where we could add the custom color tokens to the addon, extracting the markdown-color code from ember-cli entirely.

**Comment by rwjblue** [comment]
@trabus - :heart:

**Comment by trabus** [comment]
I've got a rough pass [here](https://github.com/trabus/markdown-it-terminal), with header tags, lists, and bold working so far. I'll will be writing some more tests later today, and will just keep going down the list of token renderers. It takes a slightly different approach (token replacement, vs wrapping the content of matched token pairs), so I've had to do some things differently, but I think I can get the whole thing done by the end of the week.

**Comment by chadhietala** [comment]
@trabus :+1:

**Comment by trabus** [comment]
So I've got most of the basics done, but tables are going to be a bit tricky. I can probably get them figured out soon, but I'm not sure how much of a priority they'd be. Anyhow, I'll keep plugging away on the rest of the basics, and leave tables for last. I'm pretty close to having the core markdown support, I'll probably add color support before tables, since it's a more common use case for our project.

**Comment by rwjblue** [comment]
Makes sense.  I agree that tables are less of a concern, and am happy deferring that for later.

**Comment by stefanpenner** [comment]
@trabus you are a scholar and a gentleman.

**Comment by trabus** [comment]
I'm refactoring due to a recent release (yesterday) of a new version of markdown-it that I think may work a bit better for what I'm trying to do with the library. Will update once I've got my tests passing again.
