### ISSUE TITLE
Addon's addon dependency's included hook is never called

### ISSUE THREAD

**Issue by marcoow** [ember-cli/ember-cli#3531]
I have an addon (ember-cli-simple-auth-oauth2) that depends on another addon (ember-cli-simple-auth). While the dependency is correctly installed its `included` hook is never called and thus the modules it imports aren't available…

This might very well not be a bug and is probably related to the Addon updates in 0.2.0 but I can't figure out what's supposed to be changed in the addons in order to make dependencies like this work again.

**Comment by rwjblue** [comment]
The included hook of nested/child addons should be called. Can you throw up a demo repo that I could look at?

**Comment by marcoow** [comment]
simplabs/ember-cli-simple-auth-example works fine on the [master branch](https://github.com/simplabs/ember-cli-simple-auth-example) with ember-cli 0.1.15 but not with ember-cli 0.2.0 (https://github.com/simplabs/ember-cli-simple-auth-example/tree/ember-cli-020).

The project depends on [`ember-cli-simple-auth-oauth2`](https://github.com/simplabs/ember-cli-simple-auth-oauth2) as well as on [`ember-cli-simple-auth-testing`](https://github.com/simplabs/ember-cli-simple-auth-testing) which both in turn depend on [`ember-cli-simple-auth`](https://github.com/simplabs/ember-cli-simple-auth). Now there's a module missing in the [list of ember-cli-simple-auth's exports](https://github.com/simplabs/ember-cli-simple-auth/blob/master/index.js#L10) but regardless of whether I add that in `node_modules/ember-cli-simple-auth-oauth2/node_modules/ember-cli-simple-auth/index.js` or `node_modules/ember-cli-simple-auth-testing/node_modules/ember-cli-simple-auth/index.js` it's stil not available. Also a `console.log('test')` in either of these files is never executed. Of course the missing module is a bug of it's own I still don't get why the index.js files aren't executed.

**Comment by rwjblue** [comment]
Findings:

* Due to an error on my part when I added the `_super` system, [calling super here](https://github.com/simplabs/ember-cli-simple-auth-oauth2/blob/master/index.js#L5) is incorrect.  It should be `this._super.included.apply(this, arguments)`.  Fixing that enables the nested addon's `included` hooks to be called properly (which unlocks new levels of issues :wink: ).
* The `app` variable is **not** present in the second level addons.  So when they call `this.app.import` it throws an error because `this.app` is not defined [here](https://github.com/simplabs/ember-cli-simple-auth/blob/master/index.js#L9).
* If the `app.import` were to be made to work (by not calling `_super` in the top-level addons, invoking `included` manually on `ember-cli-simple-auth`, and passing the top level app down into its `included`) this test app would actually include `ember-cli-simple-auth`'s code twice.  This is because the contents of `app.import`s are not de-duped (they are stored based on source path which in this case are different).

Ideally, `app.import` should only be called from top-level addons (because nested addons will not and should not have access to the top level `app` instance). If `ember-cli-simple-auth` were structured as ES6 modules in its `addon/` tree the `app.import` would not be needed at all **AND** the presence of the duplicate `ember-cli-simple-auth` (or `ember-simple-auth`) modules would automatically de-dupe as part of the our build process.

**Comment by rwjblue** [comment]
> test app would actually include ember-cli-simple-auth's code twice

In retrospect, I think I was wrong here since both import from the flattened `bower_components` dir.

**Comment by marcoow** [comment]
I'll update the installation instructions for the extension libraries (ember-cli-simple-auth-oauth2, ember-cli-simple-auth-testing etc.) to include installation of the base library ember-cli-simple-auth as well.

Thanks for the great feedback!

**Comment by stefanpenner** [comment]
This seems to have gone stale, if someone has a reproduction on latest we can explore an revisit.
