### ISSUE TITLE
Ember.handlebars boundIf didn't call calculated property

### ISSUE THREAD

**Issue by vvs-code** [ember-cli/ember-cli#3591]
I try to migrate project form Ember cli 0.1.2 to 0.1.15. Current problem is next:

I have can-helper. It works fine at older ember but at newer version all can-blocks are absent. Can-helper use calculated property in model, so i try to set debugger into calculation function - it work on 0.1.2 and didn't work at 0.1.15

Original ember v 1.7.0-beta.1
Try to use 1.9.1

As i found that implementation of boundIf helper was changed. I can't found description for this changes. Possible that i should change my helper, but boundIf signature is the same, so i suppose it should work the same

Have anybody some ideas / experience with such trouble?

Thx in advance

**Comment by rwjblue** [comment]
`boundIf` was and has always been a private helper, and it has been removed (since it wasn't needed internally).

This is not really an issue with Ember CLI, and would likely serve you better as a stack overflow question.  Please cross-post to this issue when you do...

**Comment by vvs-code** [comment]
You're right - the question is about ember, not ember-cli
boundIf - public helper http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#method_boundIf

And yep - when i find answer i'll post link here. Thanks

**Comment by rwjblue** [comment]
It definitely has been private at least since 1.0.0:

* 1.0.0 - https://github.com/emberjs/ember.js/blob/v1.0.0/packages/ember-handlebars/lib/helpers/binding.js#L202
* 1.1.3 - https://github.com/emberjs/ember.js/blob/v1.1.3/packages/ember-handlebars/lib/helpers/binding.js#L218
* 1.2.0 - https://github.com/emberjs/ember.js/blob/v1.2.0/packages/ember-handlebars/lib/helpers/binding.js#L233
* 1.3.0 -  https://github.com/emberjs/ember.js/blob/v1.3.0/packages/ember-handlebars/lib/helpers/binding.js#L238
* 1.4.0 - https://github.com/emberjs/ember.js/blob/v1.4.0/packages/ember-handlebars/lib/helpers/binding.js#L258
* 1.5.0 - https://github.com/emberjs/ember.js/blob/v1.5.0/packages/ember-handlebars/lib/helpers/binding.js#L258
* 1.6.0 - https://github.com/emberjs/ember.js/blob/v1.6.0/packages_es6/ember-handlebars/lib/helpers/binding.js#L344
* 1.7.0 - https://github.com/emberjs/ember.js/blob/v1.7.0/packages/ember-handlebars/lib/helpers/binding.js#L363
* 1.8.0 - https://github.com/emberjs/ember.js/blob/v1.8.0/packages/ember-handlebars/lib/helpers/binding.js#L362
* 1.9.0 - https://github.com/emberjs/ember.js/blob/v1.9.0/packages/ember-handlebars/lib/helpers/if_unless.js#L37
* 1.10.0 - https://github.com/emberjs/ember.js/blob/v1.10.0/packages/ember-htmlbars/lib/helpers/if_unless.js#L41
* 1.11.0 - Removed.

**Comment by vvs-code** [comment]
What then i can use  to create a conditional that re-evaluates?

**Comment by rwjblue** [comment]
A standard `{{if}}` recomputes and is the suggested way to do this...

**Comment by vvs-code** [comment]
More information here https://github.com/emberjs/ember.js/issues/10692
