### ISSUE TITLE
Importing component pod requires additional (undocumented) path

### ISSUE THREAD

**Issue by oskarols** [ember-cli/ember-cli#3607]
I have a component defined in a Ember CLI app as such: ```/app/components/foo-bar/component.js``` (created using component blueprint).

Trying to re-use and extend the component from another component, importing using the following does not work: 

```javascript
import FooBarComponent from 'app/components/foo-bar';
```

Instead, the path that is required is the following: 
```javascript
import FooBarComponent from 'app/components/foo-bar/component';
```

Looking at ```required._eak_seen``` it seems the components and its template is exported to a a pod-specific path.

I'd suggest the former is the most intuitive, as I don't see how distinguishing between pod and non-pod components would be beneficial.

**Comment by rwjblue** [comment]
The second path (the correct one) is actually the path on disk, how is that not the most intuitive?

**Comment by trabus** [comment]
@oskarols For extending a component to work, it seems that you need to ensure there is no template in the component folder that is extending. That part may actually be a bug. I have an [example repo here](https://github.com/trabus/extend-component), this is the resulting page:
![result](https://cldup.com/YPrV_0-rVx-2000x2000.png)

**Comment by stefanpenner** [comment]
> The second path (the correct one) is actually the path on disk, how is that not the most intuitive?

i think that is because

`app/components/foo-bar.js` is a valid component, but can be expanded to `app/components/foo-bar/component.js` 

We could do something automatic here, but the resolver typically handles this. Unfortunately for inheritance we need a concrete reference at design time, which doesn't go through the resolver..

It could, but this needs further thought/exploration.

**Comment by funtusov** [comment]
I found this thread while also cracking my head as to why ``import ... from "app/components/foo-bar" wasn't working, so I'd weight in on the fact that it's intuitive. 

A pod component folder by convention contains component.js and template.hbs, so it seemed probable that the import would know about the correct thing to import. We came to expect a lot from the ember cli resolver, I guess :)

**Comment by stefanpenner** [comment]
@rwjblue this should be taken into account with your pod work

**Comment by stefanpenner** [comment]
@dgeb / @rwjblue is this something we are handling in the new modules work?

**Comment by dgeb** [comment]
@stefanpenner There's a [section in the module unification RFC](https://github.com/dgeb/rfcs/blob/module-unification/text/0000-module-unification.md#es-modules) that describes ES module imports, including an example in which a component is imported into another component:

------------------

ES module paths will be formed from a project's package name followed by a
direct mapping of file paths from the project root. The file's final extension
(e.g. `js` or `hbs`) will be excluded because all ES modules will of course be
compiled into JavaScript from their original format.

For example, the file `src/ui/components/date-picker.js` in the
`my-calendar` app will be exported with the module path
`my-calendar/src/ui/components/date-picker`.

Within any package, you'll be able to access the package's root with `$root`
and the project's `src` dir with `$src`.

These aliases will make the following module paths equivalent:

* `my-calendar/src/ui/components/date-picker`
* `$root/src/ui/components/date-picker`
* `$src/ui/components/date-picker`

Let's say that you want to create a new component, `date-time-picker`, which is
based on `date-picker`. You'll be able to import the base component from any of
the paths above. For example:

```
import DatePicker from '$src/ui/components/date-picker';
```

> Note: The above example could also use a relative path, like
`'./date-picker'`, which would be appropriate if the extended
`date-time-picker` is located close to the base `date-picker`.

**Comment by stefanpenner** [comment]
@dgeb thanks, so it seems like the modules RFC improves this.

---

The pods are more or less frozen, as they will be replaced by the modules proposal when it lands. This issue will most likely not be addressed.
