### ISSUE TITLE
blueprint generation should take into account .editorconfig

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3664]

**Comment by stefanpenner** [comment]
@trabus is this structure related, or ...

**Comment by trabus** [comment]
No, I'd say it's more blueprint related. AST transform after generating, most likely.

**Comment by stefanpenner** [comment]
> AST transform after generating, most likely.

ah, yes. Good call.

**Comment by trabus** [comment]
cc @abuiles

**Comment by efx** [comment]
+1
 Right now, generate blueprints seems to default to space based indentation while I am working in a project that requires tab based indentation. Using the .editorconfig would fix this problem quite cleanly.

**Comment by stefanpenner** [comment]
> Using the .editorconfig would fix this problem quite cleanly.

yes correct, it may also be easily supported if we added post generation transforms.

**Comment by efx** [comment]
how do 'post generation transforms' differ from the 'afterInstall' hook ?
I'm guessing the transforms would be easier to implement.

**Comment by stefanpenner** [comment]
because we want this to run during the templating phase of any blueprint based generation.

**Comment by vforge** [comment]
+1 for this

**Comment by huntie** [comment]
+1 Would love to see this

**Comment by ctcpip** [comment]
+1

**Comment by stefanpenner** [comment]
I'll try to work on an RFC for this

**Comment by ro0gr** [comment]
Just an idea. 
Also it would be great also to take into account eslint fix.
Looks like eslint has a [programmatic api](https://github.com/eslint/eslint/blob/master/lib/util/source-code-fixer.js) for that.

**Comment by nathanhammond** [comment]
Note: this is incredibly low priority for us on the CLI team. In order for anything to come of this it _must_ have a champion. Further, since we originally wrote the config and blueprints they represent the style we use. 😜

We're in no way opposed to make this happen, but we'll likely only partner with somebody in the community who cares deeply. (Tabs vs. Spaces debate can begin anew.)

**Comment by oskarrough** [comment]
@nathanhammond thanks for clarifying. I'd love to help out with this but unfortunately I'm not sure where to start. If someone has time to team up on this, let me know.

**Comment by j127** [comment]
Specifying the indentation via a `.editorconfig` file is a great idea for a standard feature in code generators in general. Code styles are personal things that should be left up to the programmers, not frameworks. Not having this feature in a framework that uses a code generator as part of the standard workflow adds a lot of hassle, because the generated code may not be compatible with the rest of the project out of the box.

I think that Sublime Text 3 achieves their various indentation levels when using snippets by creating the snippets with `tab` characters. The editor then replaces the `\t` characters with whatever indentation the settings file dictates. It doesn't seem like it would be very difficult to do: change the templates to use `\t` for indentation, and then replace each `\t` with two spaces by default, but override the default if a `.editorconfig` file is found and the indentation for JS is something other than two spaces.

**Comment by rwjblue** [comment]
@j127 as mentioned above by @nathanhammond and @stefanpenner, I think we are generally all in favor of honoring the editorconfig when generating files, someone just has to do the work. 😺

**Comment by j127** [comment]
It looked like the discussion had stalled for months, so I was voicing support and continuing the brainstorm. I have similar problems with vue-cli, so I think that this idea has potential as a standard feature on code-generating tools.

Is there is something like `.eslint --fix` that could format the generated files according to each user's detailed preferences? That would also help address problems with generated code like in these examples, in addition to indentation:

``` javascript
function () {
    // code
}

// vs.

function() {
    // code
}

// vs.

function(){
    // code
}
```

**Comment by ro0gr** [comment]
I believe this can be closed now, since https://github.com/ember-cli/ember-cli/pull/9469 has been merged!

**Comment by rwjblue** [comment]
Thanks @ro0gr!
