### ISSUE TITLE
Docker + ember-cli applications in Development

### ISSUE THREAD

**Issue by jakehow** [ember-cli/ember-cli#3679]
See previous discussion -> http://discuss.emberjs.com/t/working-with-docker-ember-cli-in-development/7658

I am not sure there is any issue that ember-cli can address per-se or that ember-cli-todos necessarily wants to include docker setup instructions, but you can see my example [here](https://github.com/ember-cli/ember-cli-todos/compare/ember-cli:master...jakehow:docker-development-support), which I can easily PR if desired.

Getting the ember-cli developer environment to run in a container is a challenge, mostly due to a synergy of conflicting issues between docker and node dependencies.  While playing with the ember-cli-todos I figured out an interesting work around to the biggest of them which is volume behavior.

Normally when developing an app locally in a docker container, we would mount the entire application's source tree in the container so that any files we change during development can be reflected in the vm we are testing with immediately.

Because `node_modules` and `bower_components` are within the project's path this is not feasible for ember-cli applications.  If you do your npm install steps before copying your source into the container and mounting the volume, the folders with the dependencies are simply removed because of how docker volume mounting works.

The solution in the code linked above is that we create specific volumes which exclude the root path of the project where `node_modules` and `bower_components` live.  We expect that nearly all change a developer needs to deal with is happening in `app/`, `config/`, `public/` and `test/` and create these as standalone volumes.  The developer can now work on their host machine and changes are reflected in the container.

Performance for builds and rebuilds of ember-cli-todos seem fine to me but I will test this strategy on some other projects to see if any issues arise.

There are might be other ways to resolve this but I could not get any of the other things I tried to work.  Previously I was focused on moving `node_modules` out of the project directory to somewhere like `$HOME`, but ember-cli does not seem to use this in the load path, and I don't know if that is still supposed to work in node.

**Comment by stefanpenner** [comment]
Are you proposing a community maintained docker image?

**Comment by jakehow** [comment]
@stefanpenner either that, or I can put together a guide using ember-cli-todos as an example and easy way to keep the guide up to date, so that developers have something they can reference when they want to put together a docker setup for their apps.

The current big pain here that I am looking to overcome is described more concisely in #3735

**Comment by WooDzu** [comment]
>  We expect that nearly all change a developer needs to deal with is happening in app/, config/, public/ and test/ and create these as standalone volumes.

@jakehow This seems to be reasonable approach to bundle into docker-compose.yml while keeping rest of the ember-cli stuff in docker image. What are your concers about this?

**Comment by jakehow** [comment]
@WooDzu this is potentially OK to duct-tape a temporary solution with but I think we should try to resolve the underlying issues in ember-cli to be more friendly in this environment.

* volumes are a little confusing to explain as is, once you start throwing caveats in to how they work with an environment it becomes much harder to communicate
* with this solution you are still sacrificing usability, if you want to flip a setting back and forth in `.ember-cli` for example then you need to rebuild the image.

FWIW I think the symlink at runtime hack is a better temporary solution than cherrypicking which folders you are going to mount as volumes.

**Comment by stefanpenner** [comment]
@jakehow i'll try to carve out some time soon to play with your docker examples, and try and get a grip on what sucks/works/doesn't I am sure i will be able to provide better feedback at that point in time.

I suspect i am missing some aspects of the workflow

**Comment by WooDzu** [comment]
> FWIW I think the symlink at runtime hack is a better temporary solution than cherrypicking which folders you are going to mount as volumes.

I noticed docker it pretty much like ember in terms of conventions. One can either work with it to do it the ember/docker way or fight against it which will cost a lot of frustration and issues during updating. Either way there is also alternative approach which might suit your needs:

* Build a data-only container which exposes 2 volumes with -v flag eg. `-v /bower_components -v /npm_modules` notice these are not available to host machine.
* Build ember-cli runtime container which mounts the above shared volumes using `--volumes-from data-container`. This will mount the shared dependencies at given locations.

There might be more approaches which I'm not aware of but would love to get to know any alternatives that can be proved to work.

**Comment by stefanpenner** [comment]
cc @burke would love your advice on this. I'll make myself free sometime this weekend/early next week if you have time to share your docker wisdom.

**Comment by burke** [comment]
As far as the `Dockerfile` in the PR goes:

* Why a ruby image? Why not just `ubuntu:14.04` or somesuch?
* Compress the npm, bower, and ember-cli installations into a single `RUN`.
* Cleaning up after `apt` has no effect on the total image size unless you do it in the same `RUN` as all of your `apt` stuff.
* Move the `ADD bower.json` below the `npm install` to benefit a bit more from caching.
* Node and bower both support envvars to specify the directory to use. You could just set these two early on in the `Dockerfile`, and not have to worry about mounting specific subpaths or juggling the artifacts on lines 29-30.

```Dockerfile
ENV NODE_PATH /opt/deps/node_modules
ENV bower_directory /opt/deps/bower_components
```

* Once you've done that, no more need to `ADD .`
* Don't set the `WORKDIR` for temporary stuff, just prefix a `cd /tmp` to each line that needs it.
* Instead of `CMD ["ember", "server", "--watcher=polling"]`, do `ENTRYPOINT ["ember"]` and `CMD ["server", "--watcher=polling"]`.

---

All that said, I'm not really sure I see the value in ember explicitly endorsing this practice. It's easier to set up `npm`, `node`, and `bower` than it is to set up `docker` and `boot2docker` (I say this as someone that's worked full-time with docker for almost 2 year and harbours a lot of resentment for the javascript ecosystem). 

If this actually solves a problem, it's indicative of a workflow problem that ember should be solving or encouraging the community to solve. As a not-javascript developer, there are two things I see here that *might* be the pain point this is targeted at:

1. Installing `node`, `npm`, `bower`, and `ember-cli` on OS X. Should this be made easier?
2. Running `npm` and `bower` only when their respective `json` files change. Are they slow to run on an up-to-date cache? You could fix upstream or have them stash away a hashsum of the `.json` file on the latest successful run and return early if matches.

The other thing is maybe it's just fun to play with docker and people feel like they need to get on board the bandwagon? I understand that, but I don't think it's appropriate to suggest this complexity to people that don't specifically seek it, because it is definitely (IMO) more complex that what exists currently.

**Comment by jakehow** [comment]
@burke thanks for the suggestions, our app has a little rack layer so that is why I am using the ruby image. Originally this was just a POC to make sure nothing specific about my env was not the issue.

> Node and bower both support envvars to specify the directory to use. You could just set these two early on in the Dockerfile, and not have to worry about mounting specific subpaths or juggling the artifacts on lines 29-30.
> ```
ENV NODE_PATH /opt/deps/node_modules
ENV bower_directory /opt/deps/bower_components
```
This is not currently possible with the current inner workings of ember-cli (node and bower paths are not respected as they are hardcoded to be within the project structure in the ember-cli codebase). This is the core issue which I made this POC to explain, see #3735.

**Comment by burke** [comment]
Oh, then yeah, I agree it's pretty much always a good idea to allow those paths to be overridden with an envvar. Prefixing with "EMBER_" seems sane to me. Silly bower using lowercase like they think they know how to computer.

**Comment by erichonkanen** [comment]
+1 ran into this issue of how to work with ember-cli in development inside a docker container.. updated my dockerfile/compose.yml to match the PR at top and it seems to have resolved the issue.. maybe add some notes about this to the ember-cli docs? seems like with dockers popularity it could be useful for people... vagrant info is there already

**Comment by stefanpenner** [comment]
i believe the relevant PR has been merged, we should be good to go (i believe) Let me know if i missed something

**Comment by jakehow** [comment]
@stefanpenner going to try and play with this today.

I am not sure if there was a specific PR for this, but here is an issue linking to downstream PRs https://github.com/ember-cli/ember-cli/issues/4562

I these all need to be merged for this to work?

**Comment by stefanpenner** [comment]
ya, all the broccoli usages need to be upgrade to the new plugin

**Comment by erichonkanen** [comment]
will it be possible in the future to not have to rebuild my machine when I update npm/bower dependencies? I followed the path above and mount app/, config/, public/, and tests/ separate and it works fine but the only hangup is its a pain to rebuild everytime I change a dependency

**Comment by jakehow** [comment]
@erichonkanen this is a tradeoff choice you'll need to make depending on what you are trying to do. You could definitely mount your dependencies from another volume or install them on run.

**Comment by erichonkanen** [comment]
definitely.. the issue with installing them at run is it seemed to be extremely slow.. right now we are only using docker for development of microservice project where ember is the client service

**Comment by stefanpenner** [comment]
I really have doubts dockers provides value here, there my be perceived value. But the sum total appears quite negative.

That being said, we will continue to make improvements, and try to enable those that go down this path when possible.

**Comment by erichonkanen** [comment]
@stefanpenner yeah it is almost more trouble than it's worth except the goal was to set up a consistent local dev environment where all 5 services + client are all spun up together and can communicate etc... we added the ember-cli container so that anyone that isn't working on client can still spin up the whole project etc.. not going this route into staging/production though.

that said docker-compose makes things nice/easy to orchestrate in theory but it's been one roadblock after the other as well
