### ISSUE TITLE
Update docs to change `ember install:addon` to `ember install`

### ISSUE THREAD

**Issue by searls** [ember-cli/ember-cli#3855]
It sounds like the `ember install:addon` command has been deprecated in favor of just saying `ember install`, this should be updated in the docs.

Mentioned in #3850

**Comment by visualjeff** [comment]
I noticed this too.  In my case I'm attempting to development my addon locally using npm link and I'm running into this issues where addon's are being removed from node_modules when running an ember build.

> npm link <addon name>
> npm install
> ember build <== Here is where addon disappears.  

build dies because it can't find addon index.js file in addon module.  Somehow it has the path.  But the addon has disappeared form node_modules.

I'm using version 0.2.3 of the ember-cli.

**Comment by visualjeff** [comment]
I should open my own issue.

**Comment by clekstro** [comment]
Can this be closed now?  The documentation PR was already merged.

**Comment by searls** [comment]
I don't see why not.
