### ISSUE TITLE
`ember serve` fails for all non-index routes with 'config' directory moved to 'ember-config'

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#3904]
When you move the config directory `ember serve` no longer allows you to directly navigate to a route.

Reproduction:
```bash
ember new testing
cd testing
mv config ember-config
vim Brocfile.js # var app = new EmberApp({ configPath: 'ember-config/environment' });
ember g route asdf
ember serve
curl http://localhost:4200/asdf
# "Cannot GET /asdf"
```

**Comment by nathanhammond** [comment]
Okay, so it's failing in [Project#configPath](https://github.com/ember-cli/ember-cli/blob/18d377b264859548f41aba6c3ea2015b90978068/lib/models/project.js#L127) ... `'config'` is being hardcoded as the directory path which results in trickle-down failure.

I'm not familiar enough with this portion of ember-cli to know how to fix it correctly, but this should now be relatively easy for somebody more familiar to knock out. :)

**Comment by rwjblue** [comment]
You can override without changes to ember-cli by adding:

```javascript
"ember-addon": {
  "configPath": "some-other-path"
}
```

**Comment by chadhietala** [comment]
@rwjblue Confirm. While this fixes the issue this feels weird. I don't remember who was working on the config story, but they should be aware of this.  Closing as it should unblock @nathanhammond.

**Comment by jameshoward** [comment]
Just to help anyone else who ends up here after the same journey I've been on…

Setting `EmberApp`'s `configPath` in `ember-cli-build.js` will work for `ember build` but not `ember serve` because the serve command uses `Project.config` before it is overridden in `EmberApp` to return the version in options.

The solution about works but doesn't make as much sense to be in `package.json` rather than a config option to `EmberApp`.
