### ISSUE TITLE
"intermediate value" error with computed properties - Addons only

### ISSUE THREAD

**Issue by brancusi** [ember-cli/ember-cli#3928]
Just upgraded from 0.2.0 ~> 0.2.3 and I'm getting this error.

Steps to reproduce:

1. ```> ember addon myaddon```
2. ```> create application.js in tests/dummy/app/routes``` 
```js
// /tests/dummy/app/route/application.js
import Ember from 'ember';

export default Ember.Route.extend({

  testProp: function(){
    return 'yes';
  }.property(),

  model:function(){
    console.log(this.get('testProp'));
  }
});
```
3. ```> ember s```

4. In browser throws error: ```Uncaught TypeError: (intermediate value).property is not a function```

If instead we use: 
```js
testProp: Ember.computed(()=> 'test')
```
...it works?!

This is only with addons. Everything works as expected with a regular ember new/init app.
Also, just showing this in the dummy app, but the actual addon is throwing this error from any file using the computed prop syntax:

```js
function(){
...
}.property()
```
What am I doing wrong?

**Comment by rwjblue** [comment]
Prototypes are not extended by default in addons.  This is because the application that the addon may be included in could need to disable prototype extensions.  The safest way (and the default way) to develop an addon is to avoid using prototype extensions.

See:

* Item 2) -> http://reefpoints.dockyard.com/2015/03/22/tips-for-writing-ember-addons.html.
* http://guides.emberjs.com/v1.11.0/configuring-ember/disabling-prototype-extensions/

**Comment by stefanpenner** [comment]
> Uncaught TypeError: (intermediate value).property is not a function

this is a crappy chrome error message.

**Comment by stefanpenner** [comment]
[reported](https://code.google.com/p/chromium/issues/detail?id=259443#c14)

**Comment by brancusi** [comment]
Thank you!
