### ISSUE TITLE
Exclude folders from builds in Brocfile

### ISSUE THREAD

**Issue by WooDzu** [ember-cli/ember-cli#4232]
Hi all,

There seems to be no way to exclude a folder from a build in a Brocfile (or any other place).
The use case is packaging, where I have an app made of sub-apps within pods. eg.
>  /app/modules/components
>  /app/modules/app1
>  /app/modules/app2
>  /app/modules/app3

I'd like to build them all when environment is set to 'development' or only eg. 'app1' when environment is 'app1'. Any suggestions?

**Comment by jrobeson** [comment]
for the Brocfile part, read the broccoli-funnel section http://www.ember-cli.com/#asset-compilation

**Comment by stefanpenner** [comment]
This is a great question for stackoverflow

**Comment by WooDzu** [comment]
I posted on both [StackOverflow](http://stackoverflow.com/questions/30686368/exclude-folders-from-builds-in-brocfile) and the [forum](http://discuss.emberjs.com/t/exclude-pods-from-builds-in-brocfile/8127) without any luck. Also tried different combinations of broccoli-file-remover, broccoli-funnel and broccoli-merge-trees to no avail.

```js
// Brocfile.js
var removeFile = require('broccoli-file-remover');

module.exports = removeFile(app.toTree(), {
    paths: ['app/modules/pod1/', 'app/modules/pod2/']
});
```
Is there anything else I could try?

**Comment by stefanpenner** [comment]
i responded.

**Comment by olivierlesnicki** [comment]
Why can't we have these questions answered on Github? Instead of stack-overflow. Having to jump between emberjs.com, github, stack overflow and the forum to find the solution to a question is painful. Happened to me yesterday when trying to figure out why `.volatile()` properties weren't triggering observers. Additionally the Ember.js community has the burden that the core code for ember-cli is spread across a large amount of micro services (broccoli and all its addons, ember-qunit, etc...).

Having used backbone, angular and react in the past ember is my favorite framework and I will continue to use it anyway. Community is amazing, core team is super approchable (and damn effective!), ember-cli is the best cli tool ever (just after npm). But to lower barrier to entry we need to make it more easily for people to ask questions and find answers - either by dramatically consolidating the documentation available on emberjs.com or reducing the amount of websites and repositories where users need to chase answers from.

@stefanpenner this query definitely doesn't sit here, and it's part of my point. Feel free to delete this comment once acknowledged.

**Comment by stefanpenner** [comment]
> Why can't we have these questions answered on Github? Instead of stack-overflow.

because stack-overflow has a very good UX for Q/A. It can be moderated in ways to adjust as the system matures and problems phase out. In addition, it is a platform optimized for finding and searching for questions, we should embrace it.

The issue tracker is better suited for bug reports -> solutions flow.
