### ISSUE TITLE
`--pod` doing the opposite of `usePods` setting is confusing

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#4330]
I find the [following behavior of Ember CLI](http://www.ember-cli.com/#pods) unexpected and confusing:
> If you would like to use the pods structure as the default for your project, you can set `usePods` in your `.ember-cli` config file to `true` ... When `usePods` is `true`, the `--pod` flag is essentially inverted.

The issue is that one is unable to tell from the command line whether a generator will use pods or not, despite a flag being explicitly added. That is, typing
```bash
$ ember generate route foo --pod    # may or may not use pods
```
May create the Foo Route in pod structure, or it may not, depending on the value of `usePods`. 

I feel it would be more clear if instead `--pod` guaranteed the pod structure, and another flag (*e.g.*, `--no-pod`) would guarantee traditional structure. The absence of either flag would use the setting as defined in `.ember-cli`.
```bash
$ ember generate route foo          # uses setting in .ember-cli
$ ember generate route foo --pod    # uses pods
$ ember generate route foo --no-pod # does not use pods
```

**Comment by david-duncan** [comment]
> The issue is that one is unable to tell from the command line whether a generator will use pods or not, despite a flag being explicitly added

You can always use dry run to eliminate any ambiguity.. I think it's a good practice in general to use it.

`ember g route foo --dry-run`

**Comment by SaladFork** [comment]
@david-duncan Thanks, I should probably be using dry run more often.

I can also use `cat .ember-cli` to check, but the point is that it is confusing that `--pod` can mean "don't use pod" sometimes.

**Comment by stefanpenner** [comment]
cc @trabus

**Comment by trabus** [comment]
@SaladFork I absolutely agree that it's confusing. There was some discussion about it [here](https://github.com/ember-cli/ember-cli/issues/2652#issuecomment-72324207) a while back, but there wasn't really a resolution for it.

[Structures](https://github.com/ember-cli/rfcs/pull/5) would probably help make a less confusing option easier to implement, but I probably won't be able to implement them until late July. 

However, there have been some improvements to the command options since it was last discussed, and we can look at adding some shorthands that will make more sense, instead of just inverting the value of the `--pod` option.

We could also be a bit more explicit about what structure your blueprint is being generated in, but we'll need to come to consensus on official terminology for what to call each type of structure (maybe we can add a GLOSSARY.md to catalog terms, I think it would be especially helpful for ESL people). I had proposed "basic" or "classic" for the original default type structure, but neither were officially picked up.

**Comment by locks** [comment]
Someone just got bit by this on IRC. Suggested resolution: `--pod` overrides `.ember-cli` instead of flipping it? ;P

**Comment by pjoe** [comment]
Someone = me .. so +1

**Comment by trabus** [comment]
Working on a PR for it now. I'm going to add a `--classic`  flag that will fill the role instead of inverting the value.
