### ISSUE TITLE
`ember build --environment production` hangs

### ISSUE THREAD

**Issue by al3x-edge** [ember-cli/ember-cli#4352]
Possibly related to #4004 and #4145.

@mihaiscurtucb notes it takes about 10 minutes on a decent machine and it completes in about 15 on mine.

Currently we are using LESS as well in that project, but I don't believe we have any really large files but have Intl polyfill clocking in at 1MB.

Debug gist with time: https://gist.github.com/al3x-edge/ff35696b5ac535853e07

Dropbox with time profiling / perf map file:
https://www.dropbox.com/sh/gih7edh4ub9idur/AAC_q76xIALzld1IT4a14V7Wa?dl=0

I'll be following the steps in #4004 shortly to determine if it's still something related LESS.

Project Packages

```
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-autoprefixer": "^0.4.1",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-divshot": "^0.1.7",
    "ember-cli-document-title": "0.1.0",
    "ember-cli-flash": "1.1.0",
    "ember-cli-font-awesome": "0.0.9",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-less": "^1.3.3",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-selectize": "0.3.1",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "ember-inputmask": "0.1.4",
    "ember-intl": "yahoo/ember-intl#2.0",
    "ember-truth-helpers": "0.0.4",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "liquid-fire": "0.19.2"
```

**Comment by stefanpenner** [comment]
thanks for the examples. I'll try to get it running this weekend and see what is up.

**Comment by stefanpenner** [comment]
I think what happens easily is the uglify or similar blow the reasonable memory constraint, and everything slows to a horrible crawl.

Splitting into multiple files helped in the past.

**Comment by al3x-edge** [comment]
@stefanpenner Send your email to alexander.r.ambrose@gmail.com if you need access to the repository itself =]

**Comment by stefanpenner** [comment]
stefan.penner@gmail.com

**Comment by al3x-edge** [comment]
@stefanpenner Added -- Thanks for taking a look. Appreciate it.

**Comment by stefanpenner** [comment]
thanks. I plan to look into this this weekend.

**Comment by al3x-edge** [comment]
@stefanpenner Did you get a chance to take a look at this? I haven't had a chance to go look much further, but following the steps in the LESS debugging thread, it seems to make it past the LESS compilation rather quickly so I'm going to say this might be more related to #4145.

**Comment by stefanpenner** [comment]
@al3x-edge not yet

**Comment by jasonmit** [comment]
I did some triaging of my own and tracked it down to:
https://github.com/yahoo/ember-intl/blob/master/index.js#L129-L131

Which funnels 717 files which total 18mb to the asset tree.  This makes them available for side loading.. not sure why the build pipeline is choking though...

**Comment by al3x-edge** [comment]
Jason -- thanks for that. Great addition. I'll try that out today. This was in the sprint this week actually.

**Comment by al3x-edge** [comment]
Set our cherry pick for currently two ([`en-us`, `es-mx`]) and I'm still getting the insanely long build times.  Added a few logs before and after L129 and I'm not hitting the before log at all.  Still trying to track it down.

**Comment by al3x-edge** [comment]
Although I wish it was faster than a minute or so, it's miles better than almost 16 minutes. Thanks for the work in ember-intl @jasonmit.  All done here :dancers:

**Comment by jasonmit** [comment]
A minute is still really slow.. so maybe another issue at large here within your app.  I would keep this open as ~700 files totaling 18mb should not add ~15 minutes to the build time.

**Comment by al3x-edge** [comment]
@jasonmit Might be a few other things, but I believe this is closer to the build time we were used to. I know auto-prefixer for us originally added quite a bit of overhead in build time.

**Comment by stefanpenner** [comment]
@jasonmit i think, once node reaches some % of memory utilization all time is spent swapping and GC'ing. I suspect this is the reason for the explosion in time.

I'm going to add logging to the uglify tools so that its clear what is going on.

**Comment by Jcamilorada** [comment]
Is this configuration enable for 1.3 version or just to 2.0?

**Comment by corrspt** [comment]
I've got a similar problem after adding the KendoUI suite of widgets. When I build the application with `build --environment production` it just hangs. (I've left it running for about 40 minutes on a 2014 Macbook Pro , 2.8Ghz i7 QuadCore).

If I remove the KendoUI widgets, the build works ok. The issue is easily reproducible, I've create a [repo to show the problem](https://github.com/corrspt/ember-cli-hangs-build-production) that you can checkout and simply run the build command (with `--environment production`) and you can see the problem occurring.

My project is using Ember 2.0 with CLI 1.3.8, but the repo I'm linking to is running Ember 1.13 with CLI 1.3.8.

Also, from what I've read in this and other github issues, I've tried adding this to my `ember-cli-build.js` but without luck:

```javascript
fingerprint: {
    exclude: ['kendo'],
    ignore: ['kendo']
}
```

As you can see from that repo in the `vendor` directory, I'm including the full set of widgets (a 2.2Mb file)... I'm going to try and find the dependencies of the things I need and include only those to see if the problem is the sheer size of the thing.

Any help is appreciated as I can't do production builds right now :+1:  Thanks for any help in advance.

**Comment by corrspt** [comment]
@stefanpenner : Sorry for pinging you directly, just wanted to know if you got an email about this and know about this. 

It's not my intention to bug you with 'my problem', just wanted to know if you (or anybody else on the team) knows that they can reproduce the issue with the repository I linked to (and in that case I'll patiently wait for you guys to have the time to check it out - and I'll help more If I can/know how to).

Thanks for the awesome work on ember-cli and all things ember!

**Comment by stefanpenner** [comment]
> Also, from what I've read in this and other github issues, I've tried adding this to my ember-cli-build.js but without luck:
> 
> fingerprint: {
>     exclude: ['kendo'],
>     ignore: ['kendo']
> }

this is only available on master (and the 1.13.9 release, i am releasing momentarily)



> @stefanpenner : Sorry for pinging you directly, just wanted to know if you got an email about this and know about this.

maybe my overzealous junk mail filter intercepted it

**Comment by corrspt** [comment]
@stefanpenner 

> this is only available on master (and the 1.13.9 release, i am releasing momentarily)

Thanks for the release, I will try it as soon as I can and see if I can bypass the issue with that.

> maybe my overzealous junk mail filter intercepted it

I know you and the team are super-busy with all things happening in ember (and you got your own lives going on, naturally) so I didn't want to add to that, just wanted to make sure my comment was noted (mostly because I could reproduce the bug with that repo).

Once again, thanks a lot for your hard work!

**Comment by corrspt** [comment]
@stefanpenner 

Hi, me again! Sorry to inform but updating to ember-cli 1.13.13 did not resolve the issue (even adding the fingerprint exclude).

I've [updated the repo](https://github.com/corrspt/ember-cli-hangs-build-production) to use the latest cli. Any tips or pointers in how to debug such an issue?

Thanks a lot.

**Comment by stefanpenner** [comment]
@corrspt taking a look now

**Comment by stefanpenner** [comment]
@corrspt fingerprinting has nothing to do with this: https://github.com/corrspt/ember-cli-hangs-build-production/blob/master/ember-cli-build.js#L7-L10

`app.import` essentially adds the given file to `vendor.js`, which is something we minify wholesale, not in chunks.

your options:

1. app.import a non minified version of kendo and let ember-cli minify it for you (recommended)
2. put kendo in public, add it to uglify excludes, and include it in your index files separate of vendor.

**Comment by corrspt** [comment]
@stefanpenner 

First of all, thanks so much for taking a look at my problem. And thanks for the pointers about the problem.

I can only try option 2, as i don't have a non-minified version of kendo to experiment.

I did what you suggested on option 2 (and was really hopeful on that). I've [updated the repo to reflect](https://github.com/corrspt/ember-cli-hangs-build-production/commit/657ef52267295158dade607df041cd07e9fd3005) my attempts but still I wasn't successful. Building to production still hangs. 
I couldn't find neither in the documentation nor in the source code of ember-cli-uglify/broccoli-uglify how to "exclude" a particular item (so I just disabled the minifyJS option), maybe the problem is there? 

Could it something with my setup? I'm using node v0.12.2 on OSX 10.10.5. I would like to be able to better debug to assist you (but I'm also a newbie regarding node.js stuff, sorry... although I've had to do some broccoli stuff so I don't get lost around the basic concepts )

**Comment by corrspt** [comment]
@stefanpenner Sorry for pinging you, just wanted to give an update on this situation.

I've managed to workaround the issue, but it involves removing the `kendo.ui.all.min.js` file from the ember directories (vendor/public). I basically reference the file in `index.html` as you suggested but I don't put it in the ember directory. I build with `environment production` and then I copy the offending file to the correct place.

I thought files in public were not touched by the build process but apparently they are?.

Thanks a lot for your input, it did allow me to the point where I am today :+1:
