### ISSUE TITLE
Could we make the code examples on the website copyable without the line numbers?

### ISSUE THREAD

**Issue by kitsunde** [ember-cli/ember-cli#4390]
The code blocks on the ember-cli isn't copyable without also getting the line numbers. Compared to say: http://guides.emberjs.com/v1.12.0/routing/defining-your-routes/

It would make it a bit more pleasant to copy things when you're trying things out.

**Comment by stefanpenner** [comment]
ember-cli is the repo for the cli tool, i suspect you are looking for emberjs/guides

**Comment by kitsunde** [comment]
@stefanpenner http://www.ember-cli.com/user-guide/#models

**Comment by stefanpenner** [comment]
ah

**Comment by stefanpenner** [comment]
cc @joostdevries

**Comment by stefanpenner** [comment]
Would accept a PR to improve this

cc @leo

**Comment by leo** [comment]
Since we're using the Jekyll version that's running on GitHub's servers, we won't be able to change the structure of the code highlighting to disable this through a different markup.

So I've decided to solve this problem by simply hiding the line numbers: https://github.com/ember-cli/ember-cli.github.io/commit/8776609d3975b4add34df626bd3bc53efc1da488
