### ISSUE TITLE
Add support for in-repo-addon tests

### ISSUE THREAD

**Issue by SaladFork** [ember-cli/ember-cli#4461]
> tests inside an in-repo-addon aren't picked up currently, which is why they're added to the tests folder for now, but I understand how that can cause possible conflicts
> -- @trabus 

The messaging for in-repo-addons is often "they're just like full addons, with the only difference being where ember-cli looks for them." This is true in every regard but the tests.

Also affected, generators:
```
$ ember g component ember-calendar -ir calendar
  create tests/unit/components/ember-calendar-test.js
```

**Comment by MiguelMadero** [comment]
Having the tests on a separate folder is really important. The whole purpose of using in-repo-addons is to create a separation of concerns between the app. Having them in the sample place mixes this concerns. It also makes it hard if in the future we want to extract this into a normal addon.

**Comment by trentmwillis** [comment]
Reviving this issue to see if we can make some progress.

What is the desired behavior here? Assuming I have my tests inside my in-repo-addon's directory, should they be totally separate? Meaning that they will run in a totally different test suite and be setup with a `dummy` app and so forth. I feel that is overkill but it might make the most sense. You'd run the tests via something like `ember test -ir my-addon`.

Or, should the tests just be bundled into the consuming app's test suite? I feel this behavior could make sense as the in-repo-addon is likely coupled to the app. It would also save us from having to duplicate test helpers between the main application and any in-repo-addons. I'm not sure which approach is better/more correct.

cc @pete-the-pete

**Comment by MiguelMadero** [comment]
@trentmwillis all of the above, which is probably the simplest.... Let me expand

* I think the structure of an in-repo-addon should be identical to the structure used by regular addons, including tests and a dummy app (which could be ignored). My main goal with this is separation of concerns. I don't want the app/in-repo-addon coupled at all with the app. That extends to test-helpers. Others expressed the intention of breaking the in-repo-addon into a proper addon. That is easy to do if we avoid the coupling. 
* I like your idea of runnin in-repo tests. That follows the pattern already used by generators. 
* Running `ember test` should run the app and in-repo tests as well. I think that makes more sense as a default, especially for CI. If not, we could have a command like `ember test --all`. I think we would get this without even trying since the tests will be funneled into test.js for the other command to work, so if anything we would need a command to exclude them, 
* For in-repo test helpers to work we would have to modify `test-suffix` to require `addon/tests/test-helpers`
* Ideally test-helpers should be defined and loaded independently. This will be tricky. It's hard to isolate helpers that call `Ember.Test.register*`. So it might be fine if all the tests include all the helpers. If the addon moves out of repo, then the consuming app will simply have to import them manually. It will be a bit harder if the addon is using any of the app's helpers, which we would have no way to prevent. I know there have been some talks about parallelizing tests and that also provides a bit of isolation. Maybe that could be used to run each set of tests in isolation. 

Does this makes sense? Do you think this deserves its own RFC to discuss further?

**Comment by MiguelMadero** [comment]
@trentmwillis another idea is to run all the tests from the *in-repo-addon* folder if we want isolation. 

```
$ ember test # runs only the the app tests
$ ember test --run-in-repo-addon-tests # new flag to include in-repo addon tests
$ cd lib/my-addon && ember test # runs all the tests for my-addon
$ ember test --in-repo=my-addon # just a short cut for ^^ 
```

Doing that works today already, except for the new commands.

**Comment by trabus** [comment]
@MiguelMadero I definitely think this deserves an RFC, though I think you have much of it fleshed out here. I like the idea of a command flag to identify test context, we can work out the details and naming in the RFC.

**Comment by MiguelMadero** [comment]
Sounds good! I'll add it to my list of RFCs to write.

**Comment by trabus** [comment]
> I think the structure of an in-repo-addon should be identical to the structure used by regular addons, including tests and a dummy app (which could be ignored). My main goal with this is separation of concerns. I don't want the app/in-repo-addon coupled at all with the app. That extends to test-helpers. Others expressed the intention of breaking the in-repo-addon into a proper addon. That is easy to do if we avoid the coupling.

I absolutely agree with this. Though having a dummy app for each addon might be a bit much. 

> I like your idea of runnin in-repo tests. That follows the pattern already used by generators.

We can absolutely setup the blueprints to be able to handle this. Much of the blueprints will be handled by just changing the default.

> Running ember test should run the app and in-repo tests as well. I think that makes more sense as a default, especially for CI. If not, we could have a command like ember test --all. I think we would get this without even trying since the tests will be funneled into test.js for the other command to work, so if anything we would need a command to exclude them,

I think that we'll need to provide some fine grained control for this, and probably don't want to run all tests by default. I think having an opt in flag like `--all` would be good. I think the glob lookup for tests would pick up these tests, so yes, we'll need to figure that part out for sure.

> For in-repo test helpers to work we would have to modify test-suffix to require addon/tests/test-helpers

:+1: 

> Ideally test-helpers should be defined and loaded independently. This will be tricky. It's hard to isolate helpers that call Ember.Test.register*. So it might be fine if all the tests include all the helpers. If the addon moves out of repo, then the consuming app will simply have to import them manually. It will be a bit harder if the addon is using any of the app's helpers, which we would have no way to prevent. I know there have been some talks about parallelizing tests and that also provides a bit of isolation. Maybe that could be used to run each set of tests in isolation.

I'm not as familiar with this, so I'll defer to someone with more knowledge of it.

**Comment by MiguelMadero** [comment]
> I absolutely agree with this. Though having a dummy app for each addon might be a bit much.

I think that is already optional... and we also have a `--dummy` flag for generators. So we not sure if `--ir my-addon --dummy` makes sense. 

> I think the glob lookup for tests would pick up these tests, so yes, we'll need to figure that part out for sure.

It depends on how we build things. Today, the test tree for in-repo addons doesn't end up in the testTree... Maybe someone thought about it, but likely is just the same behavior as for external addons. This has pros and cons. It provides the isolation I was referring to, but it also makes the `--all` flag harder to implement.

**Comment by trabus** [comment]
@MiguelMadero are you at Emberconf right now? If so come find me later, we can chat about it!

**Comment by MiguelMadero** [comment]
Unfortunately, I couldn't make it this year :(

**Comment by stefanpenner** [comment]
i like this idea, but lets get an RFC fleshed out and continue discussion on it.

**Comment by MiguelMadero** [comment]
Yes, I'll work on it this weekend or early next week.

**Comment by olivierlesnicki** [comment]
How is this item going?

**Comment by olivierlesnicki** [comment]
Not sure the run tests from pods rfc is the minimum viable first step towards this

**Comment by jamesarosen** [comment]
Related to #5016

**Comment by jamesarosen** [comment]
RFC: ember-cli/rfcs#60
