### ISSUE TITLE
Replace sane or polling and favor chokidar

### ISSUE THREAD

**Issue by bucaran** [ember-cli/ember-cli#4503]
Hi! 

Have you considered replacing the current watcher strategy in favor of a more versatile and *efficient* option like [`chokidar`](https://gitter.im/paulmillr/chokidar). You can see in the README the list of projects using chokidar already.

Regards

**Comment by stefanpenner** [comment]
Yes. We unfortunately do no want native extensions. As it is a very suboptimal user experience when something goes wrong.

In practice watchman works as good, or better the chokidar. It does this because it runs as a dedicated server abstracting the OSes fs watching quirks

**Comment by bucaran** [comment]
I am not confident enough to discuss the internals of `chokidar` here, but I know a lot of work has gone into using each platform (OS) native features efficiently. I have not noticed any issues with Fly that relies on this library either. 

> it runs as a dedicated server abstracting the OSes fs watching quirks

`chokidar`'s main strength is precisely this AFIU.

I was not aware `watchman` could perform better than `chokidar` as I was even unaware of `watchman` existence until recently.

Thanks.

**Comment by es128** [comment]
watchman can't be installed via npm, so it can't easily be integrated as a widely-used dependency. Each user would need to install it individually (using homebrew, in the case of OS X). So choosing sane means that the majority of end-users are likely polling, which has all sorts of downsides.

Anecdotal evidence does support the notion that watchman is much more stable an solid than any purely npm-based alternative, although I haven't investigated much myself.

Somewhere on my to-do list is looking into adding a watchman interface for chokidar, so that users who do have it installed can realize its benefits when using chokidar. However, I don't think this would eliminate the necessity of preserving `fsevents` as a dependency for all the OS X users who don't have watchman, so the small number of cases where this is problematic will remain - probably until npm gets better at suppressing issues with `optionalDependencies`.

**Comment by stefanpenner** [comment]
> watchman can't be installed via npm, so it can't easily be integrated as a widely-used dependency.

Our statistics on watchman posix consumers with watchman installed is sufficiently high to assume it is not a barrier for our users.

**Comment by es128** [comment]
@stefanpenner That's very interesting. You're detecting the presence of watchman and feeding back the stats to a central server somewhere? Can I see the statistics somewhere?

**Comment by bucaran** [comment]
I know Ember uses [leek](https://www.npmjs.com/package/leek), but I am not sure if this is what they are using to gather this data.

**Comment by stefanpenner** [comment]
> @stefanpenner That's very interesting. You're detecting the presence of watchman and feeding back the stats to a central server somewhere?

yes

> Can I see the statistics somewhere?

Not quite yet, we plan to open proportion based statics at some future point in time. Currently we don't plan on ever releasing the raw data, in-case some personal identifying information exists. We have worked hard to ensure that we don't leak private information, but accidents happen.

Currently we use the statistic to gauge version adoption, measure build times (to notice regressions, like the recent one), error rates etc.

**Comment by stefanpenner** [comment]
note: I have fleshed out my above pros/cons and rationale.

**Comment by stefanpenner** [comment]
One thing worth noting, cost of change is high. I have fairly limited time to deal with fallout or pain, so the benefit must be extremely convincing.

**Comment by bucaran** [comment]
Closing this as I don't think you folks are going to be replacing `watchman` with chokidar anytime soon :disappointed:
