### ISSUE TITLE
Reopen #538

### ISSUE THREAD

**Issue by bucaran** [ember-cli/ember-cli#4543]
I have a similar situation (soft for exactly the same) as #538

Please reopen as I don't see how locking it is helping other rodents stumbling upon this issue with the same problem. I have upgraded to the latest everything and still experiencing horribly slow rebuilds. I should mention the problem does _not_ occur on SDD mbps, but it still takes quite a while to compute (less than 10s though).

On HDD mbps however my team is experiencing 3 minute rebuilds in average. 

Also, @rwjblue @stefanpenner I would appreciate if you could address my issue [here](https://github.com/broccolijs/broccoli-funnel/issues/27).

While it has already being established that ember-cli performs poorly on HDD mbps, it's still not clear why it fails to clean the `tmp` directory while it does so on SDD mbps.

**Comment by stefanpenner** [comment]
there is already an issue tracking this, and you have commented on it.

**Comment by bucaran** [comment]
This is about reopening #538.

**Comment by stefanpenner** [comment]
this issue is being tracked at https://github.com/ember-cli/ember-cli/issues/4460

**Comment by bucaran** [comment]
Gotcha! :+1:

**Comment by stefanpenner** [comment]
#538 was related to a regression we explicitly introduced due to a safety issue related to hardlinks on HFS+. This issue was not apparent on ext3/4 (where the initial tests and development of broccoli occurred) and was quite surprising when encountered. Turns out, hardlinks on HFS+ where layered on top of the existing FS, and the resulting implementation hard some non-standard quirks. This quirks could result in unexpected data loss.

A quick choice was made to migrate to copying, to give time for jo to land a refactor the relied on symlinks and also ensure the symlinks didn't suffer from similar issues.  Unfortunately that process took much longer then expected (do to everyone having different responsibilities). Anyways, it landed and allows for fast builds assuming we don't introduce invalidations (which apparently we have in some scenarios).

An interesting quirk of broccoli, is it is truly exceptionally fast. Unfortunately, in some scenarios we don't even realize how much work broccoli is actually doing for us. This allow us to get sloppy.

Which means, when several things go side-ways. Like ember-paper introduces 86,000 files (and the sass plugin grabs all of them) and we have an existing invalidation issue that causes extra work to happen on rebuild, we accidentally create the perfect storm of work amplification. Which unfortunately makes broccoli itself look poor.

One thing that is truly the responsibility of broccoli  (and historically a short coming ) is visibility into what is does under the hood. Without this, the WTFs per minute when something goes wrong increase rampantly.

Because of this, I have implemented the following tools (additions):

* https://github.com/stefanpenner/broccoli-stew/blob/master/lib/log.js#L27
* https://github.com/stefanpenner/broccoli-stew/blob/master/lib/debug.js#L20
* https://github.com/ember-cli/broccoli-caching-writer/pull/44
* https://github.com/caitp/cauliflower-filter/pull/16

With each step we mitigate an entirely category of visibility problems, and the resulting problems become obvious and don't appear quite that tricky to resolve.

Anyways, hopefully this further context is useful.

**Comment by kellyselden** [comment]
@stefanpenner well said! lots of good info.

**Comment by wayne-o** [comment]
I f#%^king love ember-cli!
