### ISSUE TITLE
Is it possible to add .jshintignore for my app?

### ISSUE THREAD

**Issue by kitsunde** [ember-cli/ember-cli#4586]
I've tried creating a **.jshintignore** file with:

```
mirage/*
app/mirage/*
```

In both **/** and **/app*** and I've created **/app/mirage/.jshintignore** with:
```
*
```

But it's not getting picked up and ember-cli is showing me the same JSHint errors for **/app/mirage/config.js**. Is this not supported and if not could we consider adding it?

**Comment by stefanpenner** [comment]
im surprised it doesnt "just work", but we can likely ensure it does.

**Comment by rwjblue** [comment]
broccoli-jshint is wiring up the the `.jshintrc`'s, but it doesn't do anything with `.jshintignore`.  I definitely welcome a PR adding this...

**Comment by jfelchner** [comment]
Just ran into this.  I was trying to swap out jshint for eslint and wanted to basically just ignore every directory in my app to keep from getting any jshint errors since it doesn't seem to be possible to disable the jshint linter.

To my surprise the `.jshintignore` file was being ignored. :)

**Comment by rwjblue** [comment]
This came up in another issue recently (maybe @nathonhammond recalls which one), but ember-cli-quint needs to use a config option to allow opting out of its 'lintTree'...

**Comment by nathanhammond** [comment]
`.jshintignore` isn't supported as a feature inside of the NPM-driven version we have of jshint. [Docs here.](http://jshint.com/docs/api/)

In our general addon story there's no guarantee that we'll have options available at the appropriate time as `lintTrees` doesn't receive options as an argument. We're able to save off something to `this.options` and rely on the `included` hook to run first, however. BUT! While trying to come up with a PR for this I encountered another nasty bug: https://github.com/ember-cli/ember-cli/pull/4923

So, hold on.

**Comment by baron1405** [comment]
Is this issue closed because .jshintignore is now supported or because it will not be supported? I would like to prevent jshint from being run against modules/ember-bootstrap.

**Comment by nathanhammond** [comment]
@baron1405 This issue was closed because `.jshintignore` isn't supported by the API of the jshint function (see docs link above) and because I mistakenly associated the completion of the subissue with this entire issue.

This is a non-trivial change as it would require us picking up the processing of the `.jshintignore` files and running those against our broccoli trees. Open PR here that you can help bring home: https://github.com/rwjblue/broccoli-jshint/pull/40

(I don't think there is anything else we have to do inside of ember-cli to support this, so I'm leaving this closed.)

**Comment by baron1405** [comment]
Thanks @nathanhammond for the quick and informative reply! I'm pretty new to the JS/Ember/Broccoli worl so I can't promise I can make head or tail out of the broccoli-jshint issue but I will have a look, maybe use it to drive my learning :-)

**Comment by rwjblue** [comment]
Also, by default `modules/ember-bootstrap` should not be jshinted at all and you should not need a `.jshintignore` for this.  See https://github.com/kaliber5/ember-bootstrap/pull/51 which fixes.

**Comment by baron1405** [comment]
Excellent, thanks!

**Comment by simonihmig** [comment]
Sorry for being a little bit off topic, but as ember-bootstrap was specifically involved here,  I just wanted to drop in. I cannot see any jshint errors on ember-bootstrap, Travis is not complaining either. Maybe it is because of some non-standard jshint rules? 

@baron1405 If you feel there is something that needs to be fixed in ember-bootstrap, please file an issue here: https://github.com/kaliber5/ember-bootstrap. Thanks!

**Comment by baron1405** [comment]
No errors, it is just that jshint was being run against ember-bootstrap, which produced a lot of "ok" output and made the build take longer. Happily, you merged the patch from @rwjblue today and I am looking forward to a new release of ember-bootstrap.

Thanks for checking!

**Comment by baron1405** [comment]
@rwjblue and @simonihmig just tried ember-bootstrap 0.6.2 and am happy to report that jshint no longer runs against ember-bootstrap. Thanks for the patch and quick release!
