### ISSUE TITLE
Addon not using its own addons

### ISSUE THREAD

**Issue by QuantumKing** [ember-cli/ember-cli#4602]
I have an addon which makes use of `ember-browserify`. The code for my addon is in the addon folder and when I compile my main app, I get the error `Could not find module 'npm:ember-monitorable'` meaning `ember-browserify` hasn't worked its magic.

What's going on here?

**Comment by stefanpenner** [comment]
> What's going on here?

this is not supported.

addons of addons have very limited support currently. This support is artificially limited due to the the ambiguity when dealing with dupes (NPM node_module graph can easily contain dupes). We will likely enable features scenario by scenario as we have thought about them and solved them correctly.

In-regards to the npm stuff, @chadhietala's packager/assember work will provide NPM deps as a primitive to the whole system, and will replace ember-browserify entirely. At this point the nested deps will work. Tracking issue for this effort is here: https://github.com/ember-cli/ember-cli/issues/4211

**Comment by QuantumKing** [comment]
Ok, good to know. So its currently impossible to say, write an addon using coffeescript, since `ember-cli-coffeescript` can't be used? What about all the addons which are included by default in my addon, such as `ember-cli-htmlbars`? How do those work?

**Comment by stefanpenner** [comment]
> addons of addons have very limited support currently.

Some work as expected like `ember-cli-htmlbars`, in theory the coffee-script one should also work, although I don't use it so I don't know.



> How do those work?

Any addon that doesn't potentially collide with duplicates of themselves can work.

**Comment by stefanpenner** [comment]
this isn't a bug, going to close this.
