### ISSUE TITLE
[Question] How can a blueprint generate a path to related modules for import (pods)?

### ISSUE THREAD

**Issue by pixelhandler** [ember-cli/ember-cli#4868]
I have a few blueprints in an addon that need to import related modules, e.g. to compose a service object. 

I can’t find a method that will generate a path to a module, and works out the path when consuming app is using pods. the service object and initializer need to import a model, adapter, and serializer.

Currently I use a relative path to those modules based on a resource name. but I need to use a path that can import the related modules from a pods file layout or traditional.

Any ideas?

See - https://github.com/pixelhandler/ember-jsonapi-resources/issues/44

**Comment by sandstrom** [comment]
I think this is better suited for [StackOverflow](http://stackoverflow.com/questions/tagged/ember.js), or asked in the IRC-channel.

**Comment by pixelhandler** [comment]
Seems to me like this either leads to a feature request or need for documentation.

Already asked in slack got zero responses. Seems like a legitimate issue to be able to write a path to a module for people using pods.

**Comment by pixelhandler** [comment]
@sandstrom just asked again on IRC and Slack.

**Comment by pixelhandler** [comment]
@trabus perhaps you my have some insight? Thanks for taking a peek at this question/issue when you get a chance :)

**Comment by trabus** [comment]
@pixelhandler looking at it now. :)

**Comment by pixelhandler** [comment]
After a chat with @trabus looks like the addon blueprints need to implement their own path resolution behavior for related modules, use fs.exists-sync to lookup paths for related modules in addon blueprint.

**Comment by trabus** [comment]
AFIK, there's no built-in way to detect existing modules/content in a project. You could use the exists-sync module for looking up the path where it should be, then determine whether the path is pods or classic. Otherwise you'll need to leave it to your user to generate depending on their needs. 

You'll need to setup the locals to consider whether the blueprint is being generated as a pod or not, then output the import path as a local, [similar to how the component blueprint does](https://github.com/ember-cli/ember-cli/blob/master/blueprints/component/index.js#L66).

I wish I had a better answer, but hopefully that helps.
