### ISSUE TITLE
ember server is dramatic slowly at windows 10 + SSD + 16G Memory

### ISSUE THREAD

**Issue by gdipkf1986** [ember-cli/ember-cli#4949]
I'm newbie of ember,  when start to build an existing large project (10k files), it takes 19703 ms to initial and takes 20k+ ms to increase build when i change anything in any file, is there any way to improve it? Because my colleague using mac is quite fast and only few seconds to build up. 

I tried to install ember-cli-windows and several similar tools but not one help, it there any way to solve this problem? 

The project will concat all vendor js files into "vendor.js" and all project files into an "app.js", is there anyway to avoid it concat and process vendor files every time?  This is my increase build time:
![image](https://cloud.githubusercontent.com/assets/1468041/10445364/2a9bf736-71a4-11e5-9f38-c9b3204deb8a.png)

It's really depressed when work with live-reload, you have to wait for half minute at every save, and I like to save at every few seconds.

**Comment by gskaplan** [comment]
I had this same problem and could not find a reasonable solution. I got very excited from reading about EmberJS and ember-cli, only to be let down by poor Windows compatibility. Ultimately, I had to setup an Ubuntu VM to do everything in. It would be REALLY appreciated if there was at least a tech note on how to properly setup Windows[10] such that it is as performant as the other OS's.

**Comment by david-duncan** [comment]
There have been a ton of windows improvements and tickets and its still slow in the end. Every few weeks I try it out on my windows desktop at home and am still disappointed. Its not so much embers fault as it is windows. Windows is an awful environment to develop in.

We mandate everyone use *nix on our team. Every tool you use will be easier. No constant struggle trying to emulate a POSIX terminal either.

**Comment by gskaplan** [comment]
I've been using Windows for Java and C/C++ development for ages without a hitch. What exactly is it about Windows that makes it such an awful environment to develop in? Certainly if someone could identify what the issue is, at least such a statement about Windows could be justified, or, the offending stuff could be turned off.

If in fact there is no way to get reasonable performance out of Windows for developing Ember apps, then it would be in Ember's best interest to make such a statement so that newbies, such as me and the others who have made similar postings, would know not to even bother trying it on Windows. But as it stands now, the typical developer will decide to give Ember a whirl, experience ridiculous slowness, and then start digging into the net to figure out what they did wrong, only to eventually come upon these postings that say that Windows is not a good development environment. For me, I wish I knew that from the start so I didn't spend time installing plug-ins (that often failed due to permission issues), etc. Ember looks fantastic and enticing - let's just declare it in the getting started docs that it doesn't perform well on Windows and save us newbies some time.

**Comment by stefanpenner** [comment]
@gskaplan io perf (maybe just through node) is laughable, compared to posix.

I'm in the process of reducing io of rebuilds by about 90% across most broccoli, this will likely be a welcome change for our windows (and slow disk users). But will benefit everyone.

As usual, the large chunks of work is related to strange things of non-posix system (windows) do.

This tools is actually used at Microsoft, they have contributed to the guides and many users with large apps who have followed the guides correctly have much more reasonable Windows builds.

For those that fail to follow instructions, or some strange setting in their profile somehow defeats it. (Or have slow disks) My current above mentioned effort should provide a much better experience.

**Comment by lpaluszk** [comment]
@gdipkf1986 If you can, run the command prompt as administrator. It helps a lot.

**Comment by gskaplan** [comment]
@stefanpenner and others on this thread. I followed the directions on ember-cli.com under the Windows topic and that did indeed improve performance DRAMATICALLY. The rebuild speed is now about the same as it is under my Ubuntu VM which gives me the option to move back to my Windows environment. For whatever reason, I MUST use the PowerShell with Administrator privileges. If I don't use Admin privileges, it is unbearably slow. That's fine for now but, if someone knows why, I would love to know why there's such a difference between Admin/Non-Admin, and is it possible to setup my machine such that I don't need to use Admin for the shell.

For the benefit of those who are experiencing this, here is the link to how to configure Windows:  http://www.ember-cli.com/user-guide/#windows

Also, for anyone who can update the "Guides", I think it would be a really great addition to direct Windows users to http://www.ember-cli.com/user-guide/#windows before running the "ember serve" command so that they won't get caught in the performance trap (and possibly give-up right away).

**Comment by rwjblue** [comment]
Without specific permissions (which you get when you are an admin) the build tooling cannot create symlinks on Windows.  This means that instead of using small & fast symlinks we have to fall back to completely copying every file for every step of the build pipeline (and our build pipeline has many layers so this is magnified greatly).

**Comment by gskaplan** [comment]
Thanks @rwjblue. That makes me wonder if there's a way to assign my user the necessary permissions. I'm not familiar enough with Windows security to know if I can just add that permission to my account.

**Comment by stefanpenner** [comment]
> That makes me wonder if there's a way to assign my user the necessary permissions.

One can, but only if not an administrator. Strangely, If those permissions are assigned, and the user is an administrator the shell must still run as an administrator. If the user is not an administrator but has the permission they can use it freely.

^^ information provided by one of our friends from Microsoft @felixrieseberg (who is also an active ember-cli user and contributor)

**Comment by gskaplan** [comment]
@stefanpenner - that is very quirky. I looked and my account is an administrative account, so I would still have to run PowerShell as an admin. Harumph.

**Comment by stefanpenner** [comment]
> I'm in the process of reducing io of rebuilds by about 90% across most broccoli, this will likely be a welcome change for our windows (and slow disk users). But will benefit everyone.

^ is likely the best solution

**Comment by lpaluszk** [comment]
@stefanpenner Will SassCompiler benefit from those changes as well? If I have a bower component with bower_components folder inside my build time goes up from 1400ms to 25000ms just on SassCompiler step.

I 've come across a repo where I think I saw your issue raised about the sass compiler speed and suggested 2 approaches to the repo owner, but I can't find it now.

**Comment by gdipkf1986** [comment]
@lpaluszk  Thanks, I will try, but how could I make node_modules as flat? I just npm install and all modules got their dependencies inside  recursively,

**Comment by lpaluszk** [comment]
@gdipkf1986 sorry I think I actually meant bower components. 

Getting dependencies through bower doesn't download component's own dependencies but if you run bower install or npm install inside that component it will download them. This causes ember-cli to traverse through a lot more folders looking for changes, which is what takes so long.

**Comment by jsifuentes** [comment]
I also experienced slow compiling on Windows, and came to see if someone else reported it. Mine took 50+ seconds to compile. This is straight from a brand new Ember project.

$ ember server
Future versions of Ember CLI will not support v4.1.2. Please update to Node 0.12 or io.js.
version: 1.13.8
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 56111ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
TreeMerger (stylesAndVendor)                  | 5337ms
SimpleConcat                                  | 4964ms
TreeMerger (ExternalTree)                     | 4782ms
TreeMerger (vendor)                           | 4667ms
BroccoliMergeTrees                            | 4170ms
ConcatWithMaps                                | 4093ms
Funnel                                        | 3380ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Funnel (35)                                   | 17233ms (492 ms)
ConcatWithMaps (4)                            | 6523ms (1630 ms)
SimpleConcat (3)                              | 6458ms (2152 ms)
TreeMerger (stylesAndVendor) (1)              | 5337ms
TreeMerger (ExternalTree) (1)                 | 4782ms
BroccoliMergeTrees (3)                        | 4704ms (1568 ms)
TreeMerger (vendor) (1)                       | 4667ms

**Comment by stefanpenner** [comment]
Solution is to follow the provided instructions exactly, and ongoing work will minimize the net cost nicelt

**Comment by felixrieseberg** [comment]
Just in case someone else finds this in the future: +1 to everything my friend @stefanpenner said here. Running as PowerShell as Administrator will improve your performance dramatically (and so will turning off the search index & defender tools for tmp folders). We at Microsoft (who run Macs all the time and have decent comparisons) have roughly the same speed with those settings.

The administrator thing is annoying, but we won't be able to do anything about that anytime soon (sadly).
