### ISSUE TITLE
Running ember cli from code

### ISSUE THREAD

**Issue by eibrahim** [ember-cli/ember-cli#4980]
I am trying to create a GUI wrapper for ember-cli.  I was able to do something like this to run a cli command:

```
var cli = require('ember-cli');
cli({
    inputStream: process.stdin,
    outputStream: process.stdout,
    cliArgs: ['-v']
}).then(function(r){
  console.log(r);
});

```

I want to get the list of commands and tasks but the CLI doesn't expose any of that.  I see that you use requireAsHash to parse out the commands and tasks but I am not sure how to use that from within my code, other than copy and paste requireAsHash and have it parse node_modules/ember-cli/commands...  Any ideas? Thoughts?

**Comment by stefanpenner** [comment]
Running the help command should help you get programmatic info

**Comment by kellyselden** [comment]
`ember help --json` using master

**Comment by eibrahim** [comment]
`ember help --json` doesn't work

version: 1.13.8
The option '--json' is not registered with the help command. Run `ember help --help` for a list of supported options.

**Comment by eibrahim** [comment]
I really prefer to access the `commands` and `tasks` arrays so I can play with them in my GUI.  so getting the help text and trying to export is not ideal.  I don't mind forking the repo and exposing whatever I need and can keep that in sync with master as changes are made...  do you think that's a good approach.

**Comment by eibrahim** [comment]
Even better getting access to the `environment` variable.  Maybe I can change cli.run to return the environment (or have the command.run return the environment somehow)...

**Comment by kellyselden** [comment]
you have to be using master, looks like you're on 1.13.8

**Comment by eibrahim** [comment]
That's great.  exactly what I wanted.  I ran it from the command line of my project and it worked but for some reason when I run this code, it doesn't work and is using the global version (i think):
```
var cli = require('ember-cli');
cli({
    inputStream: process.stdin,
    outputStream: process.stdout,
    cliArgs: ['help --json']
}).then(function(r){
  console.log(r);
});
```

**Comment by H3Chief** [comment]
@eibrahim at a cursory glance, it looks like all of the functionality of the cli is extracted into `ember-cli/lib`. this is hugely important, because:

If you wish to use the ember-cli programmatically, create a js file that consumes the modules exported under `lib`,  and point to that file's location from the `main` property of your `package.json`, then you'll have what you need without having to do any parsing at all. 

You would actually get rid of the following code, because it's all about stdio, which you wouldn't need if you want to access the cli's functionality programmatically. Incidentally, that's also why it's not resolving correctly, because you're accessing the stdio version, which is symlinked to the global, instead of the local version, which is only symlinked to the local `.bin` when executed from the `bin` script indicated in ember-cli's `package.json`.  So that means, you actually don't need:

```
cli({
    inputStream: process.stdin,
    outputStream: process.stdout,
    cliArgs: ['help --json']
})
```
And instead, need to load the cli from it's local install, and include the `/lib` folder instead:

```
var cli = require("node_modules/ember-cli/lib/cli");
// variable `cli` now has access programmatically to all the exports from lib/cli
```

**Comment by eibrahim** [comment]
That seems to work.  Thanks.

**Comment by H3Chief** [comment]
awesome! Glad I could help. If it works well, you should consider adding a `main` property to the ember-cli and submitting a merge request.

My guess though, is that some of the cli won't work as expected programmatically, so there would need to be separate docs, and that's a huge chore.

If it does work well, let me know, and I'll pitch in if I can.

**Comment by stefanpenner** [comment]
If someone has some spare cycles, it would be great to have this as a readme entry.

(working on the CLI release as we speak so i don't have time atm)

**Comment by eibrahim** [comment]
I will add it to the readme and do PR shortly...

@H3Chief I agree that some things are going to be a pain to work programmatically.  For example, I just tried to run this:

```
var cli = require("ember-cli/lib/cli");
cli({
    inputStream: process.stdin,
    outputStream: process.stdout,
    cliArgs: ['new','hello_world']
}).then(function(r){
  console.log(r);
});
```

And got the error:
`You cannot use the new command inside an ember-cli project.`

I don't think it's a big deal but there is definitely going to be some tweaks to programmatically accessing the cli.

**Comment by stefanpenner** [comment]
> And got the error:
> You cannot use the new command inside an ember-cli project.
> 
> I don't think it's a big deal but there is definitely going to be some tweaks to programmatically accessing the cli.

:+1: im on-board with improving the ergonomics, but please note that error sounds totally valid (and potentially helpful)

**Comment by stefanpenner** [comment]
its also worth noting, ember-cli's own test suite uses this API so its stable and will likely remain so.

quick example: https://github.com/ember-cli/ember-cli/blob/master/tests/helpers/ember.js

**Comment by H3Chief** [comment]
> If someone has some spare cycles, it would be great to have this as a readme entry.

> (working on the CLI release as we speak so i don't have time atm)

> thanks @H3Chief, appreciate the help answering this question.

No problem. Trying to recoup some karma from my initial comments at #2041. I will have some time this Saturday that I could take a stab at crafting the beginning programmatic usage section in the readme, and setting up the programmatic consumption from within the `package.json`. 

My biggest concern were incompatibilities the might crop up from typical differences between a cli's api and a module's api, but since you've confirmed the test suite uses the api, then I agree, there should be very little to be concerned about on that front. 

@eibrahim you don't want to initialize the usage of the api in the same way that `bin/cli` does. You are now a level deeper, and can access stuff without going through stdin/stdout.  That's what is causing your error response.  Take out the following code:

```
cli({
    inputStream: process.stdin,
    outputStream: process.stdout,
    cliArgs: ['new','hello_world']
})
```
Removing that block *should* resolve your error, assuming that you call a method exported from the cli correctly. A good place to look for examples would be the test suite within the `ember-cli`. Based on @stefanpenner description, their tests consume the cli api in exactly the same way you are trying to do so.  You'll probably find some great code snippets from within those files

**Comment by eibrahim** [comment]
I created this pull request https://github.com/ember-cli/ember-cli/pull/5065

But it looks like I will need to change it to address both your comments...

**Comment by eibrahim** [comment]
I tried using the example in the helpers/ember.js mentioned above but can't make it work.  The code in my pull request works but I am still not sure why you said it is not the right way to do it.

**Comment by H3Chief** [comment]
Those configs set the cli UI. Generally speaking, if you want access to the api programmatically, you aren't going to be interacting with the same UI.  However, if you're intending to intercept and inject something, basically extending the ember-cli in order to create a new cli,  *then* it makes sense, but you'd probably still be changing it up a bit.

The main cli module in `/lib/cli/index.js` sets those properties by default, and so any initialization of api programmatically would want to be focused on overwriting those defaults, or  consider executing them within a child process, instead of just confirming them or running them inside parent app's main process.
