### ISSUE TITLE
Question: is it possible to customize paths used by ember-cli ?

### ISSUE THREAD

**Issue by gauthierj** [ember-cli/ember-cli#4998]
Hi,

I'm currently using ember-cli with a java backend build with Maven. I was wondering if it is possible to customize various paths used by ember-cli to get it closer to Maven conventions : 
- Place "app" somewhere in "src/main"
- Place "dist" and "tmp" somewhere in "target"
- Place "tests" somewhere in "src/test"
- Place "bower_components" and "node_modules" somewhere outside of the project (the same way as  "~/.m2/repository")
- ...

I could not find any information about this, neither in the documentation, nor on google. Can you give me a hint on this ?

Thanks, best regards,

Gauthier JACQUES

**Comment by stefanpenner** [comment]
The paths are not adjustable

**Comment by rwjblue** [comment]
It is quite likely that this will lead to some pain, but the examples you gave can all be configured.

> Place "app" somewhere in "src/main"
> Place "tests" somewhere in "src/test"

```javascript
// ember-cli-build.js

// ....snip....
var app = new EmberApp(defaults, {
  trees: {
    app: 'src/main',
    tests: 'src/test',
    styles:    'src/main/styles',
    templates: 'src/main/templates',
    public: 'src/main/public'
  }
});
```

> Place "dist" somewhere in "target"

Use `--output-path`: `ember build --output-path="target"`

> Place "tmp" somewhere in "target"

`./tmp` cannot be moved

> Place "bower_components" somewhere outside of the project

Configure Bower via `.bowerrc` to indicate an alternate directory.

> Place "node_modules" somewhere outside of the project

This can't be trivially moved, but it is possible to install packages in a parent directory instead of the apps directory.

**Comment by stefanpenner** [comment]
> The paths are not adjustable

I would prefer the "paths are not adjustable" statement to be the public understanding, although the internals support otherwise. The reality is, this omni flexible notion has little value, and more downside then upside. 

I would strongly encourage staying on the rails, this ensure generators continue to work, tutorials have relevant material etc. etc.

**Comment by gauthierj** [comment]
Yes, I'm starting to think it would be better to keep the ember front end in a separate project build with ember cli, and use it as a dependency in the web application, instead of trying to integrate source code of both projects together.

Thanks for your answers.

**Comment by stefanpenner** [comment]
> Yes, I'm starting to think it would be better to keep the ember front end in a separate project build with ember cli, and use it as a dependency in the web application, instead of trying to integrate source code of both projects together.

couldn't agree more.
