### ISSUE TITLE
Stylesheets with same names in addon/styles not included in vendor.css

### ISSUE THREAD

**Issue by mmelvin0** [ember-cli/ember-cli#5135]
With ember-cli 1.13.8, if I have two addons in my application with the following:
`addon1/addon/styles/some-style.css`
`addon2/addon/styles/some-style.css`

Only one `some-style.css` is concat'd into the resulting vendor.css.

These addons each contain other (differently named) stylesheets, which are included in vendor.css.

I can work around this by additionally namespacing my styles (e.g.):
`addon1/addon/styles/addon1/some-style.css`
`addon2/addon/styles/addon2/some-style.css`

Expected behavior: I shouldn't have to namespace `addon/styles` nor should I have to worry about conflicting with other addons as the `addon` directory is 'part of the addon’s namespace' per the documentation.

**Comment by stefanpenner** [comment]
This is largely by design today (yes it is crappy) We are going to be focusing on addons/nested-addons/peer-addons and these problems in broad strokes this year. It is unlikely that we will solve this issue piecemill but as part of a larger design.

We absolutely care about this, but wont be tracking this issue independently. We will be sure to include it in the addon rework.
