### ISSUE TITLE
Support seekable video

### ISSUE THREAD

**Issue by Mode7James** [ember-cli/ember-cli#5145]
Issue:  Video will not update 'currentTime' properties or seek to specific time.

Solution (possible):  Add support to the Express server definition to accept certain header ranges.  This Stack Overflow says a bit more:  http://stackoverflow.com/questions/24976123/streaming-a-video-file-to-an-html5-video-player-with-node-js-so-that-the-video-c

This specific example lists specific video files - I'm not sure if this is required or a wildcard can be used.

I'm a little surprised something as basic as video scrubbing isn't supported by Node-based build tools yet.  I guess until this support is added we need to ditch Ember-CLI and go back to Vagrant and good-ole Apache for video-heavy projects...

**Comment by stefanpenner** [comment]
Ember-cli is a development harness for building a UI. It should have nothing to do with video serving.

**Comment by leo** [comment]
@Mode7James As far as I know, the build-in express server in ember-cli is only ment to be used for the purpose of developing the client-side part of your app by responding to API request with sample data (so that you can test out how your app will behave with real data in it).

All in all, it shouldn't be used for serving data in production. An ember app usually consists of at least two parts: The client-side app itself and the API server. So if you want to stream videos to the client, just add this functionality to your API server (and not to the development environment - aka. "ember-cli").

**Comment by Mode7James** [comment]
@stefanpenner, @leo - I'm not suggesting a production server, I fully realize that ember-cli is meant for client-side development.  HTML5 doesn't "just work" like Flash video used to - which was confusing to me because there's not many articles on this (because usually this just works for everyone using conventional development environments).  Apparently html5 <video> needs the server set up correctly to allow for more advanced video playback like determining when the video has finished loading & seeking.  I'm hoping someone in the community has more experience with this than I have and can add it to Ember-CLI either as an add-on or as part of the basic package.  As it currently stands, I have several apps that allow scrubbing and seeking of video, programmatically easing of the video's currentTime and more advanced requests like playing video backwards & forwards.  I spent hours trying to figure out why my 'currentTime' continually read '0' and nothing would work as it should, until I realized it might be a deficiency with Node Express and Ember-CLI.  Even if I throttle the download in Chrome, it does allow the video to register the loaded progress and determine if the full video has loaded, but seek still doesn't work.  The only way I can develop something with advanced video capabilities is to upload to stage to observe each modification or serve it locally in something like Vagrant + Apache.

Since video is such a huge part of client-side UI and getting bigger, I'd think this is an important thing to support even if it's very basic.

**Comment by stefanpenner** [comment]
@Mode7James thank you for the further explanation. 

I do not feel this should be included by default as users may be confused that ember-cli has more functionality then their target host does. Currently ember-cli aims to produce something any static host could host. With the exception of another html feature History state. For this, we do allow the app to be build both with and without this required support (hash history)

As you mentioned, advanced video features (scrubbing etc) may not be supported out of the box. For this, I believe you idea of an "add-on" would be most appropriate. As it turns out, most of ember-cli's express code is [actually written as a series of](https://github.com/ember-cli/ember-cli/tree/master/lib/tasks/server/middleware) `add-ons`  and could likely be used as a reference point.

My recommendation is an add-on ember-cli-XXX, which clearly indicates it is a development only solution(for now), which provides an express middleware which is streaming aware. Given such an add-on, I would gladly accept a PR making note of it on the website. It seems like an important feature!

A quick google revealed https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/examples/express-stream.js  which may be interesting.

I am going to close this issue, not because I don't believe advanced video streaming is important (I do), but i do believe this may be best served as an add-on. If development of the add-on in question is prevented by some issue with ember-cli, an issue (or ideally pr) would be accepted.
