### ISSUE TITLE
Just CANNOT install ember-cli with npm

### ISSUE THREAD

**Issue by itsfadnis** [ember-cli/ember-cli#5170]
I'm running on mac osx yosemite 10.10.5 & this is what I get whenever I hit `npm install -g ember-cli`

    npm ERR! Darwin 14.5.0
    npm ERR! argv "/Users/itsfadnis/.nvm/versions/io.js/v3.3.1/bin/iojs"    "/Users/itsfadnis/.nvm/versions/io.js/v3.3.1/bin/npm" "install" "-g"     "ember-cli" "--no-optional"
    npm ERR! node v3.3.1
    npm ERR! npm  v2.14.3
    npm ERR! code ETIMEDOUT
    npm ERR! errno ETIMEDOUT
    npm ERR! syscall connect

    npm ERR! network connect ETIMEDOUT 103.245.222.162:80
    npm ERR! network This is most likely not a problem with npm itself
    npm ERR! network and is related to network connectivity.
    npm ERR! network In most cases you are behind a proxy or have bad network settings.
    npm ERR! network
    npm ERR! network If you are behind a proxy, please make sure that the
    npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/itsfadnis/npm-debug.log

I have tried the following and none have worked:

 1. Reinstall node and npm
 2. `npm set registry http://registry.npmjs.org`
 3. Tried with different versions of node - v0.12.8, iojs-v3.3.1, v4.4.2, v5.0
 4. Without optional dependencies `npm install -g ember-cli`
 5. As administrator `sudo npm install -g ember-cli`

Network connection is absolutely fine and I'm not behind a proxy.
Any help on this would be appreciated. Thanks.

**Comment by stefanpenner** [comment]
> Network connection is absolutely fine and I'm not behind a proxy.
> npm ERR! network connect ETIMEDOUT 103.245.222.162:80

I suspect something is funky with you connection to the registry.

> npm  v2.14.3

I would consider upgrading to a more recent NPM (something like v3.5.1 or greater).

> Any help on this would be appreciated. Thanks.

Unfortunately, I believe this is an issue between your npm client and the registry. You can try upgrading it as recommended above, but this is unfortunately not really in our control

**Comment by jsArgus** [comment]
Had the exact same error (npm was v3.5.3). Finally solved it:
* Uninstalled npm: `npm uninstall npm -g`
* Reinstalled node.js using the installer. (npm now is on v3.3.12)

Then `npm install -g ember-cli` was running fine. Note that before this I could install other npm packages without a problem. 
I then managed to reintroduce the error by updating npm `npm update -g`. Going trough the uninstall / reinstall routine once more fixed it again.
Still there is some weird stuff going on, perhaps by using the node.js installer and homebrew at the same time? 
```
$ ember -v
version: 2.3.0-beta.1
node: 5.5.0
npm: 2.14.10
os: darwin x64
$ npm -v
3.3.12
```
Replying here because I only have this problem with the ember-cli npm package.
