### ISSUE TITLE
Ember CLI an error when dealing with globally installed modules

### ISSUE THREAD

**Issue by vadossi-rmn** [ember-cli/ember-cli#5193]
In an attempt to share node modules across projects, I created a `.npmrc` that looks like this:

```
prefix = path/to/shared/modules/folder
global = true
```

However, when I tried to run Ember CLI (after successfully performing `npm install` for the app install, with modules going to the prefix folder), it complains:

```
node_modules appears empty, you may need to run `npm install`
```

Not sure how to address this (whether to introduce an option to relax the error or something else) -- but at least wanted to bring it to everyone's attention.

**Comment by rwjblue** [comment]
We use https://github.com/ember-cli/node-modules-path to determine what the `node_modules` path is, and if it is not present we throw the error you pasted above. The error is generally pretty helpful, because it lets folks know that they may have forgotten to run `npm install` after initially cloning the repo.

I noticed from the comment [here](https://github.com/ember-cli/node-modules-path/blob/master/index.js#L70) that setting `EMBER_NODE_PATH` environment variable will force that path to be used which should provide you with a workable solution (I think).

I would not be opposed if someone wanted to try to add the functionality needed to detect an `.npmrc` as the one you have specified above in node-modules-path lib...

**Comment by stefanpenner** [comment]
> I would not be opposed if someone wanted to try to add the functionality needed to detect an .npmrc as the one you have specified above in node-modules-path lib...

I would love for us to support this

**Comment by Turbo87** [comment]
closing in favor of https://github.com/ember-cli/node-modules-path/pull/3
