### ISSUE TITLE
Live-reload host option not working

### ISSUE THREAD

**Issue by ryanjm** [ember-cli/ember-cli#5287]
When I run `ember server` I'm getting the following in my console:

> [Report Only] Refused to load the script 'http://myember:49155/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' localhost:49155 0.0.0.0:49155".
> `ember-cli-live-reload.js:6`
> [Report Only] Refused to connect to 'ws://myember:49155/livereload' because it violates the following Content Security Policy directive: "connect-src 'self' www.google-analytics.com ws://localhost:49155 ws://0.0.0.0:49155 http://myember:4200/csp-report".
> `livereload.js?snipver=1:74`

Because "localhost:49155 0.0.0.0:49155" and "ws://localhost:49155 ws://0.0.0.0:49155" show up in the lists, I'm assuming that the live reload host option is not being used correctly since that looks like the default options for live reload.

My `.ember-cli` looks like this:

```js
{
  'disableAnalytics': false,
  'host': 'myember',
  'liveReloadHost': 'myember',
  'proxy': 'http://mydevbox.dev'
}
```

I get the same results when I pass them as options into `ember server`.

Are there other steps I'm missing to make those two errors to go away or is it a bug in the loading of live-reload?

Live reloading is working properly (change file and the browser reloads), but I think this is might be interfering with some of my other code and I'd like to remove all errors from the console if I can.

| lib | version |
|----|---------|
| Ember      | 2.2.0 |
| Ember Data | 2.2.1 |
| jQuery | 1.11.3 |

Potentially related issue: #1080.

**Comment by stefanpenner** [comment]
> [Report Only] Refused to load the script 'http://myember:49155/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' localhost:49155 0.0.0.0:49155".
> ember-cli-live-reload.js:6
> [Report Only] Refused to connect to 'ws://myember:49155/livereload' because it violates the following Content Security Policy directive: "connect-src 'self' www.google-analytics.com ws://localhost:49155 ws://0.0.0.0:49155 http://myember:4200/csp-report".
> livereload.js?snipver=1:74

These are report-only, they do not affect usage in development. Merely letting you know, those scripts are violating the CSP outlined.. If you want them to go away you have 2 choices

1. Read https://github.com/rwjblue/ember-cli-content-security-policy and follow the instructions on how to add those to the CSP configuration
2. remove ember-cli-content-security-policy from your package.json

––––

As master no longer includes CSP by default (due to the pretty bad user experience) if you do not feel CSP is important for your site/development, then feel free to just remove the add-on.

**Comment by ryanjm** [comment]
Thanks @stefanpenner
