### ISSUE TITLE
Refactor away from 'npm install package-name' for 'ember install'.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#5295]
Based on https://docs.npmjs.com/how-npm-works/npm3-nondet, we should completely avoid using 'npm install package-name' due to non-determinism. 

We should update 'ember install' to update package.json, rm -rf node_modules, and npm install. If we do not do this the resulting local node_modules will not match what other team members will get or what CI will use. 

This whole situation sucks massively.

**Comment by kellyselden** [comment]
ouch.

Well we already have code that can modify package.json dependencies the same way npm does alphabetically (addon `addPackageToX`)

but ouch the network traffic and time (on windows). Hopefully the npm cache will help us out.

**Comment by rwjblue** [comment]
Yes, definitely sucks. Sadly, I think the that non-deterministic builds are the worse of two evils here.

**Comment by stefanpenner** [comment]
The proposal sounds a it much. Anyways please take the rfc route, this needs to be fleshed out

**Comment by rwjblue** [comment]
> The proposal sounds a bit much.

Heh. Sounds more like npm is a bit lacking to me :smiling_imp:.

**Comment by gabrielgrant** [comment]
@rwjblue I'm not sure I follow why the non-determinism of the node_modules dir is a problem? [The NPM docs are pretty explicit that this non-determinism in directory structure should have no effect on the functioning of the app](https://docs.npmjs.com/how-npm-works/npm3-nondet#do-different-dependency-tree-structures-affect-my-app)

**Comment by stefanpenner** [comment]
I am also unclear.

**Comment by CHIEFnChowCombo** [comment]
This is a non-issue.  The article discusses the non-determinism only to point out that it's *not* a concern.

> Do different dependency tree structures affect my app?

> No! Even though the trees are different, both sufficiently install and point all your dependencies at all their dependencies, and so on, down the tree. You still have everything you need, it just happens to be in a different configuration.

Basically, what they're trying to say is that non-determinism is a *desired outcome*.  Each machine will be able to optimize based on the existing state of the modules it has installed, every time an npm operation is performed.  It's all an abstraction, because the consuming application will run the same way, *regardless* of the order.

There article is there to show how to recreate a single, consistent `node_modules` directory "*should you want to do that*", which would be rare.  

Typically, this would only be a concern if there is a 3rd party application running that is dependent on a very specific structure of your app's node_modules folder, and can't use the built-in module resolver that is used whenever you `require` or `import` something.

**Comment by stefanpenner** [comment]
we have taken time to make sure we follow the node resolution algo, when interacting with node_modules. From my understanding, that should allow us to safely use the new layout.

I do believe they should make the topology deterministic...  but we should also be sure to avoid related issues.

**Comment by CHIEFnChowCombo** [comment]
> Heh. Sounds more like npm is a bit lacking to me :smiling_imp:.

and 

> I do believe they should make the topology deterministic... but we should also be sure to avoid related issues.

This is all a direct result of the pure volume of npm modules that have proliferated. I've actually sat in on a few TCS meetins where this was discussed. @ebryn was chatting with me a few months ago about "the stew", (or whatever he called it), and this non-determinism is the attempt to mitigate some of side-effects of that.

The v2 resolver created a lot of crazy trees, and you would run into issues on certain platforms due to limitation on character length for path names.

> we have taken time to make sure we follow the node resolution algo

I've been spending the last week or so digging through the issue history of ember-cli, and the direction things are moving, and I think we're on the right course. 

From what I'm seeing, the only remaining issue to solve in order to be fully on-board with the npm compatibility is resolving side-effects from operations that `ember install addon` perform, that `npm install some-ember-addon` don't. (mentioned here: https://github.com/ember-cli/ember-cli/issues/4616, and from @rwjblue's commit here: [rwjblue/ember-cli-pretender@33e5794](https://github.com/rwjblue/ember-cli-pretender/commit/33e5794f5aef545f00995435d08cb471e79a3bae))

I have some thoughts brewing on that, and the involve utilizing the native `npm postinstall` from the `install addon` task, but I plan to take the RFC route when I've fully thought it through.
