### ISSUE TITLE
specifying the input HTML document

### ISSUE THREAD

**Issue by skaterdav85** [ember-cli/ember-cli#5381]
When you run `ember build`, is there a way to change the input HTML document from app/index.html to something else?

**Comment by stefanpenner** [comment]
As per our contributing.md questions are best asked on discourse or stackoverflow. Unfortunately due to limited time, and github being pretty poor at Q/A compared to a specialized knowledge base tool like stack overflow, we can't handle these times of requests here.

Feel free to cross link, if an issue is discovered  please open a new issue, or if a feature is requested please go through the rfc process.
