### ISSUE TITLE
`0%` changed to `0` when minifying css.

### ISSUE THREAD

**Issue by altrim** [ember-cli/ember-cli#5440]
You can see the example here https://jsbin.com/tecoju/edit?html,css,output . 
I am using flex box and I have a rule where I set `height:0%` but when minified in production it gets changed to `height:0` and that breaks the layout. To verify this just remove `%` in `height` from `.col3{...}` in the jsbin example and see how it breaks the layout.

I am using sass in the project btw.

- OS: Mac OS X 10.11.3
- npm version: 3.7
- node version: 5.5.0
- ember version: 2.3.0-beta.2

**Comment by stefanpenner** [comment]
That's strange. You should likely open the issue on the cssminification lib, but we can track the meta issue here

**Comment by KrisOlszewski** [comment]
I think the problem is in your CSS. The goal of minification is to remove any non-essential code. In CSS value of 0 is simply 0, there is no need for units.

I think the bug you're experiencing is a result of using flexbox and floats in your grid. You should pick one technique and not mix the two. See here: https://jsbin.com/jojukafido/edit?html,css,output

**Comment by altrim** [comment]
@KrisOlszewski In the issue I have I was not using float that was just in the example I provided. Even without the float I had the issue but still I managed to fix it in the css based on your example. Thanks a lot for the help. 

I guess I can close this issue now since it looks like it's not the problem in the cssminification lib.
