### ISSUE TITLE
problem with @import in css files

### ISSUE THREAD

**Issue by mynoheart** [ember-cli/ember-cli#5522]
ember-cli 2.3.0
ArchLinux 4.4.1-2-ARCH

if in css files used `@import` then:
- in dev mode after change css file which imported to `app.css` live reload request it and gets 404 response, after file load correctly, but browser then styles not apply. Resolve problem full reload page.
- in prod mode all css files minification and placed to `/assets/` folder, but to `index.html` added only `app.css` and not included other files to result.

**Comment by Turbo87** [comment]
do you have a public repo somewhere to reproduce this bug?

**Comment by mynoheart** [comment]
Hello.
Unfortunately no.
Now i don't have possibility create example.

**Comment by Turbo87** [comment]
I guess without being able to reproduce this there is not much we can do about your problem...

**Comment by mynoheart** [comment]
Ok. I still will try create example and reproduce this problem in minimal app.

**Comment by mynoheart** [comment]
For production case: this my fault (i not write correct `@import` directive, not ended semicolon).

For dev problem actual (example repo https://github.com/mynoheart/ember-cli-example-import-css-problem). Problem reproduce only in Chrome browser. In Firefox work correctly. This may be due with live reload first time receive 404 response.
For reproduce need run `ember server`. Open in Chrome and change file `app/styles/div1/div1.css` and styles reseting.

**Comment by topaxi** [comment]
I just started a minimal app with plain CSS. I noticed 404 errors in my console when I save my `app.css` which imports `fonts.css` in the same folder.

`app/styles/app.css`
`app/styles/fonts.css`

Saving `app/styles/app.css` results in a request to `http://localhost:4200/fonts.css`.

Repo here: https://github.com/topaxi/open-pizza-creator/tree/e0a7948

Styles which change get applied though.
Sometimes styles I remove in a imported file won't get unloaded until I resave `app.css` or reload the page.

**Comment by BrianSipple** [comment]
I’ve also just discovered the same behavior as @topaxi did with a plain CSS build — but in this case, while serving styles from an addon dummy app [add-on dummy app](https://github.com/BrianSipple/ember-a11y-testing/tree/ff2610ef2661ca243ec383d411402128eed59e39/tests/dummy/app).
 
Importing stylesheets goes off without a hitch on the initial build, but then when I make a change to one of the imported files and save it, livereload fails when requesting the new file -- even though the new styles are still applied.

For example, during an update of `tests/dummy/app/styles/_patterns.css`, which `tests/dummy/app/styles/app.css` imports at the top with `@import '_patterns.css';`, this is the error in Chrome:
 
<img width="763" alt="screen shot 2016-06-21 at 7 39 42 pm" src="https://cloud.githubusercontent.com/assets/5483853/16253265/f6df5372-37e9-11e6-80c1-d594bb97b3b9.png">

And in Firefox...
<img width="695" alt="screen shot 2016-06-21 at 7 55 06 pm" src="https://cloud.githubusercontent.com/assets/5483853/16253296/3a5dc84a-37ea-11e6-884f-90f1145d0c41.png">

It looks like livereload is trying to request the file directly instead of waiting for it to be imported into `app.css` and just making one request from there. The styles build correctly, though, because that process does still occur right after.
Notice the different root for the 404 and then the 200:

<img width="1181" alt="screen shot 2016-06-21 at 8 05 53 pm" src="https://cloud.githubusercontent.com/assets/5483853/16253475/afae3520-37eb-11e6-9b71-434b179da900.png">

<img width="1181" alt="screen shot 2016-06-21 at 8 05 31 pm" src="https://cloud.githubusercontent.com/assets/5483853/16253478/b284afb8-37eb-11e6-82bc-dbcfd7ecaa21.png">

**Comment by locks** [comment]
I couldn't reproduce the problem in the latest versions. Please re-open if you encounter this again!
