### ISSUE TITLE
Convert into a Yeoman generator

### ISSUE THREAD

**Issue by leo** [ember-cli/ember-cli#5692]
I'm not sure why this hasn't been done yet, but if you ask me, we should convert the whole CLI into a simple [Yeoman](http://yeoman.io) generator.

![yeoman](https://cloud.githubusercontent.com/assets/6170607/14081778/9c4e9064-f50c-11e5-9d42-69167b5b258a.png)

The biggest reasons:

- We could use all of Yeoman's methods to [generate blueprints](http://yeoman.io/authoring/file-system.html) and execute [other actions](http://yeoman.io/authoring/user-interactions.html) (which would allow us to remove a lot of our code)
- The current best practise when developing Ember apps is to use ember-cli, isn't it? Then making ember-cli a simple Yeoman generator instead of a whole CLI seems like a great step into the direction of making ember-cli an actual part of Ember. Currently, it's a really huge and completely separate project. In my opinion, this will also make the whole process of getting started with Ember a lot easier for newbies (I've also heard that the docs might be merged later).
- As far as I know, Yeoman does a [really great job](http://yeoman.io/authoring/integrating-yeoman.html) when it comes to integrating those generators into different environments like editors and IDEs (not just the command line).

All of this stuff seems to be a great way to both strip many lines of code from the project and also make it less "separate, big project" and more "just a boilerplate for Ember". Since Yeoman will also handle a lot of the main logic, we could **focus on building great blueprints**.

To accomplish this, we would have to take over [generator-ember](https://www.npmjs.com/package/generator-ember) and either start at `1.0.0` or `2.4.3` (the latter seems like a better choice to me).

## What we need to keep in mind

Yeoman doesn't seem to support "destroying" generated routes/models/etc. out of the box. So we would either have to do something like `yo ember:g <name>` and `yo ember:d model <name>` or completely remove the feature of "destroying" stuff in favour of this syntax:

```
yo ember:model <name>
```

Since all of us are using some kind of versioning on their code, the "destroy" subcommand seems pretty unnecessary to me anyway. I mean, it's more than easy to just revert back to a certain state in history or discard the changes in certain files before committing.

-

It's just a really small thing and shouldn't be an argument for this choice, but I'll tell you anyway: "Destroying" generated routes/models/etc. also doesn't bring back the ".gitkeep" files within the destination directories, while reverting back to a certain state in the commit history and discarding the changes before committing does. So technically, those empty directories will be lost after making a commit. But yeah. As I said, it's not that important!

### Addons

As far as I know, @rwjblue decided that `ember-cli-*` addons will extend the CLI and `ember-*` ones only Ember itself.

So my personal recommendation would be to use the `ember-<addon-name>` syntax for ALL addons that will extend Ember or its generator. This would have the following advantage: An addon wouldn't have to change its name if it wants to start extending the generator instead of just Ember itself (and also the other way around).

Here's an example: The addon `ember-hello" adds some functionality to Ember. Now it also wants to add a blueprint to the generator (extend the generator). What now? Right! It would technically have to change its name to "ember-cli-hello". However, this won't be fitting either, since it now extends both Ember and its command line interface.

See the problem here? We could solve this!

-

Let me know what you think about making this whole project a Yeoman generator!

**Comment by Turbo87** [comment]
are you aware that `ember-cli` is capable of doing **much** more than just generating blueprints?! I don't think stripping away all that functionality and replacing it with yeoman will have any advantages...

**Comment by stefanpenner** [comment]
These sorts of topics are best raised as RFCs, but transitioning to another tech just "because" is unlikely to gain traction. Before proposing this as an RFC be sure to dig into the exact differences and transition required, as the devil is in the details. (And why we choose our own path, rather then yeoman at the starT)

**Comment by nathanhammond** [comment]
Hey @leo! We (@trabus) have done a lot of work recently to extract blueprints themselves outside of ember-cli core. As a tool ember-cli handles everything from builds to http-proxies to testing to linting and more. We agree that we still have some work to do on making blueprints more flexible and are actively investigating how generation itself can be extended but we're early in the process.

We're pretty comfortable with status quo when it comes to our generator story and would need a very compelling argument to move. I'm also not sure how adopting Yeoman (as a separate tool) is different in consequence from having ember-cli (a separate tool). We also have tremendous leverage in it being a tool that we control, allowing us to set our own direction and timelines.

Regarding one of your concerns, addon naming isn't something that we particularly have a convention around. Any addon is able to register blueprints. You can name an addon "liquid-fire" and it will do the right thing as long as package.json is configured correctly. The conventions exist only as a hint to addon consumers.

I'm closing this since it wouldn't be addressed here (instead ember-cli/rfcs). I consider it incredibly unlikely that we would choose to adopt Yeoman, but you may open an RFC (with significantly more information than just this) which will trigger a formal discussion after which a decision will be made. :)
