### ISSUE TITLE
helper generator creates wrong format of helper code

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli#5771]
Ember cli 2.4.3:

Documentation at [http://emberjs.com/api/classes/Ember.Helper.html] states that helper should look like this:
```
export default Ember.Helper.extend({
  compute(params, hash) {
    let cents = params[0];
    let currency = hash.currency;
    return `${currency}${cents * 0.01}`;
  }
});
```

`ember g helper add-s` instead generates
```
export function addS(params/*, hash*/) {
  return params;
}

export default Ember.Helper.helper(addS);
```

**Comment by rwjblue** [comment]
Both are correct :smiley_cat:.

Note that the API doc says this:

> Helpers defined using a class must provide a compute function.

This means, that if you **do** use the `Ember.Helper.extend` syntax, you must provide your own `compute` function. The `Ember.Helper.helper` method is just a convenient shorthand for `Ember.Helper.extend`. See http://emberjs.com/api/classes/Ember.Helper.html#method_helper for a description of what our generator uses.

I do, however, think we should mention both versions (`.extend` and `.helper`) in the main `Ember.Helper` intro docs.   I would welcome a PR to update https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/helper.js#L9 to include examples of both.

---

Since this isn't a bug, I'm going to close this issue...

**Comment by BryanCrotaz** [comment]
> In many cases, the ceremony of a full Ember.Helper class is not required. The helper method create pure-function helpers without instances.

Is the pure-function helper better in any way, e.g. faster?

**Comment by rwjblue** [comment]
Yes, `Ember.Helper.helper` has slightly less overhead (because we can make some additional optimizations internally to avoid allocating extra objects), but I doubt that difference would be measurable in an application.

**Comment by rwjblue** [comment]
I also think it is less total bytes / characters :)

**Comment by BryanCrotaz** [comment]
So to summarise generator is doing it the best way but documentation needs
an update.

On 10 April 2016 at 17:58, Robert Jackson <notifications@github.com> wrote:

> I also think it is less total bytes / characters :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/5771#issuecomment-208015385>
>



-- 
Bryan Crotaz
Managing Director
Silver Curve

**Comment by rwjblue** [comment]
Yep. Would love someone to update the docs where I linked to show both versions.

**Comment by BryanCrotaz** [comment]
PR #13292

On 10 April 2016 at 18:11, Robert Jackson <notifications@github.com> wrote:

> Yep. Would love someone to update the docs where I linked to show both
> versions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/5771#issuecomment-208018354>
>



-- 
Bryan Crotaz
Managing Director
Silver Curve
