### ISSUE TITLE
using Ember --proxy behind corporate firewall

### ISSUE THREAD

**Issue by ankeshdave** [ember-cli/ember-cli#6032]
I am developing an Emberjs Application behind corporate firewall (NTML Proxy). I have configured proxy settings (using **Cntlm**) for all devtools.

Things working behind firewall through Cntlm (http://127.0.0.1:3128)

-     Git
-     Npm
-     Bower

But, when ever i proxy request to my cloud api (deployed on Azure) using
```
ember server --proxy https://my-api-on-cloud.azurewebsites.net --ssl
```
I am unable to do api request from the served website. If i connect the system to my phone (Wifi), remove proxy config. Every thing runs fine.
how can i forward all request from my website to my api throught my proxy (http://127.0.0.1)

Output from ember version --verbose:
```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.1.0
v8: 5.0.71.35
uv: 1.9.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2h
os: win32 x64
```

**Comment by nathanhammond** [comment]
@ankeshdave This likely has something to do with how we're configuring the npm package `http-proxy`. [Our code for the proxy is here.](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/proxy-server/index.js) Is this something you can dig into since you have the perfect test environment? We're happy to help you land a PR to make sure we properly support Cntlm. 😄

**Comment by ankeshdave** [comment]
@nathanhammond  I have asked a question on the `http-proxy` repo on options , I'll connect with you after getting a response, I personally can't figure out how to specify N/W proxy or make the middleware pick up system proxy (Directly or through Env variable).

**Comment by stefanpenner** [comment]
this appears to have gone stale. W
