### ISSUE TITLE
2 files 1 hash

### ISSUE THREAD

**Issue by floriandotorg** [ember-cli/ember-cli#6044]
Hi Ember Team :-)

thanks for your amazing work.

I've encountered a bug with fingerprints. It's possible to create two different files with same fingerprint.
This can cause bugs since the cache is not busted.
This is especially bad because SRI checks will fail and the whole applications refuses to load.

I attached an example project: [example.zip](https://github.com/ember-cli/ember-cli/files/350194/example.zip)

Steps to reproduce:
```
ember build --environment=production

mv dist dist_a
mv ember-cli-build.js ember-cli-build.js.a
mv ember-cli-build.js.b ember-cli-build.js

ember build --environment=production

diff dist_a/assets/bla-c8cb2bedf4cb9bffa9ebc32e6fde0f0b.css dist/assets/bla-c8cb2bedf4cb9bffa9ebc32e6fde0f0b.css
```

It seems like the asset rewriting does not affect the fingerprint.

---

Output from ember version --verbose:
```
ember-cli: 2.6.2
http_parser: 2.7.0
node: 6.2.0
v8: 5.0.71.47
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by nathanhammond** [comment]
You're running into this issue: https://github.com/rickharrison/broccoli-asset-rev/issues/29

The correct solution is to build everything as a dependency tree and work from the leaf to the root nodes but that has a few gotchas (circular dependencies will ruin your day) and is a bit of work. Let me know if you'd like guidance or help taking it on. Nobody has decided to take it on since it was first reported as an issue in 2014. 😞

I'm closing this as it isn't exactly an Ember CLI issue. Thank you for taking the time to report it!
