### ISSUE TITLE
`ember new` errors if git is not installed

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-cli#6117]
According to a [bug report on the Guides repository](https://github.com/emberjs/guides/issues/1579#issuecomment-235924338), Ember CLI is erroring and reverting the application generation if the user does not have `git` in the system.

Platform: Windows

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/git-init.js#L42-L48 is intended to prevent issues here

**Comment by kellyselden** [comment]
If anyone wants to dig into this, comment out these lines
https://github.com/ember-cli/ember-cli/blob/master/dev/windows/install.ps1#L11-L15
then `cd dev/windows` and `vagrant up`

p.s. you need vagrant and virtualbox

**Comment by NullVoxPopuli** [comment]
I did (on linux)
```
cd dev/windows
vagrant up
```
![image](https://user-images.githubusercontent.com/199018/52522358-49496d00-2c52-11e9-8690-536a6f18bdd6.png)

then, in windows powershell,
```
npm install -g ember-cli
ember new my-app
```
it worked, git must be installed (I don't know how to `which git` in powershell

let's uninstall git.

 - start / windows key
 - search for remove
 - select add or remove programs
 - select Git version 2.20.1
   - follow prompts
   - git was successfully removed! 
 - back to powershell:
   - delete my-app `rm my-app`
   - re-run `ember new my-app`

hmmm... that worked still. so... let's try a new shell, maybe git was somehow cached
maybe first let's verify that git is uninstalled:
![image](https://user-images.githubusercontent.com/199018/52522411-1fdd1100-2c53-11e9-9f95-69e171bdf51a.png)
cool.

run `ember new some-app`

turns out, ember new works if git is not installed. :)

![image](https://user-images.githubusercontent.com/199018/52522434-63377f80-2c53-11e9-87fb-504783745ed3.png)

So, if this is still an issue, we'd need more information. 
 - windows version
 - npm version
 - etc

**Comment by locks** [comment]
Let us called fixed 😁
