### ISSUE TITLE
Make blueprints use destructuring

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli#6146]
I was talking with @alexlafroscia about blueprints generating something like:

```js
import Ember from 'ember';
const { Component } = Ember;
```

This way you don't use `Ember.Component` directly. 

The same would be true for `Ember.Route`, `Ember.Controller`, etc.

We wanted to get your thoughts on this proposal and see if you would be open to some PRs to implement it, if you like the idea.

Please let me know your thoughts.

**Comment by alexlafroscia** [comment]
I personally like this, and it's been the "recommended" approach for a while now.

I do know that a lot of the modules (like `Component`) have a place we can import the class directly from.  Maybe we should just straight to that?  I think it's something like

```js
import Component from 'ember-component';
```

The destructuring was always recommended to make the transition to that syntax easier, but maybe we're in a place where we can just go right to it.  Get people doing the "right thing" now so that Svelte builds can be benefitted from with less application changes.

**Comment by alexlafroscia** [comment]
Seems like #6114 is closely related

**Comment by rwwagner90** [comment]
Ping @toddlittle

**Comment by rwwagner90** [comment]
@alexlafroscia I would be fine with importing directly, versus destructuring. Is that really importable or just from ember-cli-shims though?

**Comment by alexlafroscia** [comment]
It might be from a shim repo; all I know is that I've seen that in an app before, but it could (and likely is) an addon that's enabling that right now.

**Comment by Turbo87** [comment]
This is indeed exactly what #6114  is about and the comments on this PR also apply to this issue.

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/ember-cli/pull/6114#issuecomment-237310075
