### ISSUE TITLE
Cannot seem to get Ember CLI to Babelify browserified npm dependency

### ISSUE THREAD

**Issue by sohara** [ember-cli/ember-cli#6170]
We are using Ember CLI along with Ember Browserify to manage a number of our client-side dependencies. In one of our new packages the author elected to write some modules using ES2015 features/syntax. The package is also used server-side in a Node 4.x environment and this works without issue.

I realize this issue maybe be more appropriate to the ember-browserify project but I'm opening it here because I understand that ember-cli seeks to provide a story for managing an Ember project's dependencies in a sane and comprehensive way.

I have a repro project here: https://github.com/sohara/halp-markdown

Basically I added a dependency that exposes a function that uses `const` which should be transpiled if using the `ES2015` Babel preset. The const remains in the source if you inspect the build `vendor.js` file. Works fine in current Chrome. Here's source of the npm packages's entry file:
```js
'use strict';

function parse(str) {
  const newString = '<p>' + str + '</p>';
  return newString;
}

module.exports = {
  parse: parse
};
```

This issue in ember browserify: https://github.com/ef4/ember-browserify/issues/60 was closed but I don't think it was ever really addressed. Let me know if it's better I open this in the ember browserify project.

cc @ef4 

### Output from ember version --verbose:
```
ember-cli: 2.7.0
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: darwin x64
```

**Comment by stefanpenner** [comment]
cc @nathanhammond

**Comment by nathanhammond** [comment]
@sohara Without direct review of the code in question my intuition on this is that ember-browserify is adding its asset into the build external to the Ember CLI step which does our rewriting of `const` and `let`. In that case `ember-browserify` should be the addon responsible for doing something reasonable for transpilation of the Node module.

I'd call this an ember-browserify issue because if this were inserted into just the right spot in the Ember CLI build process it would "just work." Note: Ember CLI may not actually expose a place to insert ember-browserify assets into the build at just the right spot and that is not something we intend to change at this exact moment. We are instead using reports like yours to inform our future plans for the build process: https://github.com/ember-cli/rfcs/issues/64

I'm closing this as it's not something we're going to take action on at this moment, but I really appreciate you taking to time to create a clean implementation and document the problem you're trying to solve which makes it easy for me to review.

I'd reopen this issue against ember-browserify and look into making that addon support Babel transpilation.

**Comment by sohara** [comment]
Thanks @nathanhammond. I'll open this against ember-browserify.

**Comment by nucleartide** [comment]
I ran into this exact problem today. Don't want to knock ember-browserify, but IMO it makes a lot more sense to me to just run browserify via the command line. So I wrote a shell script to wrap my app's node modules: https://gist.github.com/nucleartide/12d9fe7d7a7ce8477ddaaba0b27ce481

This also fixes the problems with ember-browserify [not playing nice with addons][1]. Hopefully this helps!

[1]: https://github.com/ef4/ember-browserify#using-ember-browserify-in-addons

**Comment by sohara** [comment]
@nucleartide Based on your gist, I don't understand your use case. We use dependencies like lodash via ember-browserify without issue (their dist builds are es5). The only encountered this issue when we tried to import and npm module that had new ES syntax/features.

**Comment by nucleartide** [comment]
@sohara Yes, perhaps Lodash is a bad example. I'm using the script on a node module ([joi][1]) that uses ES6 classes in its codebase as well as in its dependencies. Of course, if the module provides a "dist" build that is all ES5, then you don't need to bother.

[1]: https://github.com/hapijs/joi

**Comment by sohara** [comment]
@nucleartide I see. Thanks. We can certainly manually transpile the code but we're hoping for a solution that hooks in more seamlessly with our build chain.
