### ISSUE TITLE
rootURL included in asset path when fingerprint.prepend is present

### ISSUE THREAD

**Issue by ivanvanderbyl** [ember-cli/ember-cli#6212]
Output from ember version --verbose:
```
ember-cli: 2.8.0-beta.3
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

NOTE: Also confirmed on `2.7.0`

My app uses a `rootURL` of `/app/` when deployed in production to `mydomain.com/app/`, however we deploy assets to a CDN `https://subdomain.cloudfront.net/`. When building the app the assets are correctly stored in `/dist/assets`, however the asset URLs in `index.html` incorrectly contain `/app/`:

```html
<script src="https://subdomain.cloudfront.net/app/assets/vendor-77407fbfe79fa9db1086f7042f314d3e.js"></script>
<script src="https://subdomain.cloudfront.net/app/assets/dummy-app-5391163f5b71cffb8314a50026f5659b.js"></script>
```

According to the release notes for the baseURL/rootURL change: 
> Note: the rootURL is not present. This is intentional as rootURL exists only to provide information to Ember's Router about where the application is served from

Expected output:

```html
<script src="https://subdomain.cloudfront.net/assets/vendor-77407fbfe79fa9db1086f7042f314d3e.js"></script>
<script src="https://subdomain.cloudfront.net/assets/dummy-app-5391163f5b71cffb8314a50026f5659b.js"></script>
```

My `ember-cli-build.js`:

```js
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    fingerprint: {
      prepend: 'https://subdomain.cloudfront.net/'
    }
  });

  return app.toTree();
};
```

`config/environment.js`:

```js
...
  if (environment === 'production') {
    ENV.rootURL = '/app/';
  }
...
```

This is obviously the output from a fresh ember app I created to replicate the issue, I also tested building it in docker to ensure my local machine wasn't tainting the results.

**Comment by nathanhammond** [comment]
Ugh, I tested this. Gimme a bit to give you an answer on what the solution will be.

**Comment by ivanvanderbyl** [comment]
Thanks @nathanhammond, I've been digging through ember-cli and ember-asset-rev all morning trying to figure out how this works and find some less than obvious thing I'm doing wrong.

Let me know if you want a reproduction repo.

**Comment by rwjblue** [comment]
Had a long chat with @nathanhammond about this in #dev-ember-cli, and I am sure he will chime in with better details.  In the meantime, you can work around the issue you are having by:

* Specify `rootURL` of `/` for production.
* Add a `routerRootURL` property to `config/environment.js` with a value of `/app/`
* Change `app/router.js` to use `rootURL: config.routerRootURL` instead of `rootURL: config.rootURL`.

**Comment by nathanhammond** [comment]
nathanhammond [6:56 PM]
The situation is that we replace `rootURL` by default in `index.html` ... we want that to be the default behavior as it's required for things to work with `ember serve`.

[6:57]  
> Note: the rootURL is not present. This is intentional as rootURL exists only to provide information to Ember's Router about where the application is served from. - http://emberjs.com/blog/2016/04/28/baseURL.html#toc_how-to-use-a-cdn


[6:59]  
That quote was based upon direct testing of the behavior, and yet it appears to have changed.

[6:59]  
Or I just can't do anything right, which is also possible.

rwjblue [6:59 PM]  
haha

[6:59]  
I doubt it

[7:00]
assuming you always use a `rootURL` of `/foo/`, when you `ember build` `/foo/assets/vendor.js` would be referenced

[7:00]  
are you saying that is not expected?

nathanhammond [7:00 PM]  
That is fully expected.

rwjblue [7:00 PM]  
ok?

[7:00]  
so where is the issue?

[7:01]  
that is what the OP is reporting, and that seems fine to me...

nathanhammond [7:01 PM]  
So the problem is how do we support a CDN?

rwjblue [7:01 PM]  
they are saying that this is the output:

```
<script src="https://subdomain.cloudfront.net/app/assets/vendor-77407fbfe79fa9db1086f7042f314d3e.js"></script>
<script src="https://subdomain.cloudfront.net/app/assets/dummy-app-5391163f5b71cffb8314a50026f5659b.js"></script>
```

nathanhammond [7:01 PM]  
Force the CDN to have to same asset paths?

[7:01]  
prepended with `rootURL`?

[7:02]  
Note that the assets appear in the built output at `/dist/assets` with no hint of `rootURL`. (edited)

rwjblue [7:02 PM]
before the asset-rev prepend runs the output would be:

```
<script src="/app/assets/vendor-77407fbfe79fa9db1086f7042f314d3e.js"></script>
<script src="/app/assets/dummy-app-5391163f5b71cffb8314a50026f5659b.js"></script>
```

nathanhammond [7:02 PM]  
Correct.

rwjblue [7:02 PM]  
prepend replaces `/` with `<prepend value>/`

nathanhammond [7:03 PM]  
I'm not surprised by the behavior. It seems like it's doing the right thing.

rwjblue [7:03 PM]  
"no hint of rootURL" isn't right at all

nathanhammond [7:04 PM]  
I mean that it's not `/dist/app/assets/vendor-asdfasdf.js`

[7:04]  
It's instead found in the build output at `/dist/assets/vendor-asdfasdf.js`

rwjblue [7:04 PM]  
right

[7:04]  
ripe for uploading to your previously stated location :stuck_out_tongue_winking_eye:

[7:05]  
the work around in this case is easy

[7:05]  
`rootURL` of `/`, and change `app/router.js` to not use that property.  Instead provide a different value.

[7:06]  
we use `rootURL` to conflate two things

[7:06]  
* "the place we serve shit at"
* "the URL that we are telling the router that `/` lives at at runtime"

[7:07]
in the 90% case, this is not an issue

[7:07]  
folks just serve the app from where they say it is

[7:07]  
it also isn't horrible to have subfolders on the CDN (edited)

nathanhammond [7:08 PM]  
Confirm. That conflation is intentional as `baseURL` and having multiple concepts was making peoples' brains explode.

rwjblue [7:08 PM]  
confirm

[7:08]  
so I don't think we "fix" this per-se

[7:08]  
because I don't think its broken

[7:08]  
though we need to solve the confusion via docs/guides (edited)

nathanhammond [7:08 PM]  
And correct the blog post.

rwjblue [7:09 PM]  
yeah, though I think that its only wrong if you read it sideways and squint

[7:09]  
i.e. I could read it and infer the actual behavior or infer the behavior that the OP thought

nathanhammond [7:09 PM]  
Yeah, but I meant what the OP thought.

[7:09]  
:stuck_out_tongue:

rwjblue [7:10 PM]  
hehe, ok

[7:10]  
seems good to clarify

nathanhammond [7:10 PM]  
I'll clean that section up a bit.

**Comment by nathanhammond** [comment]
@ivanvanderbyl Can confirm that we're not going to make a change here. The recommended solution for your scenario is going to be the one that @rwjblue [proposes here](https://github.com/ember-cli/ember-cli/issues/6212#issuecomment-242889740).

I'm going to clean that up and get it into the `baseURL` blog post.

/cc @sandstrom: you were right, we do need a better pattern.

**Comment by ivanvanderbyl** [comment]
@nathanhammond thanks for the update, I'm happy with that fix.

**Comment by nathanhammond** [comment]
Not done yet!

**Comment by ivanvanderbyl** [comment]
Solid work guys 😃

**Comment by sandstrom** [comment]
@nathanhammond Yea, OP's problem stems from *subtle* difference we talked about :) I still agree with your point about ease of use for the typical use-case.

Blog posts are great to highlight changes, but people rarely look in old blogposts when looking up API behaviour. Perhaps the pattern in the blogpost could be added to the docs for environment and/or the `rootURL` property.

**Comment by typeoneerror** [comment]
@nathanhammond I'm sorry to bug you about this, but I'm still confused. I changed

```js
// environment.js
baseURL: '/'

// router.js
rootURL: '/app/'
```

to 

```js
// environment.js
rootURL: '/'
routerRootURL: '/app/'

// router.js
rootURL: config.routerRootURL
```

As described in the blog post.

And now everything is served correctly as before, but now my api calls are prefixed with '/app/'. I had to put baseURL back in as '/' to make the api calls be root relative again. Is this expected? I thought baseURL was going away, but seems to be still needed?

**Comment by nathanhammond** [comment]
You should, in most cases, not need `routerRootURL`. That's an escape valve intended for more-complicated apps, not the general case.

Anybody who encounters trouble with this please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and explain your entire setup:

- Where you're serving it from locally. (e.g. `http://localhost:4200/`)
- Where you make your API requests to locally. (e.g. `http://localhost:4200/api/`)
- Where your static assets are served in production. (e.g. `http://localhost:4200/assets/`)
- Where you're serving it from in production. (e.g. `http://www.example.com/myapp/`)
- Where you make your API requests to. (e.g. `http://www.example.com/api/`)
- Where your static assets are served in production. (e.g. `http://cdn.example.com/assets/`)
- Where it lives on the file system in production. (e.g. `/var/www/`)
- Other pertinent reverse proxy information (if you have any).

All of this information is required to help you and possibly more (if common we'll update the list above). Without this complete set of information we can't help you.
