### ISSUE TITLE
Domain name donation

### ISSUE THREAD

**Issue by msmyers** [ember-cli/ember-cli#6225]
I would like to donate these websites/domains to ember-cli:

www.emberjs.feedback
www.ember.feedback
www.ember-cli.feedback

My suggestion is to pick one and have the others redirect to the one that you pick.

The domain names come with free feedback hosted software. (this is because the .feedback TLD requires by policy that each domain name in existence *must* accept feedback from customers. So a default option is provided).

Custom DNS to opt out of the free feedback platform is also an option.

**Comment by nathanhammond** [comment]
Hey @msmyers! I very much appreciate the thought! We've got a large number of web properties, none of which get the attention that we would like. Taking on additional ones is not something we're interested in right now. Additionally we want to funnel feedback into places we already monitor rather than through [Yet Another](https://en.wikipedia.org/wiki/Yet_another)™ input.

I'm closing this issue, but don't let that imply any lack of gratitude. If this is something you wish to maintain on behalf of the community it is certainly something I would encourage you to pursue!

Thanks again!

**Comment by msmyers** [comment]
May I recommend that you redirect all 3 to github.com/ember/issues
