### ISSUE TITLE
Prototype Extensions are disabled in 2.9.0's blueprint for Ember <= 2.6.0.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6252]
#6194 accidentally turned off prototype extensions in newly generated apps. We have two possible solutions proposed by @cibernox:
1. Modify the blueprint to specify each of the prototypes which we extend as proposed by @morhook [here](https://github.com/ember-cli/ember-cli/pull/6194#issuecomment-243815707).
2. Make the code in Ember check for explicit `true` or `false`.

We should also take this opportunity to discuss the future of prototype extensions.

**Comment by Turbo87** [comment]
@nathanhammond was #6194 backported to v2.8.0? in that case I seem to have attached the wrong milestone to it...

**Comment by cibernox** [comment]
To clarify, I proposed to check for explicit `false` since now it's the default, but if the plan is to deprecate prototype extensions, in that case I'd advocate the opposite and check for `true`.

When it comes to prototype extensions, I think that the only problematic one is Array. 95% of apps wont notice disabling extensions in Date. Around 70% won't notice removing `.property` and `.observes` from Function since `Ember.computed/observer` have been encouraged for a long time. String extensions are a bit more extended, but Array is the real deal.

**Comment by rwjblue** [comment]
> To clarify, I proposed to check for explicit false since now it's the default, but if the plan is to deprecate prototype extensions, in that case I'd advocate the opposite and check for true.

I believe this is what Ember is doing (since 2.7).  See [code here](https://github.com/emberjs/ember.js/blob/v2.7.3/packages/ember-environment/lib/utils.js).

**Comment by cibernox** [comment]
@rwjblue I noticed this in 2.6, so maybe this is a non-issue for most people. Probably very few people will use ember-cli canary with Ember 2.6.

**Comment by nathanhammond** [comment]
@Turbo87 Good catch, renamed.

**Comment by locks** [comment]
No longer relevant.
