### ISSUE TITLE
Can't add a custom resolver

### ISSUE THREAD

**Issue by martndemus** [ember-cli/ember-cli#6253]
The following piece of code will fail a build if `ember-resolver` is not in package.json and `ember-resolver.js` is not bower.json:

https://github.com/ember-cli/ember-cli/blob/8c84c6c6188cddb35fb6723f50c9f229439073b3/lib/broccoli/ember-app.js#L328-L333

``` js
  if (this.registry.availablePlugins['ember-resolver']) {
    // if the project is using `ember-resolver` as an addon
    // remove it from `vendorFiles` (the NPM version properly works
    // without `app.import`s)
    delete this.vendorFiles['ember-resolver.js'];
  }
```

I think this should be inverted to check if the bower dep exists and then load the bower dev, else never even add `ember-resolver.js` to `vendorFiles`.

**Comment by nathanhammond** [comment]
Currently we check to see if the user did the good thing of including `ember-resolver` via `npm`. If so, we blindly remove an `ember-resolver` loaded in via `app.import`. The proposal here is to invert the check to see if the user has `ember-resolver` provided via bower. If so, it would write out a deprecation.

**HOWEVER**

@martndemus doesn't want the writing of the deprecation to fail the build as he wants to be able to provide a custom resolver to Ember. Because the custom resolver won't match on the specific name check that we presently do, there won't be a way to _know_ that the user has provided a resolver so we can't immediately fail the build for not including a resolver.

This is approximately the same failure mode of not including `ember-resolver` in either bower or npm, except that it helpfully guides you toward adding it as an npm dependency via deprecation notice.

I do, however, suspect that we would end up with a broccoli build error in the previous scenario.

Having reviewed and summarized the problem, and goal, I don't have strong opinions either way. Maybe @rwjblue does?

**Comment by martndemus** [comment]
Currently if neither a bower or npm resolver is installed you get a cryptic couldn't find `tmp/etc/etc/bower_components/etc/etc/ember-resolver.js` during the build.

This pretty much means that Ember CLI assumes you will either use the bower version of `ember-resolver` or the npm version. It does not in any way factor in that someone might want to replace `ember-resolver` with his own package. 

Either way, there should be a patch that allows someone to provide a custom resolver. I'm totally fine to add some extra logic to warn someone that he might have accidentally removed the resolver.

**Comment by nathanhammond** [comment]
@rwjblue Would you mind sharing an opinion on this one?

**Comment by rwjblue** [comment]
A few general points:

1) Today, you can avoid errors *and* avoid using `ember-resolver` addon via this config in your `ember-cli-build.js`. This works intentionally, and should continue to work (for compat reasons).

```js
new EmberApp(defaults, {
  vendorFiles: {
    'ember-resolver.js': null
  }
});
```

2) If both `bower.json` and `package.json` contain `ember-resolver` the NPM version *must* win.  Inverting the check, so that `bower.json` wins is not desired and should be avoided.

3) We should remove the requirement for the `'ember-resolver.js': null` hack described above in #1. Definitely welcome to PR's that remove that requirement and still solve #2 above.
