### ISSUE TITLE
setupPreprocessorRegistry for CSS has odd behavior

### ISSUE THREAD

**Issue by zackthehuman** [ember-cli/ember-cli#6286]
The behavior of plugins registered for CSS in `setupPreprocessorRegistry` is confusing. I[f you register a plugin, you become responsible for moving files where they need to be (e.g. `'app/styles/app.css' -> 'assets/example.css'`).](https://github.com/ember-cli/ember-cli-preprocessor-registry/blob/master/preprocessors.js#L125)

If there is more than one preprocessor registered, you have no idea what the input node will look like when your plugin receives it. You also don't know what you're supposed to return (whether you filter out everything but CSS, or keep some things, move things, etc.).

There is a default behavior that you basically need to implement in any preprocessor you write, unless you can guarantee that another preprocessor has run before you. For example, `ember-cli-eyeglass` [attempts to do the "same thing" that would normally happen, but the implementation is different and potentially incorrect](https://github.com/sass-eyeglass/ember-cli-eyeglass/blob/master/index.js#L106).

I think this can be improved, perhaps by not requiring plugins to be responsible for moving files to `assets` and letting ember-cli do that before/after processing. I'm still not actually clear _what_ I'm supposed to or not supposed to return from a preprocessor.

**Comment by nathanhammond** [comment]
Making it worse, preprocessors don't actually run in a DAG, resulting in an arms race for choosing the order in which things run. Addons run in a DAG, but depending upon when they `.register` their preprocessor DAG orderign no longer applies and it remains an arms race. [Speaking of arms races, some of the time you just get booted.](https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L68)

But let's skip over that and assume everybody plays nicely on getting into the registry. Then, because there isn't any rule on in-place vs. concatenating vs. renaming vs. doing _literally whatever you want_ by the time you hand off to the next preprocessor it has no guarantees on what it's going to get.

This makes the nested addon story fraught at best when the addons need to modify (or even inspect!) their parents' trees or any trees which they consume.

**Comment by stefanpenner** [comment]
> This makes the nested addon story fraught at best when the addons need to modify (or even inspect!) their parents' trees or any trees which they consume.

Seems unrelated, as designed nested add-ons should only  modify their direct ancestor. This means it is no different then the original issue and that is ordering of preprocessors.

> Add-ons run in a DAG, but depending upon when they .register their preprocessor DAG ordering no longer applies and it remains an arms race. Speaking of arms races, some of the time you just get booted.

I suspect the DAG may or may not be the solution. Rather the whole before/after arms race may be indicative of a missing lifecycle hook or two. I suspect @zackthehuman thoughts on more convention here may do the trick.

@zackthehuman are you able to provide a reduced example (outside of our internal large apps) that we can link to here, and use to derive what may be a better solution?

**Comment by zackthehuman** [comment]
I will see if I can build a small example that demonstrates the pain :)

I do find it odd, though, that the preprocessor plugin becomes responsible for doing what appears to be ember-cli behavior (namely, renaming the `app.css` file and moving it). If that was handled by ember-cli in all cases, either before or after preprocessing it would at least give us a clearer picture of responsibility for CSS preprocessors.

**Comment by locks** [comment]
I believe the CLI team is focusing their build efforts on embroider and thus it won't be likely that this issue would be addressed. If you feel strongly about it, please open a new issue with a reproduction or ideally a PR with a failing test 🙇
Thanks for filing the issue and discussing.
