### ISSUE TITLE
ember install from git

### ISSUE THREAD

**Issue by ming-codes** [ember-cli/ember-cli#6323]
Output from `ember version --verbose && npm --version`:
```
ember-cli: 2.8.0
http_parser: 2.5.2
node: 4.3.2
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
os: darwin x64
2.14.12
```

---

```
>  ember install git+ssh://git@<host>:<name>/<repo>.git 
Installed packages for tooling via npm.
WARNING: Could not figure out blueprint name from: "git+ssh://git@<host>:<name>/<repo>.git". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
Installed addon package.
```

The install seems to be working until it tries to find the default blueprint.

**Comment by nathanhammond** [comment]
This is not a bug. The message you're seeing is telling you what to do:
```
WARNING: Could not figure out blueprint name from: "git+ssh://git@<host>:<name>/<repo>.git". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
```

There is no way to actually know the addon's name from a git path.

**Comment by ming-codes** [comment]
`package.json` offers a name that's generated when the addon is first created. The addon's name can be inferred from this.

**Comment by nathanhammond** [comment]
Yes, it's possible to do this by inspecting state of `package.json` before and after we delegate to `npm install`, running a diff, `require.resolve`ing these new packages, and then figuring out their addon name. Inference is _not_ good enough and something we got out of the business of doing because of the associated errors. It must be correct, or we don't try.

Doing the above is incredibly low on our priority list since it doesn't represent the common case and requires manually running blueprints only once. If this is something you'd like to undertake we're glad to help guide you through the process of contributing it! :smile:

(Steps to do it already described.)

**Comment by ming-codes** [comment]
Sure, I'll give it a shot.

The name of the addon is also in `index.js`. Would this be a better choice?

> Doing the above is incredibly low on our priority list since it doesn't represent the common case.

I'm surprised by this statement. How does enterprise distribute internal Ember addons then? It's a common scenario to install npm modules directly from git repo. I would imagine it's the same case for Ember addons.

**Comment by nathanhammond** [comment]
I work at LinkedIn, we have our own internal npm registry. 😄

The name in `index.js` is used for DAG resolution at current but the npm package name is used to determine the default blueprint (if not specified in package.json): https://github.com/ember-cli/ember-cli/blob/375f3a32f4564465d2eccc3815cb61b570ce29f0/lib/tasks/addon-install.js#L46

That we use different attributes about packages for these scenarios may be something we wish to align. Reach out to @kategengler (on vacation for two weeks, so in two weeks) and ask if she can help you identify how many addons have different npm package names and internal names and if they have a self-named blueprint.
