### ISSUE TITLE
ember.js server 1 minute startup time on vagrant ubuntu

### ISSUE THREAD

**Issue by alanzheng88** [ember-cli/ember-cli#6355]
Reference: emberjs/ember.js#14483

Output from `ember version --verbose && npm --version`:
```
ubuntu@ubuntu-xenial:~/project/webroot$ ember version --verbose && npm --version
ember-cli: 2.6.3
http_parser: 2.7.0
node: 6.7.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: linux x64
3.10.8
```

Steps to reproduce issue:
- Follow instructions specified on https://github.com/alanzheng88/vagrant-chef-emberjs-boilerplate
- Note ember server build time

**Comment by nathanhammond** [comment]
This is due to virtualized FS access and there's little we can do about it. Rebuild times should be _much_ faster than initial build times, but running Ember CLI in a VM will never be ideal. We can do better, but that effort won't be tied specifically to a VM.

Thank you for reporting the slowness, please help us monitor for any regressions!
