### ISSUE TITLE
Portfinder 1.0.8 Investigation

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6361]
@cryrivers reports that portfinder@1.0.8 is not working as part of this permutation: macOS 10.12.0 / Node v5.12.0 / Ember CLI 2.8

@nightire presents a workaround of pinning 1.0.7 which implies that they have encountered an issue. Can you please describe your system setup, @nightire?

/cc @eriktrom

**Comment by eriktrom** [comment]
Will look into it. I board a plane in 20 min. Usually they have wifi. I hope nothing is really really broken.

**Comment by eriktrom** [comment]
According to #6359 its watchman. Thanks @mikl for verifying that

**Comment by nathanhammond** [comment]
There are still other reports possibly identifying 1.0.8 as an issue. @cryrivers @nightire can you confirm/deny?

@eriktrom Don't worry about it on your flight, it's not super-critical considering a few-days-old release. <3

**Comment by eriktrom** [comment]
Roger that. I will take a deep look later this afternoon. Portfinder does actually pipe text through the socket and back to the client now so it is doing more than just checking that the listening event fires. Odd nonetheless.

**Comment by arschmitz** [comment]
I ran into this this morning as well and removing watch man had no effect but fixing portfinder to 1.0.7 did even happened i'm running osx 10.12 node 6.4 and 6.7 ( tried both ) and ember-cli 2.9.0-beta.2 co workers with same everything except osx were fine

**Comment by bantic** [comment]
I had the same issue just now as well. Adding an explicit dependence on portfinder@1.0.7 fixed for me as well.
And perhaps more usefully, the following script hangs for me with 1.0.8, but runs with the expected result (4200) with portfinder 1.0.7:
```
var pf = require('portfinder');
pf.basePort = 4200;
pf.getPort(function(err, port) {
  console.log(port);
});
```

Output from ember version:
```
ember-cli: 2.7.0
node: 5.4.1
os: darwin x64
```

**Comment by nightire** [comment]
@nathanhammond I can confirm it is related with portfinder, 1.0.8? maybe, the only thing I can be sure is portfinder@1.0.7 is the cure for now.

watchman? not likely, this afternoon I work with this problem more than 3 hrs, I've tried install/uninstall watchman multiple times, it didn't change anything.

and I also think the root of problem is coming from macOS sierra public beta, at least some version of it, because this problem only happens after an automatic system upgrade (consequence of join apple beta program...)

I've been struggled with it in 3 ember projects, I've tried node v4.x v5.x v6.x and npm from v2.x to v3.x, until I found some ng-cli users complains about this as well, someone says it maybe caused by WiFi, and turn off WiFi connection before `ember s` will solve this problem, however it not works for me at least, but it reminds me a related ember-cli issue, which I can't remember which one right now, but it says how to manually upgrade portfinder in a linked local ember-cli repo, and use `DEBUG=portfinder* ember s -p 0` to diagnosing.

So I tried different version of portfinder, and finally portfinder@1.0.7 save my day.

**Comment by JasonGoemaat** [comment]
Coming here from angular-cli where I ran into this issue on Windows 10.  The portfinder installed tries to bind to my bluetooth network adapter which has an error, even though I specify the host of localhost, 127.0.0.1, or my local network ip.  Why is PortFinder used when the ports are specified?  Does it 'validate' the port before actually trying to use it or something?

**Comment by nightire** [comment]
@JasonGoemaat One reason behind that I think is to allocate an available port to livereload, because you might run multiple `ember s` (or ng-cli) process at the same time, even we can specify different port for app server, but livereload still requires a free port.

**Comment by JasonGoemaat** [comment]
You can specify the --live-reload-port too though...  I would think if a port was specified that it shouldn't attempt to use a different port.  Is it so you can specifyport 5000 and start up several instances on 5000, 5001, 5002, etc.?  That never seemed to work before I had this issue anyway, if I tried to start a second project it would give me an error instead of trying a new port.

**Comment by kiwiupover** [comment]
@eriktrom did you see this also http://stackoverflow.com/questions/40117065/ember-application-fails-to-load-after-upgrading-it-from-ember-2-7-to-2-8-when-co

**Comment by kabirsikand** [comment]
I'm seeing this issue using Node v5.20.0 / Ember-CLI 2.8.0 / OSX 10.12.0
Watchman v4.7
Portfinder v1.0.8

```
$ ember serve
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT fdd1:d9d8:4489:19b9:9c9e:794b:9e9d:fb5f:4200
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1064:14)
```

**Comment by kabirsikand** [comment]
And, to confirm - migrating to `portfinder 1.0.7` did the trick. 

*(Add `"portfinder": "1.0.7"`) to your `package.json`)*

**Comment by eriktrom** [comment]
Portfinder 1.0.9 has been published to npm. It has the same code as 1.0.7. Sorry folks

**Comment by eriktrom** [comment]
@JasonGoemaat - thanks for the windows 10 feedback. That was the reason for portfinder 1.0.8. Unfortanetly from inside a VM I didn't have bouetooth as an interface. 

To clarify all - yes portfinder verifies a port is not in use before booting express and live reload. It is a rather hard thing to validate across every OS though as one must know the error the node syscall will throw a priori

Thanks for ur patience all.

**Comment by eriktrom** [comment]
Regarding the issue in angular-cli - specifically with manually passing a live reload or normal server port and having it not pass through to portfinder - this is b/c angular-cli forked long ago and does not have recent enough code including that feature, even though it does include portfinder@^xxx. This perhaps should be addressed at some point.

**Comment by nathanhammond** [comment]
@eriktrom Thanks for the update. Closing this issue.

As always we're _incredibly_ grateful for your unending efforts on this.

**Comment by eriktrom** [comment]
@nathanhammond - no problemo. Turns out u can't pipe to bluetooth even though it'll listen on a port u open on it(odd). I had bluetooth disabled in mac os yesterday completely. 

This means I'm currently all out of hacks for windows 10 native shell support for portfinding - fyi. Will open PR if that changes.
