### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by Polve** [ember-cli/ember-cli#6400]
The first release candidate of WebAssembly has been released and they are requesting comments.

I'm not an expert but I suppose that ember-cli could be the right place to modify the tool chain in order to have a look at the tech and experiment a bit with it?

Thanks for any info on the subject :-)

**Comment by corbinu** [comment]
@Polve WebAssembly does not have any features for JS to WebAssembly features at least for the moment it is for C, C++ projects compiled via Emscripten. If features for JavaScript to WebAssembly these features are ever added they would be handled by the transpilers (Babeljs, TypeScript, etc)

Here is a great article that may help:
http://www.2ality.com/2015/06/web-assembly.html

**Comment by corbinu** [comment]
Also might want to read this from the WebAssembly FAQ: https://github.com/WebAssembly/design/blob/master/FAQ.md#which-compilers-can-i-use-to-build-webassembly-programs

**Comment by stefanpenner** [comment]
We are following WebAssembly closely. At the moment, it isn't something ember apps can benefit from directly. Although, it is entirely reasonable for them to have dependencies (like lets say, an image processing library, or all of sqlite3, or something), those should already work today!

**Comment by Polve** [comment]
Thanks for all the comments.

My goal would be to have the capability to build a webasm distribution file that should be way smaller than the actual .js file. This should enable the app on browser to start way faster due to the complete skipping of parsing and compiling the JS code.

With particular relevance on mobile platforms where, using crosswalk, we can control that a compatible version of chrome is running the app.

**Comment by stefanpenner** [comment]
> This should enable the app on browser to start way faster due to the complete skipping of parsing and compiling the JS code.

I believe currently this is not supported for just any JavaScript (although it would be really nice if someday it was). My understanding, this is only for a subset of JavaScript which is essentially C. e.g. you manage your own memory and don't have direct access to the DOM.

**Comment by stefanpenner** [comment]
further on what this subset of JS is: http://asmjs.org/spec/latest/

I did some experimenting sometime ago, but noticed quite quickly (at the time) this was very well suited for extracting totally isolated algorithms, but quite poor/impractical at running user-code that wants access to "Regular" things.

**Comment by Polve** [comment]
Thanks  @stefanpenner for the infos, I had not realized that.

While I understand the need to run low level code written for example in C, what I don't understand is why the use of a GC can't be coupled with the compiled JS.

What I find idiotic in our present web architecture is to send (usually) megabytes of minified/uglified source code to the clients that each one of them must parse and compile it before running it.

Skipping the parsing phase gives also the added bonus that the language can evolve faster because the new version does not need to be supported by the clients: they just need to be bytecode compatible, and that's a big advantage.

**Comment by corbinu** [comment]
@Polve While it may be true that the browsers performance could be increased this will have to happen at the bower level and later the transpiler level rather than Ember.

Also ran a quick check on my laptop and iPhone and parse time for an Ember.js 2.9.0 app was consistently less than half of the execution time. So at least from Ember's perspective I believe that FastBoot is the recommend path as it would allow the app state requested to be displayed before the entire initialization (both parse and execution time) and is implementable at Ember's level in the stack. 

As for the browsers speeding up web apps it definitely seems like that the current concentration is focused on HTTP/2 as it has a greater effect on all the the load time of all resources in an app including the resources and data that are loaded dynamically after the app starts. In the case of javascript specifically it seems like more improvements are being made in execution time of Promises and steps towards lazy loading via System.js

So while it may seem "idiotic" at the moment the simple fact outside of extremely large JS files like those seen in WebGL and transpiled C code there is just far more low hanging fruit for optimizing the performance of web apps. It is simply an issue of premature optimization for the moment.

**Comment by stefanpenner** [comment]
@corbinu an interesting tidbit, is quite a-bit of the "evaluation time" of ember and of ember apps is unfortunately hidden parsing them. V8 (and others) for example leave some parts of our code largely unparsed/uncompiled, they do so if they feel the code in question is not required on initial load. This is actually quite a great feature, but it does amortize this parse/compile cost out overtime. Which means although initial load is better, ever subsequent encounter of not-yet encountered code is slightly slower. So by shipping something that is essentially perparsed and compiled to byte code. It would (if possible) really make a nice difference.

It would be very cool, if we could provide a build that was able to "precompile" on the server (sorta like how we do templates). Unfortunately, as WebAsm stands today, this isn't possible, at-least not wholesale or without heroic effort. (I gave the reasons above)

@Polve as @corbinu mentioned, our parse times were not the motivation (and thus not a use-case that works). One of the primary motivators, was the ability for large projects (like let say Unreal Engine)which to not take minutes parse/compiling. In addition, I believe they where able to safely accomplish this, because the subset of JS asm.js produced is safely constrained and statically verifiable, whereas regular JS is neither of these.

I do hope in the future we have the ability to provide a precompiled blob of bytecode for the browser to merely load into memory.

**Comment by Polve** [comment]
As an example I'm working on an app which has a lot of dependencies (mainly because it uses cryptography), the vendor js file is more than 2.2MB and the app js is another 2MB, and it takes around 10 secs on a decent android phone.
I'm not sure how much of this time is due to load/parse the code, but I suspect it's a good bit.
Even if it is only 30%, it would be great to avoid it.

I understand this is not possible (today?) with webasm, so too bad, and I'll try to better understand better that tech :-)

Thanks for all the interesting informations.

**Comment by corbinu** [comment]
@Polve Is that in the old Android browsers? Not trying to start a mobile flame war but I though that Chrome on android had caught up to Parse/Execution time on iOS (my test loaded a similarly sized app in 600ms on an iPhone 6S, 2.4 seconds on an old iPad 2) 

I purely ask out of curiosity as if that is still the case then it sounds like something is very wrong inside the android WebView.

**Comment by corbinu** [comment]
It would be super cool if somebody redid this test for Ember apps:
https://timkadlec.com/2014/09/js-parse-and-execution-time/

**Comment by Polve** [comment]
It is the chrome packaged with crosswalk latest version, and I think it was chrome 48.

I know in iOS the JS support is very different, but you can't have chrome there, though

**Comment by corbinu** [comment]
Ahh ok ... that may be the issue as I think Chrome 50+ had some large improvements for mobile parse times. You might want to look at the parse time if the app is loaded strait as web app to confirm though (I use NativeScript and Xamarin for apps so I am not that familiar with CrossWalk)

Ya FastBoot doesn't really help you there :( You would think there would be some way for CrossWalk to parse the app on first load. Then cache that to the disk so at least it would start up faster the next time.
