### ISSUE TITLE
Remove ember-cli-shims

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli#6420]
Considering that https://github.com/emberjs/rfcs/pull/68 was just closed in favor of https://github.com/emberjs/rfcs/pull/176 `ember-cli-shims` should no longer be included or recommended. For that matter, I don't know why it was allowed in the official build in the first place. It implements a spec that had not yet been approved. I think moving forward any new addons brought in should respect on API that is official and not API that *may* become official.

**Comment by bcardarella** [comment]
**Or** it is rolled back to just export `Ember` and not include all of the other shims.

**Comment by rwjblue** [comment]
> I don't know why it was allowed in the official build in the first place

I am unsure of exact timing, but I suspect that at least a few shims predate RFC process. Also, only recently (last year or so) has "default inclusion in ember-cli" been considered an Ember core public API concern (and therefore require RFC). 

> It implements a spec that had not yet been approved. 

Agreed, completely.  But the path forward isn't to introduce more churn. We should land https://github.com/emberjs/rfcs/pull/176 then deprecate ember-cli-shims completely. Part of landing the RFC would be to ensure that the provided codemod can properly handle the current shims imports and replace them with their counterparts. There is no real harm to leaving things the way they are now (either way folks will have to migrate with the codemod tool or otherwise), and changing it risks breaking folks that are just updating their apps (and invalidating anything written in blog posts/etc before the official and public solution is landed).

Also, for what it is worth, the current shims absolutely meet the criteria for intimate API and cannot simply be removed. We will continue to support them (with deprecation) for at least one LTS cycle (possibly longer depending on community up take when the new RFC lands).

**Comment by nathanhammond** [comment]
@bcardarella This is another of the scenarios where we got a bit ahead of ourselves. [We added ember-cli-shims to Ember CLI somewhere in early _2014_–before we'd truly figured out governance and what we wanted this to look like.](https://github.com/ember-cli/ember-cli/commit/0aa047b15a8a06612ef522fa008f2d26d7ee3d52) (Note: that's literally the first commit in which we had built-in generators, I stopped tracing at that point.)

I'm closing this as we can't drop support for `ember-cli-shims` at this point, no matter how much we'd like to do so, until we have a path forward.

**Comment by stefanpenner** [comment]
@bcardarella thanks for keeping us honest!

> We should land emberjs/rfcs#176 then deprecate ember-cli-shims completely. Part of landing the RFC would be to ensure that the provided codemod can properly handle the current shims imports and replace them with their counterparts.

I think some of our discussions may have been out-of-band (which isn't good) @nathanhammond has been exploring how we can "auto-upgrade" people (obviously several important details to resolve) but hopefully that will help mitigate the churn concern sufficiently?

**Comment by bcardarella** [comment]
> But the path forward isn't to introduce more churn. We should land emberjs/rfcs#176 then deprecate ember-cli-shims completely.

Does this make sense? As a mid-term would it not make sense to deprecate the old-shim style once 176 lands then include the new shim syntax in ember-cli-shim? There will, I imagine, be a period of time between when 176 is accepted and when it is implemented? That time can be used to migrate consumers of the old-style to the new syntax.

I would imagine that anyone doing `import Ember from 'ember'` will also have to deprecated?

Also, you may want to be careful not to limit the deprecation warnings to first-use only and not have them scream on every import or else it will be 1.10 - 1.13 all over again.

**Comment by rwjblue** [comment]
> Does this make sense? 

Well, I think so. 😜 

> There will, I imagine, be a period of time between when 176 is accepted and when it is implemented?

I don't really think so, as the current ember-cli-shims repo shows it is really easy to make these sorts of shims. I suspect the path forward is to convert ember-cli-shims to an addon (this can be done nowish), provide the new shims, deprecate the old shims.  When Ember itself provides its own modules, we would detect that Ember version from the addon version of ember-cli-shims and deprecate using the addon at all.

This is all just spit-balling though, we would have to sit down and plot a real path when the time comes...

> Also, you may want to be careful not to limit the deprecation warnings to first-use only and not have them scream on every import or else it will be 1.10 - 1.13 all over again.

Yep, definitely need to be careful here.  I suspect that we would want to add some sort of deprecation support to `loader.js`.  So that the deprecation message can include the module name that is importing the deprecated shim, or something....
