### ISSUE TITLE
[Windows] Ctrl+C produces Exit status 1 

### ISSUE THREAD

**Issue by ro0gr** [ember-cli/ember-cli#6421]
When interrupt an ember server I get the following output:
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v5.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! ember-cli-windows-exit-error@0.0.0 start: `ember server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-cli-windows-exit-error@0.0.0 start script 'ember server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ember-cli-windows-exit-error package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ember-cli-windows-exit-error
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ember-cli-windows-exit-error
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ruslan\ember-cli-windows-exit-error\npm-debug.log

---
```

I've tested this in different combinations: **powershell**/**cmd**, **windows7**/**windows8**, **node@5**/**node@6** and always get the same output as above.

The issue started to happen in **ember-cli@2.7** and still persist in master. As I can see [trapWindowsSignals](https://github.com/ember-cli/ember-cli/commit/6b0e17e9c70585c115ce6c37ea1b9276e2060451) revealed this.

I believe the problem is not related to trapWindowsSignals implemetation. Seems like it's [`process.exit(1)`](https://github.com/ember-cli/ember-cli/blob/master/lib/models/builder.js#L260).
When I run `process.exit()` without error code termination works as expected at least on my local machine. 

Does anybody know is there any reason to exit with an error code after cleaning up? Can we safely remove it?

**Comment by rwjblue** [comment]
A few things to note here:

* I'm pretty sure this isn't a "windows issue" per-se, its just that windows shows that gnarly exit code by default when things exit with non-zero status.
* The reason we `process.exit(1)` in a few places in `lib/models/builder.js` is because the actual exit state is not clear.  For example, as you mentioned CTRL+C while running `ember serve` seems totally fine, and not really a case for exiting non-zero, but what about CTRL+C for `ember build`?  We are currently erring on the side of caution (could you imagine `ember build && npm publish` or something publishing when you CTRL+C during build?).  

It is possible for us to detect which command is being ran, and explicitly avoid `process.exit(1)` in whitelisted commands (I'm not sure if there are more than `serve` though).

Also, sorry about the long delay here @ro0gr.

**Comment by nathanhammond** [comment]
I believe that I prefer the current exit code strategy in spite of the horrifically bad `npm` messages if you invoke `ember serve` via `npm start`. You can of course directly invoke `ember serve` instead of proxying it through `npm start` which will get rid of this error message.

I'm closing this as I don't believe that we should make any changes. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread. Let me know if you think that this is a reasonable decision, @ro0gr and @rwjblue.

**Comment by ro0gr** [comment]
@nathanhammond as for me this is definitely an UX issue originated from `ember-cli`. if I were `npm` I would behave the same way(probably with better messaging) when I get an error code from a child. 

@rwjblue thank you for clarifications. As I can see `models/builder.js` is also used in the `Test` command. 
Whitelisting seems fragile to me. I believe it's possible to handle it in a better way. 
Need some more time to investigate and think about it.

**Comment by hjdivad** [comment]
@nathanhammond any objection to reopening this?  per the discussion we had a few minutes ago, a daemon/looping process exiting nonzero on `SIGINT` seems nonstandard & something worth fixing.

**Comment by rwjblue** [comment]
@hjdivad - I think we are working on fixing it in #6615, no?  

Since we intend to fix it, I see no problem with reopening...

**Comment by ro0gr** [comment]
Clever guy @homu closed this issue before I asked.

I'm not very familiar with a policy for releasing such kind of changes. So I'm interested which release should include this fix? is it ok for 2.12?

**Comment by rwjblue** [comment]
@ro0gr - The changes were targetted at what will become 2.13.

**Comment by ro0gr** [comment]
just 3 months to wait. Not a big deal 😴
