### ISSUE TITLE
Add the option of store environment.js info in separate file instead of meta

### ISSUE THREAD

**Issue by marioGomezDev** [ember-cli/ember-cli#6488]
I like the possibility of modifying the configuration without having to recompile, but change the generated meta in index.html is a little tricky. Is it possible to save the information in another file instead of meta? 

For example
```
// ember-cli-build.js
var app = new EmberApp({
  configLocation: ->"file", "meta" (storeConfigInMeta = true), "app" (storeConfigInMeta = false)
});
```
```
// index.html
<!DOCTYPE html>
   ...
   <script src="config.js" ></script>
   ...
</html>
```

**Comment by ro0gr** [comment]
Does storeConfigInMeta works for you?
https://ember-cli.com/user-guide/#application-configuration ?

**Comment by marioGomezDev** [comment]
No, I need the info in a separate file instead meta.

**Comment by stefanpenner** [comment]
@marioGomezDev sounds reasonable, mind working through and RFC for this? github.com/ember-cli/rfcs We will gladly iterate on that idea with you via line-comments in an RFC pull request.

**Comment by marioGomezDev** [comment]
Nice, I am very new to this and I don't understand how works, but I will investigate in the coming days and upload this RFC. Having this feature would be very useful. Thanks.

P.S. I apologize for my poor english.

**Comment by stefanpenner** [comment]
> P.S. I apologize for my poor english.

No need to apologize, thanks for tolerating this project of primarily english maintainers.

> Nice, I am very new to this and I don't understand how works, but I will investigate in the coming days and upload this RFC.

https://github.com/ember-cli/rfcs/blob/master/README.md may help :)

**Comment by nightire** [comment]
@marioGomezDev Agreed with you on this.

**Comment by nathanhammond** [comment]
> No, I need the info in a separate file instead meta.

That is literally accomplished by setting `storeConfigInMeta: false`.

```
// ember-cli-build.js
var app = new EmberApp({
  storeConfigInMeta: false
});
```

If this doesn't result in livereload then it is a bug. The asset will end up in `app-name.js`. Otherwise I believe that this should automatically move the config into the JS which will make it do what you're hoping.

If your aim is to have a separate configuration file for a production environment I don't recommend that. The network request will be too expensive and that is not a change we would codify inside of Ember CLI itself.

I'm closing this as I _believe_ we already have a solution for it. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

Please stop by [#-ember-cli](https://embercommunity.slack.com/messages/-ember-cli/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and seek help from the wonderful people in our community to sort out the rest of your goals.
