### ISSUE TITLE
ember-cli-eslint doesn't appear in the default blueprint.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli#6643]
Given more time to think about it, I'm not 100% happy with how `ember-cli-eslint` isn't in the default blueprint anymore. Many users don't use `ember init` to handle upgrades which means that they end up "stuck" on whichever version they have installed, or worse, delete it without paying attention as to why [when they view the comparison](https://github.com/ember-cli/ember-cli/blob/master/dev/add-to-output-repos.sh#L35).

This whole setup exists for one reason: we need to be able to run all default blueprints for bundled addons once per application creation. We may possibly in the future want to run the default blueprint for every addon in the application each time that addon gets updated. The attachment to `init` is because we can't run any blueprints unless we actually have a `node_modules` folder...

This complicates [programmatic fixture creation](https://github.com/ember-cli/ember-cli/pull/6449) as well.

I don't have a solution yet just a set of constraints and a bit of uncertainty that we've found the global maxima.

/cc @Turbo87

**Comment by Turbo87** [comment]
maybe to make this at least a little better we should add `ember-cli-eslint` to the blueprint `package.json` and instead of `npm install -D ember-cli-eslint` we run `ember generate ember-cli-eslint` after the main `npm install`?

that way, at least the dependency is back in `package.json` and the `ember-new-output` comparison.

**Comment by kellyselden** [comment]
@Turbo87 I like that idea.

**Comment by rwjblue** [comment]
Wouldn't this mean that changes in `ember-cli-eslint`'s blueprint (including things like `.eslintrc.js`) are not shown in `ember-new-output`?

**Comment by nathanhammond** [comment]
@rwjblue: they're already not present in the output repos since we don't run the install task which is gated on `--skip-npm`. (We can't run the blueprint without the modules.)

**Comment by rwjblue** [comment]
> they're already not present in the output repos since we don't run the install task which is gated on --skip-npm.

I know, and I thought that is what this issue was trying to resolve.

In https://github.com/ember-cli/ember-cli/issues/6643#issuecomment-270701487 I was specifically replying to @Turbo87's suggestion in https://github.com/ember-cli/ember-cli/issues/6643#issuecomment-270588000.  Which I think is somewhat better than today (today we don't even show `ember-cli-eslint` as part of the default app output), but not enough because it would still be missing things like `.eslintrc.js`.

**Comment by nathanhammond** [comment]
@rwjblue I'm sorry, didn't mean to talk past each other or imply you'd missed something. Should've assumed confusion in communication and asked to better understand. <3

I'm unsure how to balance running of default blueprints of default-installed addons inclusion into `ember-new-output` and `ember-addon-output`. There are multiple layers:

1. `ember-cli-eslint` being present. This is easily solveable.
2. `.eslintrc.js` and other things from the default blueprint. This is much more complicated given it requires a nested installation process. The only way out of nested install is bundling with `ember-cli` (a la `ember-try`) but that comes with its own fun set of tradeoffs.
3. ???

Just writing words, maybe somebody can turn them into a good idea.

**Comment by rwjblue** [comment]
Prior to the current situation (i.e. when we were including jshint out of the box) we had our default blueprint in `blueprints/app/files/*` include all of the jshint specific infrastructure. This met all of the criteria above, but was removed so that we could facilitate the migration to ember-cli-eslint. 

I suggest that now that that transition has happened we should actually just update our blueprinted files in `blueprint/app/files/*` to match what we now expect a default app to have.  This meets all of the constraints, while still keeping `ember-cli-eslint` included at the app layer (and therefore still being in control of the app).  Concretely, I am proposing that we copy [blueprints/ember-cli-eslint/files/.eslintrc.js](https://github.com/ember-cli/ember-cli-eslint/blob/master/blueprints/ember-cli-eslint/files/.eslintrc.js) and [blueprints/ember-cli-eslint/files/tests/.eslintrc.js](https://github.com/ember-cli/ember-cli-eslint/blob/master/blueprints/ember-cli-eslint/files/tests/.eslintrc.js) into our own `blueprints/app/files/*`.

**Comment by Turbo87** [comment]
I don't agree with that proposal of duplicating the files. It seems inevitable that they will be out of sync at some point. Is there a reason for skipping npm install when we assemble the ember-new-output files? If we just allowed npm to install it seems to me that our issues would likely be solved.

**Comment by kellyselden** [comment]
> If we just allowed npm to install it seems to me that our issues would likely be solved.

@Turbo87 not necessarily. I update my addons with `ember init -sn`, so some people wouldn't get the files.

What about taking @rwjblue's suggestion further, and as part of our (semi-)automated release process, we run the eslint generator and commit the most recent `.eslintrc.js` files just before release?

**Comment by Turbo87** [comment]
> as part of our (semi-)automated release process, we run the eslint generator and commit the most recent .eslintrc.js files just before release?

that is pretty much what I meant, but without `npm install` (i.e. with `--skip-npm`) you don't have the generator installed and thus can't run it.

**Comment by kellyselden** [comment]
@Turbo87 I don't think we are on the same page. The releaser (us) would commit the files before release. The consumer would get the files no matter if they skipped npm install or not, since they are in the initial payload.

**Comment by Turbo87** [comment]
ah, you meant committing to `ember-cli`. I don't like that... if you did that and `ember-cli-eslint` blueprints change then the user would be greated with "do you want to overwrite .eslintrc.js?" upon `ember new`

**Comment by kellyselden** [comment]
> "do you want to overwrite .eslintrc.js?" upon ember new

Isn't that inevitable? What about the case of the user makes a bunch of changes to .eslintrc.js, but then we make changes to it as well. How do they get the new changes?

**Comment by Turbo87** [comment]
this was at least partly fixed by #6681
