### ISSUE TITLE
non-production build includes ember-welcome-page/ember-welcome-page.png

### ISSUE THREAD

**Issue by Nippius** [ember-cli/ember-cli#6719]
When starting a new ember project using ember new <name> the ember-welcome-page package is installed. 

This package contains a picture of the ember mascote and it gets copied into the "dist" folder when the project is built using "ember build".

So far so good, however, In the previous build of ember-cli (I tested on 2.10.0), when removing the Application.hbs {{ember-welcome-page}} property, the image would stop beeing copied to the output.

In the 2.11.0 version this dosen´t happen and the image is always copied when making a debug build. (Productions builds are fine. No image is copied.)

One solution is to just uninstall the ember-welcome-page package after the project is created, but i think a proper fix would be nicer.

Thank you.
---
Output from `ember version --verbose && npm --version`:
(disregard the node version. i tested with the 6.9.4 LTS build and the some behaviour occurs)
```
ember-cli: 2.11.0
http_parser: 2.7.0
node: 7.3.0
v8: 5.4.500.45
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g
os: win32 x64
3.10.10
```

**Comment by kellyselden** [comment]
cc @locks

**Comment by locks** [comment]
@Nippius That's for reporting. I tweaked the title of the issue because the behaviour you descrive is how we intend for it to work http://emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_updated-code-ember-welcome-page-code ;)

One idea for the next step in ember-welcome-page would be to do what you're saying, remove the assets if we don't detect the component in templates, but that's a bit more tricky. It would also make the component work differently from other components, which is not our intention.
What I think you want here is tree shaking, which would apply across the project too, and not just to welcome-page.

I have opened a follow-up issue on the addon repository: https://github.com/ember-cli/ember-welcome-page/issues/70. See you there!

**Comment by locks** [comment]
@Nippius P.S. Are you on the Ember Slack? I'd like to discuss why the image being there in the debug build is a problem.

**Comment by Nippius** [comment]
@locks Thank you! I missed that bit in the release notes!

Regarding the issue, the image being in the output is not a problem per se in terms of functionality. Everything just works. 

I mention it because I started learning ember.js when the transition occured from 2.10 to 2.11 and was confused when files i didn´t want started to appear on the output. However, given the dificulty, i think it's best to either ignore the files or update the tutorial to make a reference to that. No harm done :)

I'll see the follow-up issue :)

Oh and I'm not on Ember Slack but I can create an account if it makes things easier.

Thank you!
