### ISSUE TITLE
Add `removeBowerPackage(s)fromProject` to Blueprint API?

### ISSUE THREAD

**Issue by srvance** [ember-cli/ember-cli#6774]
Would adding the above be useful or does the push to get away from Bower make it not so much?

@Turbo87 suggested I file an issue to see how @rwjblue and @stefanpenner feel about it.

# Background

I'm porting `ember-bootstrap` to be mutually compatible with both Bootstrap 3 and 4. @simonihmig came up with a clever scheme to make both available by letting Bootstrap 3 live in `bower.json` and adding alternate dependencies like Bootstrap 4 and `bootstrap-sass` in `package.json`. We then customize the build tree imports to pull in only the right package for production.

I'm looking to extend the blueprint to take CLI flags to allow people to go from any configuration to any other and only have the dependencies they actually need. To do this properly, I need to be able to remove entries from `bower.json`. The Bower API has supported this since May 2013, but it hasn't been exposed in the Blueprint API.

I would implement this as an addon. If we wanted it in `ember-cli` I would set it up as a polyfill. I may do the addon regardless based on need, but wanted your opinion of whether I should also put in a PR and build it as a polyfill.

**Comment by stefanpenner** [comment]
Removal is quite tricky, as it makes composition of blueprints quite tricky.

**Comment by srvance** [comment]
Sounds like it wouldn't be time well spent trying to get it into `ember-cli`.

I appreciate the point about blueprint composition. While I wouldn't be worried about it for `ember-bootstrap` removing `bootstrap`, the general case could be complicated. The same problem exists with removing `npm` packages.

Thanks for the feedback.

**Comment by tzellman** [comment]
I have a similar use-case where I would like to remove bower packages after install, mainly because some older addons are adding dependencies such as `ember-cli-shims` to `bower.json`, which will fail when using the latest version of Ember. The workaround is to simply manually remove it afterwards, but I was hoping to automate that.

After looking at the code,  it seems like the [BowerInstallTask](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/bower-install.js) code could be mostly abstracted into a base `BowerTask`, much like the [NpmTask](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js).

I'm willing to look into this, unless there is no chance a PR would be accepted.

**Comment by srvance** [comment]
@tzellman Because bower is being removed from Ember, I decided not to pursue it as a general purpose addon or a PR. You can find my sufficient solution [here](https://github.com/kaliber5/ember-bootstrap/pull/233/commits/71f3450e1490902e4e891a20f36ad139d2eb2bc4).
