### ISSUE TITLE
Modifying SASS files triggers full reload in 2.12.1 (and 2.15.1)

### ISSUE THREAD

**Issue by Senthe** [ember-cli/ember-cli#6926]
Modifying a SASS file causes full page reload instead of CSS livereload in Ember CLI 2.12.1. It wasn't the case when I was using 2.8.0 previously.

I guess it has to be already noticed, but please give some update on this issue.

**Comment by rwjblue** [comment]
Please provide a demo repo (including steps to follow to reproduce the issue) so we can dig in further.

**Comment by Senthe** [comment]
I'm unable to create a demo repo right now, I'm sorry (don't have free time). I can't publish the repo that I work with, too.

All I can do right now is to paste my package:

```
{
  "devDependencies": {
    "broccoli": "^0.16.9",
    "broccoli-asset-rev": "^2.4.6",
    "dynamic-link": "0.2.1",
    "ember-ajax": "^2.0.1",
    "ember-autoresize": "0.5.17",
    "ember-browserify": "^1.1.13",
    "ember-can": "0.8.3",
    "ember-cli-airbrake": "0.1.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "1.0.0",
    "ember-cli-deploy-build": "0.1.1",
    "ember-cli-deploy-cloudfront": "^0.2.8",
    "ember-cli-deploy-display-revisions": "0.2.2",
    "ember-cli-deploy-revision-data": "0.3.3",
    "ember-cli-deploy-s3": "^0.4.0",
    "ember-cli-deploy-s3-index": "0.5.0",
    "ember-cli-emblem": "0.8.2-beta.2",
    "ember-cli-eslint": "3.0.0",
    "ember-cli-fastboot": "^1.0.0-beta.15",
    "ember-cli-form-data": "1.0.0",
    "ember-cli-g-maps": "0.5.1",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-mirage": "0.2.3",
    "ember-cli-moment-shim": "3.0.1",
    "ember-cli-qunit": "^2.1.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "^5.5.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.8.0",
    "ember-data-filter": "1.13.0",
    "ember-export-application-global": "^1.0.5",
    "ember-i18n": "4.3.2",
    "ember-load-initializers": "^0.5.1",
    "ember-modal-dialog": "0.9.0",
    "ember-moment": "7.3.0",
    "ember-normalize": "1.0.0",
    "ember-power-select": "1.5.0-beta.2",
    "ember-resolver": "^2.0.3",
    "ember-route-history": "0.1.3",
    "ember-simple-auth": "1.1.0",
    "ember-sinon": "0.5.1",
    "eslint": "^3.8.1",
    "express": "^4.14.0",
    "glob": "^4.5.3",
    "javascript-state-machine": "2.4.0",
    "loader.js": "^4.0.1",
    "morgan": "^1.7.0",
    "normalize.css": "4.1.1"
  },
  "dependencies": {
    "ember-cli-babel": "^5.1.6", 
    "babel-polyfill": "^6.16.0",
    "ember-cli": "^2.8.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-code-coverage": "0.2.2",
    "ember-i18n-inject": "0.0.2",
    "ember-inline-svg": "0.1.7",
    "google-libphonenumber": "^2.0.4",
    "libphonenumber-js": "^0.2.31",
    "moment": "^2.16.0",
    "symlink-or-copy": "^1.1.8"
  }
}
```

I have done a fresh npm install with that like 5 days ago and ended up with this bug.

**Comment by maxkwallace** [comment]
I'm not sure what introduced it, but as of a couple weeks ago, I'm seeing the same issue (except with PostCSS instead of Sass) in the Ember app I work on. Switching to regular CSS didn't fix the issue, but I can't reproduce the problem in a fresh Ember app either. This doesn't seem to be a problem out-of-the-box. Maybe it's an unintended interaction between Ember CLI and a dependency?

I'm going to try to dig into this a bit more; I'll post back if I find anything else. Any pointers on where to start debugging this would be appreciated.

**Comment by maxkwallace** [comment]
I'm able to replicate this in my app with Ember CLI versions 2.10.0, 2.11.0 and 2.12.1. I also tried removing a bunch of dependencies, and going back several months in git, but I wasn't able to find a configuration that didn't exhibit the 'full reload' issue. I'm kind of at my time limit for looking into this, but I'm going to try upgrading deps in my `package.json` and see if that fixes it.

**Comment by henrymazza** [comment]
Partial reload never worked for me. Today I took the day to make some refactors and dig this out.

In my case I found it was the fingerprinting done by Broccoli-asset-rev that was touching every file under the sun and causing the issue. I was relying on it to prepend different asset dirs for development and production. Had to tackle the problem on a different way.

**Comment by stefanpenner** [comment]
Will gladly reopen if a reproduction (as requested) is provided.

**Comment by toranb** [comment]
@stefanpenner late to the party I know ;) but I did get close(r) to the bottom of this one. I wanted to see if I could supply some missing details and get your help later in the week 

1) I found debugging in the browser (during the live-reload WS* push event) that a single line scss change would alert the livereload client about app.css/vendor.css *AND* index.html/ tests/index.html

https://github.com/ember-redux/redux-and-engines/commits/branches/emberCLI
![screen shot 2017-09-26 at 8 07 10 pm](https://user-images.githubusercontent.com/147411/30891836-0ae10686-a2fb-11e7-8cb9-8fa0f46795d6.png)

Because index.html isn't css ... the client code eventually hits the bottom of our conditional(s) in `reload` so the method `reloadPage` is invoked (root cause for our friend the full page refresh).

![screen shot 2017-09-26 at 8 43 45 pm](https://user-images.githubusercontent.com/147411/30891957-910365d8-a2fb-11e7-8288-f1dc4b9c60ad.png)

2) next I dove into the ember-cli source for `tasks/servers/livereload-server.js`

https://github.com/ember-cli/ember-cli/blob/503ede1fcb5224d54dc36f82af84550a91d90f26/lib/tasks/server/livereload-server.js#L146

![screen shot 2017-09-26 at 8 47 55 pm](https://user-images.githubusercontent.com/147411/30892033-0332103c-a2fc-11e7-938b-e19af975eebc.png)

**Comment by toranb** [comment]
Ah this looks to be engines (ember asset loader) related

https://github.com/ember-engines/ember-asset-loader/issues/49
