### ISSUE TITLE
Context-aware generators

### ISSUE THREAD

**Issue by myartsev** [ember-cli/ember-cli#7062]
Easiest to explain this with a concrete example.
While developing an add-on, let's call it *ember-foo-addon*, I found myself needing to generate a route for the dummy test app.

Running `user@machine:~/code/ember-foo-addon/tests/dummy$ ember g route index` will create templates for the addon itself, under **/code/ember-foo-addon** instead of **/code/ember-foo-addon/tests/dummy**

I haven't worked with Ember long enough to run into other cases where this kind of behaviour might be valuable.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.13.1
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 56.1
modules: 48
openssl: 1.0.2k
os: linux x64
3.10.10
```

**Comment by stefanpenner** [comment]
In an add-on you may want to generate for the addon, or for the dummy app. We default to the addon (since your are in the addon) but allow your to opt into generation for the dummy app via the `--dummy` flag

```js
ember g --dummy route index
```

for more details:

```js
ember help g
```

---

I believe ^ addresses this issue, so I am closing. But if I misunderstood, help my understand why and I can gladly reopen.
