### ISSUE TITLE
Yarn workspaces

### ISSUE THREAD

**Issue by bsvipas** [ember-cli/ember-cli#7335]
Hi, it doesn't work correctly with Yarn workspaces... Here is the issues: https://github.com/yarnpkg/yarn/issues/4503 (same as https://github.com/yarnpkg/yarn/issues/4081). All other apps works fine, they search for `node_modules` in root dir instead of current dir if they don't find it, but Ember just search it in current dir...

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
Ember: 2.15.1
NPM: 5.4.2
Yarn: 1.0.2
```

**Comment by bsvipas** [comment]
This issue is related with `ember-cli-dependency-checker`. I fixed it and right now I need to polish it and I will try to make PR.

**Comment by ef4** [comment]
Yes, ember-cli itself has a baked-in very bad assumption: the Project model has a `nodeModulesPath` property containing a single directory name. It's used both internally by ember-cli and by ember-cli-dependency-checker.

It's a bad assumption because node's module resolution algorithm doesn't work that way. There's no such thing as "the" node_modules directory. You can have many of them, and yarn workspaces uses this to great effect.

Fixing this will simplify ember-cli, because it has a bunch of code for trying to outguess node that can just be ripped out. The correct solution is to just use [resolve](https://www.npmjs.com/package/resolve) to look up modules relative to the project root.

**Comment by lennyburdette** [comment]
@ef4 have you looked into yarn.lock file resolution as well? Some parts of Ember CLI assume that yarn.lock must exist in the Ember project root, but in a workspace the file will exist in the workspace root.

[Yarn's algorithm](https://github.com/yarnpkg/yarn/blob/master/src/config.js#L612) for finding the workspace root is somewhat straight-forward. Do you think it makes sense to port that into Ember CLI as a utility function for these three places?

[tasks/npm-task.js](https://github.com/ember-cli/ember-cli/blob/446f87bb63c8f9725920cfd9788396dcab14a911/lib/tasks/npm-task.js#L44)
[commands/init.js](https://github.com/ember-cli/ember-cli/blob/eef7317152576ee47d38fb6bbc3edd73b37c4ca4/lib/commands/init.js#L64)
[models/command.js](https://github.com/ember-cli/ember-cli/blob/d562bd36a653ae182ddc7fb1fa71a5fd83f26e0a/lib/models/command.js#L293)

cc @rwjblue

**Comment by stefanpenner** [comment]
ya, anything thats sideways about our existing integration (not respecting the node resolution algo etc) should be fix. big +1

**Comment by lennyburdette** [comment]
@stefanpenner here's a PR to help Ember CLI understand when it's part of a yarn workspace: https://github.com/ember-cli/ember-cli/pull/7464

**Comment by thetimothyp** [comment]
Updated PR for this issue: #7492

**Comment by acorncom** [comment]
It looks like this issue can be closed?

**Comment by ef4** [comment]
I think yes.

There are still plenty of addons floating around that will give warnings about nodeModulesPath (and therefore potentially do broken things in yarn workspaces), but I think all the core fixes are in.
