### ISSUE TITLE
Remove emoji alias

### ISSUE THREAD

**Issue by tristanpemble** [ember-cli/ember-cli#7426]
Re: #6928 

The fact that Yarn's output includes a hamster emoji that I cannot ignore, has unearthed a bug in our deployment tooling. It does not handle unicode output well, and since we cannot block the output of the emoji in our `yarn install` like is automatically done via https://github.com/yarnpkg/yarn/issues/405 , this has blocked my team.

I am submitting a bug report to the tool we are using to request that it properly handle the Unicode output. That said, and I don't want to be a party pooper, but forcing all tooling to support unicode output over a fun hamster emoji alias seems non-ideal.

**Comment by kellyselden** [comment]
Seems like a valid enough reason to remove to me.

**Comment by rwjblue** [comment]
I think we are generally happy to land a PR that does this (we should change the PR to target the beta branch at least, so that 2.17.0 will include the required fixes). 

> forcing all tooling to support unicode output over a fun Hamster emoji alias seems non-ideal

All CI related tooling _should_ already support unicode output or its _probably_ not worth using. There are more languages in the world than those that can be written in ASCII... 😄

**Comment by tristanpemble** [comment]
I agree; this is not a situation I'm happy to be in 😛

**Comment by kellyselden** [comment]
fixed in #7427
