### ISSUE TITLE
The 'tmp' folder in the project root causes the typescript compiler to consume 100% cpu

### ISSUE THREAD

**Issue by pieter-v** [ember-cli/ember-cli#7730]
We use ember-cli-typescript to compile our typescript source files. As described in https://github.com/typed-ember/ember-cli-typescript/pull/172, rebuilds can take a very long time. It is not only ember-cli-typescript that suffers from this performance issues, 'Visual Studio Code' has the same problem. 
It is bassically 'tsc --watch' that consumes 100% cpu.

---

Output from `ember version --verbose &&  yarn --version`:
```
ember-cli: 3.0.2
http_parser: 2.8.0
node: 8.11.1
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: darwin x64
1.5.1
```

**Comment by rwjblue** [comment]
This seems pretty unlikely to be an ember-cli issue. My best guess would be that your tsconfig.json doesn't exclude `tmp` properly, but thats just a WAG.

I'd suggest checking in with the ember-cli-typescript folks...

**Comment by pieter-v** [comment]
Our tsconfig.json excludes the 'tmp' folder. But typescript still watches the files in the 'tmp' folder for module resolution (the tracing of typescript contains almost nothing but 'Directory of Failed lookup locations in module resolution' messages).

The PR in ember-cli-typescript#172 provides a solution for ember-cli-typescript (by not using the typescript compiler in watch mode), but other IDE's (WebStorm, code) still suffer from this problem.

So, I agree that it is not an ember-cli issue, but ember-cli could provide the solution, by moving the 'tmp' folder out of the project root. 
The extra advantage of this approach is that a user doesn't have to exclude the 'tmp' folder from his IDE, revision control system,...

**Comment by runspired** [comment]
It’s trivial to exclude it from watching in WebStorm, and the WebStorm ember plugin does it for you automatically. Someone should make one for vscode.

**Comment by runspired** [comment]
I looked at the proposed fix and the config (here https://github.com/typed-ember/ember-cli-typescript/blob/master/blueprints/ember-cli-typescript/files/tsconfig.json) and neither is properly excluding any folders from watching.

**Comment by rwjblue** [comment]
> So, I agree that it is not an ember-cli issue, but ember-cli could provide the solution, by moving the 'tmp' folder out of the project root.

Yep, totally agree! We are working towards moving `tmp` to the default system tmp folder location.

**Comment by dfreeman** [comment]
I've been excitedly watching the progress on the Great Broccoli Reconvergence to get `tmp` out of the project directory, but also agreed that this is probably an issue to track with ember-cli-typescript rather than here.

> neither is properly excluding any folders from watching.

@runspired can you elaborate?

The current suggested setup is the result of a lot of experimentation by a number of people and a fair amount of code spelunking in `tsc` by @dwickern to try and minimize the problem at hand. The ultimate conclusion I believe Derek came to (which matches my own anecdotal experience) is that a big portion of the CPU churn is actually the typescript compiler cycling through the excluded files in `tmp` to _determine_ that they are, in fact, excluded.

This is total speculation, but my _guess_ is that the complexity of the interactions between `include`, `exclude` and `files` in `tsconfig.json` have led to an implementation in `tsc` that doesn't trivially filter out entire directory trees at the root.

**Comment by chriskrycho** [comment]
To add to @dfreeman's comments: we've gone the route of explicitly excluding the `tmp` directory, and it didn't actually affect the compiler's behavior _at all_, which was deeply frustrating, to say the least.

**Comment by krisselden** [comment]
Last time I checked it was the tsserver that does this, and using files of entry points instead of include/exclude works better, another is to set a root folder.  Basically look at https://github.com/Microsoft/TypeScript/blob/cbbe34b35e548fa282ff18b3d9111e5963ea4bca/src/server/project.ts and what directories are watched.  It watches all globs directories and ** is watched recursively, and excludes aren't consulted as far as I can tell.  So doing, **/*.ts is just going to watch the whole project recursively.

**Comment by bartocc** [comment]
Just like @ssnielsen, I ended up here after googling `Directory of Failed lookup locations in module resolution` from the `tsserver.log` generated by `VSCode Insiders`.

My project contains the follwing `jsconfig.json`, and as you can see, `tmp` is part of the`exclude` array.

```json
{"compilerOptions":{"target":"es6","experimentalDecorators":true},"exclude":["node_modules","bower_components","tmp","vendor",".git","dist"]}
```

I also agree that this does not seem to be an ember-cli issue, but that ember-cli *could* fix this behavior some of us encounter by moving `tmp` out of the projet's root.

> Yep, totally agree! We are working towards moving tmp to the default system tmp folder location.

@rwjblue, could you point us to some epic issue about this work in progress?

At the moment, I have no workaround for this except regularly restarting the tsserver with my editors's `Restart TS Server` command…

If anyone has a better solution, I'd be very happy to hear about it 😄

**Comment by rwjblue** [comment]
A large step forward on moving `tmp` out of the project landed yesterday in https://github.com/ember-cli/ember-cli/pull/7798. At the moment, you can try this out by using the master branch of `ember-cli` and running:

```
EMBER_CLI_BROCCOLI_2=true EMBER_CLI_SYSTEM_TEMP=true ember serve
```

I am unsure if there is a more specific tracking issue for enabling those two experiments by default...

**Comment by bartocc** [comment]
thx a lot @rwjblue for pointing us to those feature flags!

@chriskrycho, I recall trying some of those configs, but at that time I had not clearly identified the tsserver issue. I'll try again and see how it affects the CPU issue. Thx!

**Comment by pieter-v** [comment]
Latest ember-cli moves the `tmp` folder to `system tmp`
This solves this issue.
Thanks

**Comment by jenweber** [comment]
We discovered that `ember test` was still creating temporary directories, which caused the TypeScript compiler issue again. This is addressed in https://github.com/ember-cli/ember-cli/pull/8642
