### ISSUE TITLE
config/targets.js excludes IE11 for dev builds, leading to different transpiled code for CI/Prod environments

### ISSUE THREAD

**Issue by localpcguy** [ember-cli/ember-cli#7790]
I had tests that only failed on our CI environment, and after much debugging, found it was related to the `config/targets.js` file excluding IE11 as a build target for anything other than CI/PROD. 

I feel like this is a mistake as the default option, and will lead to errors in Production that may never be encountered in development or test/staging environments due to the differing build targets and different transpiled code when IE11 is included vs. when it is excluded. This also means devs cannot test locally on IE11 (yes, some of us still have to do that 😿 )

It is simple to fix once you figure out what is happening (just move IE11 into the build targets for dev and remove the conditional lines from the `config/targets.js` file that check for CI/Prod.)

I understand some of the reasoning for leaving it out was to allow native async/await functionality, but to me the danger of different code in dev/prod is a great risk (and less expected) and would outweigh the benefits of having native async/await by default. Any dev that wants to exclude IE11 can do so, and I think we could have blog posts or instructions on the pros/cons of doing so.

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.0.2
http_parser: 2.7.0
node: 8.4.0
v8: 6.0.286.52
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.22.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.8.0
1.6.0
```

**Comment by localpcguy** [comment]
Another workaround that was suggested to me was to run `CI=1 ember s` whenever you need to test or debug IE11 specific issues. Just wanted to note that here in case it helps someone else.

**Comment by rwjblue** [comment]
I’m sorry you had trouble with this! I totally agree that we need to have better documentation and mentions of this throughout the guides and api docs. Possibly even print out the list of targets being used to the console when we start up. 

Ultimately, I disagree with your conclusion that the costs of potentially having issues due to the difference in local transpilation vs production outweigh the benefits of running code much closer to what you actually wrote. 

The arguments you laid out would also suggest that you do things like fingerprinting and minification in local development builds (which also seems like a non-starter to me).

**Comment by localpcguy** [comment]
In my mind, transpilation is fundamentally different that fingerprinting and minification. I tend to trust fingerprinting (tiny risk IMO) or minification (mild risk IMO) way more than transpilation (that could just be me though, ha).

If nothing else, hopefully just having this issue (even if the code in the `targets.js` file doesn't change) could help people running into this issue to resolve it quicker.

**Comment by rwjblue** [comment]
Minification _is_ transpilation. The goal isn’t “polyfilling new syntax” but is instead “make this tiny”, but it is exactly the same thing.

I totally agree that we trust tools like uglify and consider them “different” than babel/typescript but the only reason they are rock solid today is because when we had pain and then we addressed it.  

I do appreciate you bringing this up. Thank you for filing such a well thought out issue.

**Comment by localpcguy** [comment]
After this discussion, this is how I ended up resolving it in our codebase (basically added a noIE flag to disable IE, but left the default state to include IE). I plan to run with the noIE flag enabled most of the time since debugging async/await IS that much nicer. 

```
const browsers = [
  'last 1 Chrome versions',
  'last 1 Firefox versions',
  'last 1 Safari versions',
  'last 1 Edge versions'
];

const isCI = !!process.env.CI;
const isProduction = process.env.EMBER_ENV === 'production';
const excludeIE = !!process.env.noIE;

if (isCI || isProduction || !excludeIE) {
  browsers.push('ie 11');
}

module.exports = {
  browsers
};
```
