### ISSUE TITLE
Remove `ember-cli-eslint` as a dependency

### ISSUE THREAD

**Issue by sangm** [ember-cli/ember-cli#7975]
I don't believe there's much value in having `ember-cli-eslint` as a dependency. We should advocate `eslint` through (1) editor integrations and (2) precommit-checks

This will simplify the eslint process _and_ have the potential to make builds/rebuilds faster.

Thoughts @rwjblue @stefanpenner @scalvert

**Comment by sangm** [comment]
I guess this proposes a separate, but related question: should `ember-cli` come with something like https://github.com/typicode/husky so precommit hooks are easily integrated?

**Comment by kellyselden** [comment]
We have discussed this at the last team meeting. Consensus is the benefit is worth it, since it slows the build and doesn't cover the non-ember files we lint. It might be a worth an RFC, not sure.

**Comment by sangm** [comment]
hey @kellyselden 

Benefit is worth _what_? (Keeping or removing)

**Comment by sangm** [comment]
Great 🔥 

In terms of needing a RFC or not, this is ambiguous. How do we make progress on this?

**Comment by kellyselden** [comment]
I would say someone can create one and we can fast-track it.

Pros:
* console warnings on build
* included in browser tests

Cons:
* slow builds
* ember-cli-eslint has some interesting hacks that limit how much it can be improved, and also limit improvements to ember-cli (@rwjblue is the expert on this)
* forever incomplete because it only knows about ember code, not ember-cli build code.

**Comment by sangm** [comment]
Have an initial draft of the RFC here: https://github.com/ember-cli/rfcs/pull/121

**Comment by kellyselden** [comment]
The RFC was merged, and there's a start of a PR here https://github.com/ember-cli/ember-cli/pull/8219.
