### ISSUE TITLE
CSS is minified in production builds by default

### ISSUE THREAD

**Issue by kanongil** [ember-cli/ember-cli#8359]
In the cli guide [here](https://ember-cli.com/user-guide/#minifying), it is asserted that css is minified when either `broccoli-clean-css` or `broccoli-csso` is installed locally. However, an app without any of these dependencies listed, _surprisingly minifies_!

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.5.0
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
6.4.1
1.10.1
```

**Comment by rwjblue** [comment]
This is due to ember-cli-preprocessor-registry itself bringing the behavior. I completely agree that we want to move that to a real addon instead of being out of control of the host app. To that end, I refactored ember-cli-preprocessor-registry to drop the built in functionality and started authoring ember-cli-clean-css addon (though I apparently got distracted and never finished implementation and rollout)...

**Comment by Turbo87** [comment]
closing in favor of https://github.com/ember-cli/ember-cli/issues/8457
