### ISSUE TITLE
clean-css dependency needs updating 

### ISSUE THREAD

**Issue by MelSumner** [ember-cli/ember-cli#8579]
After updating my ember version today (`npm install -g ember-cli`), I created a new app (`ember new my-ember-app`) and after switching to the directory, I ran `npm install` to install the dependencies. 

This is the message that was printed out in the console-
![image](https://user-images.githubusercontent.com/4587451/55908050-02b6b700-5b9e-11e9-8b47-ece82081bac8.png)

Seems like clean-css needs an updated version. 

Thanks!

**Comment by amk221** [comment]
There is a vulnerability in clean-css

https://github.com/jakubpawlowicz/clean-css/commit/2929bafbf8cdf7dccb24e0949c70833764fa87e3

```
npm ls clean-css
foo@0.0.0 /src/example-ember-app
└─┬ ember-cli@3.10.1
  └─┬ ember-cli-preprocess-registry@3.3.0
    └─┬ broccoli-clean-css@1.1.0
      └─┬ clean-css-promise@0.1.1
        └── clean-css@3.4.28
```

**Comment by amk221** [comment]
I realise this is probably a minor issue, but I'm it isn't getting more attention. Surely as soon as a vulnerability is reported by an audit, it should be prioritised.

**Comment by caljess599** [comment]
I agree--I don't like seeing critical vulnerabilities...

**Comment by gorner** [comment]
Trying to connect the dots for anyone who comes across this, after some difficulty trying to figure it out myself:

Bumping clean-css was attempted in https://github.com/ember-cli/ember-cli-preprocess-registry/pull/27. However it was discovered to be a breaking change due to changes in the settings options in clean-css v4 (see comments) and was reverted in https://github.com/ember-cli/ember-cli-preprocess-registry/pull/55.

Per the discussion at https://github.com/ember-cli/ember-cli-preprocess-registry/issues/50 it appears this would be deemed a breaking change for ember-cli as well. So this is probably not going to be fully resolved before ember-cli v4.

Finally, per @Turbo87's comment at https://github.com/ember-cli/ember-cli/issues/8626#issuecomment-501376912, this is a build-time dependency only (which does not minimize the importance of fixing when possible, but in combination with the SemVer concerns above, might affect why it isn't being dealt with more immediately).

If you still want to fix this for the time being, I've found you can do so in Yarn by locking ember-cli-preprocess-registry to v3.2.1 in resolutions (or alternatively upgrading one of the other intermediate packages), and then making whatever (if any) changes are needed to `minifyCSS` in ember-cli-build.js to satisfy the [breaking v3-to-v4 changes in clean-css](https://github.com/jakubpawlowicz/clean-css#important-40-breaking-changes). However, at least for ec-preprocess-registry, this will raise a compatibility warning in Ember-CLI 3.12+.

**Comment by Gaurav0** [comment]
Is it possible to get clean-css to release a patch for v3?

**Comment by panthony** [comment]
I'm using Ember 3.24. and with TailwindCSS.

Recently I upgraded to TailwindCSS 3.X and noticed weird CSS issues (ex: Ring feature not working anymore) that is linked to the minifyCSS.

Tried to disable all advanced [features](https://github.com/clean-css/clean-css/tree/v3.4.28#how-to-use-clean-css-api) from clean-css with no luck.

I finally stumbled upon issues such as [this one](https://github.com/clean-css/clean-css/issues/1180#issue-977284264) that might resolve my problems.

Just adding another perspective that upgrading clean-css might be good not simply for vulnerabilities but also because they are bugs that are not necessary simple to detect and correct.

**Comment by boris-petrov** [comment]
I personally have:

```json
    "broccoli-clean-css": "3.0.0-2",
    "clean-css": "5.2.2"
```

In `resolutions` in `package.json`. Works only on `yarn` but does the job.

**Comment by panthony** [comment]
Thanks for pointing in this direction! Apparently latest version of `npm` has a similar feature called [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)

**Comment by kategengler** [comment]
`clean-css` is no longer a dependency of `ember-cli-preprocess-registry`, however, `ember-cli-clean-css` is now included by default and uses this same version of clean-css that has the vulnerability. A new version of `ember-cli-clean-css` with updated `clean-css` needs to be released once it is confirmed it produces working css (a problem when it was attempted before). When that happens, users can update clean-css as it suits them, as the output changes across major versions.

**Comment by bertdeblock** [comment]
Fixed => https://github.com/ember-cli/ember-cli-clean-css/releases/tag/v3.0.0.
