### ISSUE TITLE
Request: provide way to set language attribute when spinning up a new app

### ISSUE THREAD

**Issue by MelSumner** [ember-cli/ember-cli#8599]
When I create a new Ember app, I have this accessibility issue immediately: 

![image](https://user-images.githubusercontent.com/4587451/56380674-6b261980-61d8-11e9-92c8-a02778185c37.png)

One solution would be to change `<html>` to `<html lang="en">`,  but perhaps we could also do something more inclusive. Would there be a way to have a language set by default but make setting a different language available via an option in `ember new`?

Thank you for considering.

**Comment by rwjblue** [comment]
TBH, I don't think there is a reasonable way for us to default this. Adding "yet another" flag you have to remember to `ember new` is not good, and using `"en"` as the default seems fundamentally wrong to me.

See https://github.com/ember-cli/ember-cli/pull/7207 for some previous conversation about it.

One possibility is to ensure that `lang` is added by the user (via either an automatic test included in the app, a lint rule, etc). This _kinda_ sucks too (generating a new app with failing tests feels bad), but at least doesn't default to excluding non-english folks...

**Comment by mehulkar** [comment]
One thing my team has considered in the past is to build per locale so that we can precompile localized templates instead of fetching translations at runtime. Instead of at `ember new` time, if we built this into `ember build`, those builds could add the `lang` attribute?

I'm thinking something like `ember build --lang "en"` or `ember build --languages config/locales.js`.

(Discovered this while reading [learning team meeting notes](https://github.com/emberjs/core-notes/blob/master/learning-team/2019-06/june-06.md#main-html-element))

**Comment by stefanpenner** [comment]
@rwjblue I don't think defaulting to `en` is an issue. In-fact our welcome page is clearly written in english today.  Would would make it more honest than anything.

Until such time as we want to bake in some broader i18n solution, defaulting to `en` is fine.

**Comment by MelSumner** [comment]
@rwjblue @stefanpenner I'd like to have this issue closed as a won't fix or work on a way to move this forward, please.
