### ISSUE TITLE
Engines field does not match policy

### ISSUE THREAD

**Issue by chriskrycho** [ember-cli/ember-cli#8628]
The version currently specified in `package.json` is:

```
  "engines": {
    "node": "8.* || >= 10.*"
  }
```

The [official policy](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md) – and warnings from the CLI! – specify that Node 11 and 12 are not currently supported. The version range should match the supported version range, e.g. as `"8.* - 10.*`

(This is helpful for tools which use the engines field, e.g. [Notion](https://notionjs.com).)

**Comment by rwjblue** [comment]
@chriskrycho - The warnings when using Node 12 state that we do not **test** with Node 12, not that it is unsupported:

```
WARNING: Node v12.1.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
```

Also note that the node support document you linked only lists LTS node versions (which is why 11 isn't listed/mentioned), and the warning suggests using the most recent LTS (which is currently v10).

**Comment by rwjblue** [comment]
I have recently added Node 12 to the test matrix (https://github.com/ember-cli/ember-cli/pull/8631), which will remove the warning for Node 12 usage (and Node 11 was added in the 3.10 cycle).

That change should be included in 3.8.x, 3.9.x, 3.10.0+ (and those versions should not emit errors on Node 12 once published).

**Comment by chriskrycho** [comment]
Ah, I understand now; thanks for the clarification!

Any thoughts on what Notion should do here? The preference would be to install the *recommended* version rather than one that will print a warning; but it's not obvious to me whether that's even possible from the `package.json`. (Apart from specifying a `toolchain` key for Ember CLI itself, which is a bigger ask!)

**Comment by rwjblue** [comment]
> Any thoughts on what Notion should do here?

I think in general, the right default thing to do from a notion/volta perspective would be to strongly lean towards the most recent LTS version (not the highest absolute version) that fits within the specified engines range. LTS versions are not coined until they have been out "for a shakedown cruise", and are much less likely to have issues like this (since the community at large would have absorbed the problems in the 12.x series before it became LTS).

Happy to move this discussion to a notion/volta issue thread also...

**Comment by chriskrycho** [comment]
Just realized I left this open for ages. I believe we came up with a good solution here on the Volta side a long time ago, so closing this.
