### ISSUE TITLE
beta broccoli watcher issue

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#8677]
(paired with @thoov)

On beta, introduced by: https://github.com/ember-cli/ember-cli/pull/8666 we have  introduced a breaking change. Specifically the meaning of `watcher.on('change'` has changed breaking https://github.com/lifeart/ember-ast-hot-load.

To reproduce:

1. first checkout `ember-ast-hot-load`
2. then link the beta branch of ember-cli
3. then run:

```
EMBER_CLI_BROCCOLI_WATCHER=true BROCCOLI_ENABLED_MEMOIZE=true ember s
```

4.  With the network tab open:
mutate `tests/dummy/app/templates/components/template-only.hbs`

You should only see `dummy.js` being loaded, and the result column of `template-only` being updated, but currently you see a full page reload.

Additionally when switching from `on('changes'` to `on('buildSuccess` we see only the `dummy.js` being refetched, but the UI isn't updating correctly. This leaves me to believe something else might be off.

Finally, when running CLI without `EMBER_CLI_BROCCOLI_WATCHER=true BROCCOLI_ENABLED_MEMOIZE=true` set, all appears to function correctly.

---

Thanks @lifeart for reporting this issue so quickly!

cc @oligriffiths

**Comment by stefanpenner** [comment]
@thoov can you take a look?

**Comment by stefanpenner** [comment]
more context: https://github.com/ember-cli/ember-cli/pull/8674

**Comment by lifeart** [comment]
how it's working before (my expectation)

- `watcher.on('change'` emit changed source files (like my-component/template.hbs)
- `ast-hot-load` send this names to service, and service check components usage (my-component), if found - it send check to server.
- once bundle updated, live-reload server send responce back to browser, and our server make request for partial js (addon use middleware to extract component definition from app/vendor.js bundle.)
- some hot-reload magic on page

now, as I understand - `watcher.on('change'`  emit build output (bundle files, instead of sources), so it may be root cause

**Comment by stefanpenner** [comment]
@lifeart makes sense, thanks for the details!

**Comment by thoov** [comment]
The issue is that the object emitted from the change event changed from:

```
{
  directory: "/var/folders/61/n399scw50nq264t..."
  filePath: undefined
  graph: TransformNodeWrapper {buildState: {…} …}
  outputChanges: (15) ["assets/dummy.css", "assets/dummy.js", ...]
  totalTime: 944093539
}
```

To: 

```
{
  directory: "/var/folders/61/n399scw50nq264t..."
  graph: TransformNodeWrapper {buildState: {…} …}
  outputChanges: (15) ["assets/dummy.css", "assets/dummy.js", ...]
  totalTime: 944093539
}
```

The difference being that `filePath` is no longer there. This causes issues with: https://github.com/lifeart/ember-ast-hot-load/blob/master/lib/hot-reloader.js#L51. This `filePath` property came from https://github.com/ember-cli/broccoli-sane-watcher/blob/ember-cli/index.js#L92-L95 which does not exist in broccoli's watcher.

I will create a PR for broccoli to add this tomorrow

cc: @stefanpenner, @lifeart, @oligriffiths

**Comment by stefanpenner** [comment]
@thoov's fix: https://github.com/broccolijs/broccoli/pull/409 (pending some discussion/code-review)
