### ISSUE TITLE
How to make dynamic loading css?

### ISSUE THREAD

**Issue by JeanRasin** [ember-cli/ember-cli#8776]
Hello. It is necessary to make dynamic loading of js and css. I made js using ember-auto-import. But css fails. I use yarn and want to load via app.import, but bower and the bower_components folder are used everywhere. I also planned to upload a separate my.css file, and not as part of vendor.css. But when I do app.import (path + 'leaflet.css', {destDir: '/ assets'}) it pops it into the vendor.css file. How to take files from node_modules using app.import? And how to move files to the assets folder if they are css and whatever they fall into vendor.css?

**Comment by ef4** [comment]
If you want to `app.import` CSS into a file other than `vendor.css`, pass the `outputFile` option to `app.import`:

```js
app.import (path + 'leaflet.css', { outputFile: 'leaflet.css' })
```

Alternatively, if your CSS is a file stored within your project already anyway, just move it into the `public` folder and then you don't need to do anything special to make sure it will be present in the final built application.

**Comment by rwjblue** [comment]
Hello @JeanRasin! In general we try to keep this issue tracker dedicated to actual bugs in ember-cli itself. This issue seems more like a question better suited for StackOverflow or our [Discourse forum](https://discuss.emberjs.com), you will almost certainly have more feedback / answers there than here. When you do create the other thread please comment here to share the link to your SO / Discuss post so folks stumbling across this issue can follow along.

Sorry for the trouble, and good luck!

**Comment by JeanRasin** [comment]
I apologize for writing the wrong way.
But the error is still there.
If the bower_components or "vendor" folder is used, then everything works, but if the node_modules folder or their error occurs.
![image](https://user-images.githubusercontent.com/17027319/62599050-9e65f300-b904-11e9-8f48-c860ed1145d4.png)
![image](https://user-images.githubusercontent.com/17027319/62599077-a9208800-b904-11e9-9f96-a03776dde41b.png)

**Comment by JeanRasin** [comment]
Solved a problem. It was necessary to raise the version of ember-cli from 2.14 to 2.15.1. The project posted [here](https://github.com/JeanRasin/ember-flexberry-gis-auto-import).
