### ISSUE TITLE
Sync beta blueprints with octane blueprints

### ISSUE THREAD

**Issue by chancancode** [ember-cli/ember-cli#8872]
This is the inverse of https://github.com/ember-cli/ember-octane-blueprint/issues/170. By the time 3.14 ships, we need them to be basically the same. Right now, the most notable omission is `ember-auto-import` in the beta blueprints.

**Comment by kellyselden** [comment]
Would that be RFC worthy? I'm not up to speed with that project, but I remember things like a non trivial build speed reduction, and making sure it matches your Babel config or else errors. Would the guides be prepared to teach this in time for octane? (Instead of app.import and in repo add-on shims)

**Comment by Panman8201** [comment]
FYI, I've submitted #8873 which completes this task.
