### ISSUE TITLE
In repo component generator creates colocated components

### ISSUE THREAD

**Issue by lvegerano** [ember-cli/ember-cli#9011]
Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 3.14.0
node: 12.14.0
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1
os: darwin x64
6.13.4
1.17.3
```
`ember g component foo-bar -gc -ir calendar` creates colocated components in in-repo addons which I was told is not supported.

**Comment by rwjblue** [comment]
> which I was told is not supported

Nope, this should work just fine. The only issue with addons using colocated templates is that they can't always assume that the host application will be running Ember 3.13 or higher, but that concern is moot with an in-repo addon since it is fundamentally tied to the version of Ember that the app itself uses.
