### ISSUE TITLE
live-reload URL should be attached at the rootURL, rather than the root (/)

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9278]
Output from `ember version --verbose && npm --version && yarn --version`:
```
$ ember version --verbose && npm --version && yarn --version
ember-cli: 3.12.0
node: 12.18.1
v8: 7.8.279.23-node.38
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
os: linux x64
6.14.5
1.22.4
```

today, the live-reload URL is `/_lr/` But with apps that rely on proxies for development, there may be collisions between different root `/_lr/` routes when multiple apps are running and live-reload is desired.

for example, if rootURLs are configured in two apps:
`/foo/` and `/bar/`
they have the same live-reload URL.

**Comment by rwjblue** [comment]
Ya, agreed. I think the issue is here:

https://github.com/ember-cli/ember-cli/blob/47479563fafd2147fb056e3d23335d7b610eafaf/lib/tasks/server/livereload-server.js#L120-L126

To fix, that should be something like:

```js
    let serverOptions = {
      app: this.app,
      dashboard: 'false',
      prefix: this.liveReloadPrefix,
      port: options.port,
    };
```

And then the command should be updated to ensure that the default value is `${rootURL}/_lr/`. In order to do that, we'd need to remove the default value here:

https://github.com/ember-cli/ember-cli/blob/47479563fafd2147fb056e3d23335d7b610eafaf/lib/commands/serve.js#L63

Then update the `run` method to do something like:

```js
if (options.liveReload === true && options.liveReloadPrefix === undefined) {
  let config = this.project.config(options.environment);
  let rootURL = cleanBaseUrl(config.rootURL);

  options.liveReloadPrefix = `${rootURL}_lr`;
}
```

And we'd need a test like this one, but with a `rootURL` set:

https://github.com/ember-cli/ember-cli/blob/47479563fafd2147fb056e3d23335d7b610eafaf/tests/unit/tasks/server/livereload-server-test.js#L94-L108

**Comment by NullVoxPopuli** [comment]
Thanks for the pointers! :D

**Comment by rwjblue** [comment]
FWIW, I think this should non-trivially help in hosted environments (e.g. code sandbox)...
