### ISSUE TITLE
Replace deprecated babel-eslint with new @babel/eslint-parser

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9307]
This is mostly a tracking issue as I am not in a place to open a PR for this atm, but,

here in the app blueprint: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L29
we're still using babel-eslint,
but, per, https://github.com/babel/babel-eslint, the eslint parser for babel has moved into their monorepo as https://github.com/babel/babel/tree/master/eslint/babel-eslint-parser

**Comment by SergeAstapov** [comment]
I would assume biggest show-stopper here is

> @babel/eslint-parser requires `@babel/core@>=7.2.0` and a valid Babel configuration file to run. If you do not have this already set up, please see the [Babel Usage Guide](https://babeljs.io/docs/en/usage).

because Ember CLI projects do not have dedicated Babel configuration file and may use ember-cli-babel@6.

**Comment by bmish** [comment]
I started an implementation in #9532:
* I think we can use `requireConfigFile: false` to avoid needing a Babel config file
* But I'm not sure what to do about the requirement for having @babel/core v7+ as a peer dependency since we don't include Babel as a dependency in the blueprint at all right now...

**Comment by tehhowch** [comment]
> we don't include Babel as a dependency in the blueprint at all right now

Perhaps not explicitly, but the default blueprint adds it to new projects. It shouldn't be a surprise to users, either, as the Ember CLI [intro](https://guides.emberjs.com/release/getting-started/quick-start/) explicitly states 
> Out of the box, your application will include:
>  -   A development server.
>  -  Template compilation.
>  -  JavaScript and CSS minification.
>  -  **Modern features via Babel.**

If one runs `ember new my-app`, the resulting package lockfile requires `@babel/core` due to embroider, broccoli-babel-transpiler, ember-auto-import, ember-cli, ember-cli-babel, and workerpool.

So moving it into package.json as a devDep or peerDep will just now be explicitly stating the dependency exists, rather than it being a transitive dependency.

**Comment by bmish** [comment]
@tehhowch great point! In fact, I just noticed that a bunch of other dependencies in a fresh Ember app already have an unmet peer dependency on @babel/core, so I think we can ignore this given that it's most certainly a transitive dependency (and I think ember-cli-babel is intended to be a wrapper around / manage the version of @babel/core anyway). CC: @rwjblue 

```
warning "ember-resolver > babel-plugin-debug-macros@0.3.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "ember-maybe-import-regenerator > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42".
warning "ember-source > @babel/plugin-transform-block-scoping@7.14.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@glimmer/component > ember-cli-typescript > @babel/plugin-transform-typescript@7.5.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-data > @ember-data/private-build-infra > ember-cli-typescript > @babel/plugin-transform-typescript@7.8.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-load-initializers > ember-cli-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "ember-source > @babel/plugin-transform-object-assign@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
```

I have moved my PR #9532 into ready-for-review.

**Comment by ctjhoa** [comment]
Another PR https://github.com/ember-cli/ember-cli/pull/9669
