### ISSUE TITLE
Function in `ember-cli-build.js` or `environment.js` config causes `DataCloneError`

### ISSUE THREAD

**Issue by emattias** [ember-cli/ember-cli#9357]
The addon [ember-cli-workbox](https://github.com/BBVAEngineering/ember-cli-workbox) `importScriptsTransform` option crashes the build with a [DataCloneError](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#Things_that_dont_work_with_structured_clone:~:text=to%20throws%20a-,DATA_CLONE_ERR):

```
internal/worker.js:279
    this[kPublicPort].postMessage(...args);
                      ^

DOMException [DataCloneError]: (importScripts) => {
      return importScripts.map((importScript) => {
        return ...<omitted>... } could not be cloned.
    at Worker.postMessage (internal/worker.js:279:23)
```

This is how you set the options in `ember-cli-build.js`:
```
  'ember-cli-workbox': {
     importScriptsTransform: (importScripts) => {
       return importScripts.map((importScript) => {
         return 'FOOBAR' + importScript;
       });
     },
  },
```

How can we send a function as an option to an addon? Is there another way to do it that doesnt have to be serializable?

**Comment by rwjblue** [comment]
In general the ember-cli-build.js options are not going to be serialized, and that should be a safe mechanism. The `config/environment.js` itself is intended to be serialized (to JSON) so that option is out regardless.

This is most likely an issue with ember-cli-workbox, would you mind filing an issue over there (and cross linking this one so future folks that stumble by will have another breadcrumb to follow)?

Happy to reopen if this comes back and turns into an issue with ember-cli...

**Comment by rwjblue** [comment]
Ahh looks like you already opened one over there: https://github.com/BBVAEngineering/ember-cli-workbox/issues/105.
