### ISSUE TITLE
Thoughts on automatically selecting a new port if there is a port conflict?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli#9512]
I was starting an unrelated tool and had this output, which was quite the delight!
![image](https://user-images.githubusercontent.com/199018/115960883-dd294b80-a4e1-11eb-9c22-cc96dc261682.png)

```
HTML Pages is Online! 🚀
Serving {project} at http://10.0.2.15:4201 (on port 4201, because 4200 is already in use)
The address was copied to the clipboard :)

Server is ready!
```
the port changing and dumping the address to the clipboard is neat (even though I'm just going to use localhost, cause reasons)

**Comment by takshch** [comment]
@NullVoxPopuli I think it can produce unnecessary complexity for the developer.
Sometimes, port is harded in environment and if port automatically changed, then it will result in errors and issues.
So, I think we should use a flag like `--auto-port` because if developer used this flag, then that developer might know what it is about and they can handle accordingly.

Please tell me what do you think?

**Comment by rwjblue** [comment]
FWIW, you can get this behavior manually by setting the port to 0 (`--port 0`).

We've talked a bit about making that the default before. I'd be in favor.

**Comment by takshch** [comment]
@rwjblue Can you please mention the link where i can see the discussion.

**Comment by rwjblue** [comment]
Sorry, I more mean in discord/slack (long ago) conversations amongst ember-cli core team folks (Stef, Tobi, Kelly, myself, etc).

**Comment by bertdeblock** [comment]
I've been testing this out locally, and I think it should be fairly easy to make `--port 0` the default, but still have `ember s` pick `4200` first.
