### ISSUE TITLE
[Feature] Add linting TODO scripts to app/addon blueprints

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-cli#9588]
ember-template-lint v3, which is now the default version in the blueprint, has added the ability to temporarily silence lint errors as TODOs: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/todos.md

There are two scripts for managing the TODO workflow:
* Creating TODOs - `ember-template-lint . --update-todo`
* Cleaning Resolved TODOs - `ember-template-lint . --clean-todo`

We already have a bunch of linting scripts for JS/HBS files in the package.json for Ember blueprints here: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L15-L20

We should add to this suite of lint commands as useful shortcuts for the TODO workflow, perhaps `lint:hbs:todo:update` and `lint:hbs:todo:clean`. We can exclude them from being run by the default `yarn lint` command by excluding all `todo` scripts the way we exclude `fix` scripts. This will make TODOs a more integrated part of the yarn lint scripts, enabling developers to integrate those workflows more easily!

Similar functionality also exists for eslint (though Ember blueprints don't yet include this by default): https://github.com/scalvert/eslint-formatter-todo

If that becomes adopted as a default, we can use the same pattern there as well.

**Comment by locks** [comment]
Sorry for the long turnaround! This was discussed at today's ember-cli meeting.
`ember-template-lint` has changed considerably since this issue was issued and now automatically cleans up todos, which already alleviates half of the issue 😁 
The team also felt that `yarn lint:hbs:todo:update` is not better that much ergonomic than `yarn ember-template-lint . --update-todo` and, in the words of Rob, every line in the blueprints has to pay its weight in gold 😂 A suggestion is to create a codemod thata can add the required commands for you! Thanks for bringing the issue to the team 💪
