### ISSUE TITLE
Remove `ie 11` from default targets

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9884]
https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/default-targets.js

**Comment by rwjblue** [comment]
We can't remove completely because we have never deprecated **not** having a targets file defined:

https://github.com/ember-cli/ember-cli/blob/983bdcb7a58f6361d650bf73dba5a644a51daf7c/lib/models/project.js#L311-L315

We should:

* Add a deprecation in that `else` case (`until: '5.0.0'`)
* Possibly update the project to detect if `ember-source` is >= 4 (but being careful not to **require** `ember-source` dependency), and if so don't include IE11 (otherwise fallback to current contents)

**Comment by ef4** [comment]
I confirmed that a 3.28 app with no targets file still sees the IE11 deprecation warning.

This means to me that we gave fair warning about the requirement to remove IE11 (which implies creating a targets.js). In other words, to run cleanly without deprecations on 3.28 you had to create targets.js and remove IE11 from it.

So I'm OK with dropping it from the defaults when you don't have a targets.js file.
