### ISSUE TITLE
Test against Node v18

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#9905]
Node v18 is a current stable release and will be the next LTS. According to our Node support document, we should already be testing against.

**Comment by boris-petrov** [comment]
I personally can't run `ember-cli` on Node 18. Running my project leads to:

```
Build Error (PostcssCompiler)                                                                                                                                 
                                                                                                                                                              
You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
```

I believe that's because of a [bug](https://github.com/mozilla/source-map/issues/432) in `source-map` that has since been fixed but only released in a beta `0.8.0-beta.0`. I've got a lower version than that coming from many, many dependencies. One of them is `fast-sourcemap-concat`. Even if I pin `source-map` to version `0.8.0-beta.0`, I get an error from it:

```
Cannot find module 'source-map/lib/source-map/base64-vlq'
Require stack:
- /home/boris/project/node_modules/fast-sourcemap-concat/lib/vlq.js
- /home/boris/project/node_modules/fast-sourcemap-concat/lib/coder.js
- /home/boris/project/node_modules/fast-sourcemap-concat/lib/source-map.js
- /home/boris/project/node_modules/fast-sourcemap-concat/lib/index.js
- /home/boris/project/node_modules/broccoli-concat/index.js
- /home/boris/project/node_modules/ember-source/lib/concat-bundle.js
- /home/boris/project/node_modules/ember-source/lib/index.js
- /home/boris/project/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /home/boris/project/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /home/boris/project/node_modules/ember-cli/lib/models/project.js
- /home/boris/project/node_modules/ember-cli/lib/utilities/get-config.js
- /home/boris/project/node_modules/ember-cli/lib/utilities/instrumentation.js
- /home/boris/project/node_modules/ember-cli/lib/cli/index.js
- /usr/lib/node_modules/ember-cli/bin/ember
```

So I guess it's going to be pretty difficult to run `ember-cli` on Node 18...

**Comment by jacobq** [comment]
Yes, I ran into that too (https://github.com/mozilla/source-map/issues/452), though did not have trouble working around with a resolution. The issue you're seeing with `fast-sourcemap-concat` appears to be because it's using an ancient version (v0.4.3 / July 2015?):
https://github.com/ef4/fast-sourcemap-concat/blob/85d8f280892863f6736740ee41a1bcf5483b8646/lib/vlq.js#L3
and in [v0.5.0 the project layout was changed](https://github.com/mozilla/source-map/compare/0.4.4...0.5.0#diff-161c72bd2149e489b6188f90c54624fee05dbdad80665022ae914a5cefdc31dd): `lib/source-map/x` --> `lib/x`
It doesn't look like there have been any breaking changes to the function so maybe a PR to update it would be acceptable

```diff
-const vlq = require('source-map/lib/source-map/base64-vlq');
+const vlq = require('source-map/lib/base64-vlq');
```

**Comment by boris-petrov** [comment]
Actually I did manage to get `ember-cli` working on Node 18 even with all these "bad" versions of `source-map` by using `NODE_OPTIONS=--no-experimental-fetch`. I've put it in my build-tools and in my `.zshrc` so I can run `ember serve`. Works fine. Of course, that breaks some other apps like VSCode which says that this is an unknown option (it obviously uses a Node version < 18). I workaround that by using `NODE_OPTIONS="" code`... :smile: For now it's OK but a "real" solution would be nice.

**Comment by jacobq** [comment]
> Actually I did manage to get `ember-cli` working on Node 18 even with all these "bad" versions of `source-map` by using `NODE_OPTIONS=--no-experimental-fetch`. I've put it in my build-tools and in my `.zshrc` so I can run `ember serve`. Works fine. Of course, that breaks some other apps like VSCode which says that this is an unknown option (it obviously uses a Node version < 18). I workaround that by using `NODE_OPTIONS="" code`... 😄 For now it's OK but a "real" solution would be nice.

@boris-petrov You can also try this (https://github.com/ef4/fast-sourcemap-concat/pull/66):

```json
"resolutions": {
  "fast-sourcemap-concat": "jacobq/fast-sourcemap-concat#source-map-update"
}
```

**Comment by jacobq** [comment]
> @jacobq thanks for the help! I'll try if that works but note that `fast-sourcemap-concat` also depends on an old version of `sourcemap-validator` which in turn depends on `source-map "~0.1.x"` - not sure if that matters but...

Gotcha, I hadn't noticed that... Looks like [`sourcemap-validator`](https://github.com/ben-ng/sourcemap-validator) only [uses `SourceMapConsumer`](https://github.com/ben-ng/sourcemap-validator/blob/c753c81986cd70e1df58801fc83386eedff0379d/index.js), but that interface [maybe have]((https://github.com/mozilla/source-map/search?o=desc&q=SourceMapConsumer&s=committer-date&type=commits) ) [changed](https://github.com/mozilla/source-map/compare/0.1.43...jacobq:%40jacobq/source-map)...if nothing else, the moving from `lib/source-map` -> `lib/` would require a change in how its used...

If you happen to want to work on it more, feel free to PR the [`@jacobq/source-map`](https://github.com/jacobq/source-map) [fork](https://www.npmjs.com/package/@jacobq/source-map). I created it since the mozilla `source-map` maintainers do not appear to be making releases, accepting PRs, etc. anymore.

**Comment by boris-petrov** [comment]
`terser` switched to some other `source-map` dependency - see [here](https://github.com/terser/terser/pull/1181) and [here](https://github.com/terser/terser/pull/1190). Not sure if relevant but perhaps something similar can be done in `fast-sourcemap-concat`.
